### ISSUE TITLE
[RFC] Mechanism to plugin intrinsic information

### ISSUE THREAD

**Issue by xqdan** [apache/incubator-tvm#2030]
Hi, all,

Storage rewrite pass can support reusing local buffers for load/store and other halide based operations, but for intrinsics we don't for now, but we do need to support inplace since performance matters.

One way to do this is exposing a backend hook for different backends, so they can implement it in a customized way. 
BTW, exposing hooks for backends is very important design in compilers, such as gcc, in which we get lots of hooks in different phases. see https://gcc.gnu.org/onlinedocs/gccint/Scheduling.html

thanks!

**Comment by tqchen** [comment]
can you provide a specific example on what you want?

**Comment by xqdan** [comment]
these are some intrinsics we've done the inplace for our target:
```
// attr [iter_var(cce, , cce)] coproc_scope = 2
    vadd(tvm_access_ptr(0.000000h, Res_UB_F16, 7936, 7936, 2), tvm_access_ptr(0.000000h, Res_UB_F16, 7936, 7936, 1), tvm_access_ptr(0.000000h, Res_UB_F16, 16, 128, 1))
copy_matrix_cc_to_ubuf(tvm_access_ptr(0.000000h, Res_UB_F16, 0, 63488, 2), tvm_access_ptr(0.000000h, Res_UB_F16, 0, 63488, 1))
```

**Comment by xqdan** [comment]
more specific, we can add a backend hook here for Evaluate(intrinsics always is inside of Evaluate node)
https://github.com/dmlc/tvm/blob/master/src/pass/storage_rewrite.cc#L231

**Comment by xqdan** [comment]
### Support buffer reuse for intrinsics
StorageRewrite can reuse/inplace buffers for load/store, and other halide based operations, but doesn't support for intrinsics, just treat intrinsics opaque, since for different backends, thet may get different requirements.  
For ASICs, we may have lots of intrinsics when we are in storage rewrite pass, if we can reuse buffers for these intrinsics, we can get more performance. For example, we can have better performance, if we do inplace for these intrinsics.

```
vadd(tvm_access_ptr(0.000000h, Res_UB_F16, 7936, 7936, 2), tvm_access_ptr(0.000000h, Res_UB_F16, 7936, 7936, 1), tvm_access_ptr(0.000000h, Res_UB_F16, 16, 128, 1))
copy_matrix_cc_to_ubuf(tvm_access_ptr(0.000000h, Res_UB_F16, 0, 63488, 2), tvm_access_ptr(0.000000h, Res_UB_F16, 0, 63488, 1))
```


### How to support this
The main idea is registering hooks for different backends.

The steps to do this

- Expose target name for StorageRewrite
  One way is adding a target name for StorageRewrite. to do this, also we need to a target name in lower api 
  `Stmt StorageRewrite(Stmt stmt, const std::string& target)`

 Another way is having a function like tvm::Target Target::current_target, but this api only works for "with target", we can't get the current target in all passes in build function.

- When check the inplace of stmt, add a hook for Evaluate(intrinsics is always inside of Evaluate node)
```
@@ -229,7 +232,11 @@ class InplaceOpVerifier : public IRVisitor {
     } else if (stmt->is_type<Store>()) {
       Visit_(static_cast<const Store*>(stmt));
     }else if (stmt->is_type<Evaluate>()){
-      Visit_(static_cast<const Evaluate*>(stmt));
+      if (target_.empty()) return false;
+      std::string reuse_hook = "tvm."+target_+".intrin_inplace";
+      const PackedFunc* f = runtime::Registry::Get(reuse_hook);
+      if (f == nullptr) return false;
+      result_ = f(static_cast<const Evaluate*>(stmt));
     } else {
       return false;
     }
```

- Define a target packed function, in which we do analysis for Evaluate node, return the result of inplace for the intrinsics, and register this function to tvm.target.intrin_inplace, both python or c++ packed function is ok.

**Comment by xqdan** [comment]
The steps to do this,
1, we need to give storage rewrite a pass name, so we can tell different backends. we could do this in two ways, one is just adding a parameter target in lower, also adding a parameter for StorageRewrite pass; another is to support getting current target name in anytime anyplace after create target in build, that is to say we may need cr
2,

**Comment by xqdan** [comment]
Thanks.

Suppose we have done what you said, i still don't see we can have a uniform optimizations for different backends, since we may have different optimizations for the same property of different backends, we can not just treat intrinsics as the same for different backends. 

If we want to do it in your way, we need to have intrinsics first and then abstract the properties among them. For operators you mentioned are easy, because those are accessible in public. we can not just have all the ASICs' intrinsics and have a sound and complete design in one public pass. 

Backends hooks are ad hoc, that's true. We have lots of hooks even for a pass in gcc and llvm. In a sense TVM is a Tensor compiler, we should consider to bring some useful and mature design idea from them when we need to, such as this backend hooks design, pass dump ir design(we've done), compilers' separation of compute and schedule, even the basic analysis frameworks such as CFG/DFA.

**Comment by tqchen** [comment]
I think there is some misunderstanding here. To be clear, I did not propose to enumerate all the intrinsics in the pass itself. I just think we will need a formal specification of what this registry is, and how can we design it so that the registry can be used to collect other information about the intrinsic, other than in-place information.

The main danger of this backend hook property is that it is scattered, and one solution to alleviate that is again through a centralized registry like the op registry https://github.com/dmlc/tvm/blob/master/include/tvm/relay/op.h

To give a concrete example, in our case of operator registry.  Currently, relay's op registry allows us to introduce additional attribute about the intrinsic, for example, you can use the following code to introduce an inplace property later, to an later registered operator property "myexp".

```python
from tvm import relay

relay.op.register("myexp", "TInplace", 1)
```

The key here is: 
- We have a centralized registry to go to when we need certain properties. 
- We have a clear documented list of properties that can be registered and queried by the passes https://github.com/dmlc/tvm/blob/master/include/tvm/relay/op_attr_types.h
    - This avoids fragmentation of the code and increases the maintainability 

Note that in your case, assume ```cce.copy``` is a target-dependent intrinsic, then this kind of registry satisfies our need.  So far the operator property registry is only introduced in the high-level IR(relay) I am proposing to design a similar one in the low-level IR, for the intrinsics, and use the intrinsic information registry as "backend hook".

**Comment by xqdan** [comment]
we need to analyze the source and dest operands then decide inplace or not for some intrinsic. how to support this with your proposal.

**Comment by xqdan** [comment]
Having a property registry looks good, but as I said, sometimes we need to analyze some context, then decide the action. I think they are two important solutions for backends support. we can have both.

**Comment by tqchen** [comment]
The registry can register functions with certain signature, for example， FTVMCompute attribute is a function that can take in context, we will need to carefully design what is the context argument to the function though as it would become part of standard

**Comment by xqdan** [comment]
I see. it'good we can register functions. 

- But when we are using, we can have one function for all intrinsics, but we need to register it for each intrinsic, a little bit redundancy，is it?

- different backends may have their own registry, but they may have the same intrinsic name, how to tell the difference in registry mechanism?

**Comment by tqchen** [comment]
@xqdan to follow up on this. I think we should have a global centralized registry attributes where all the backend can register on. 

- For backend specific intrinsics, there should be no naming conflict(e.g. use cuda prefix for cuda only intrinsics). If an intrinsic shares name among backends, that should really mean they need to have similar behavior. We can still get backend specific behavior by having a target aware dispatcher for common names.
- It is true that a single function might be able to cover multiple intrinsic, in that case, just register it for each intrinsic is not redundant, note that the function is only defined once.
- We can enable any arguments to the registered function, but should really be careful about the choice and document it properly

**Comment by xqdan** [comment]
actually I think my pr is enough for this case. also we don't need to register repeatly for each intrinsic, obviously it's better.

**Comment by tqchen** [comment]
While the current PR is enough for this case, let us try to push the centralized attribute registry instead, for the following reasons:

- We will need a centralized place to document and use these intrinsic attribute, the hook function is a bit hidden and harder for new developers to get started
- It is sometimes helpful to have a per intrinsic behavior and specifically enumerate these behaviors in a sensible fashion.
- The backend implementation of checking can be reused across multiple locations.

To elaborate, if we expect there is going to be a lot of customizable behaviors via backend hook function, the concern is not only how to enable what we want, but how to maintain these attributes in a way that every developer can understand and hack on.

**Comment by xqdan** [comment]
I see. I can act on this.

**Comment by tqchen** [comment]
close this for now. 

The new Unified IR RFC #4617 covers this aspect, by using relay's Op as a single source to register the related information. 

The follow up refactors will be able to reflect that
