### ISSUE TITLE
[RFC] eBPF backend

### ISSUE THREAD

**Issue by ajtulloch** [apache/incubator-tvm#2146]
eBPF (https://lwn.net/Articles/740157/) is a pretty powerful new technology in modern Linux kernels, that essentially embeds a simple bytecode interpreter into the kernel, allowing users to efficiently insert custom logic at various places in the kernel (i.e. packet filtering, tracepoints, perf events, etc). There's been increasing uptake of eBPF in industry and other places, particularly for line-rate packet filtering with XDP (e.g. https://code.fb.com/open-source/open-sourcing-katran-a-scalable-network-load-balancer/). This already enables (to some extent) execution of ML models in new places (i.e. 
 running decision trees for DDOS filtering directly in the NIC via e.g. https://github.com/ajtulloch/sklearn-compiledtrees/tree/bpf), but it'd be quite interesting (IMO) to expose the power/convenience of TVM to kernel/system developers. 

There are several applications of this kind of tool already, under the relatively nascent field of 'ML for systems', i.e.

- models for packet filtering
- models for various kernel cache eviction policies
- etc.

Several developers (e.g. @jroesch) are pretty familiar with (e)BPF, so I wonder if they have thoughts on the utility of something like this?

A simple backend generating eBPF bytecode requires a fairly trivial subclassing of CodeGenLLVM (e.g. https://github.com/ajtulloch/tvm/tree/bpf), but there are lots of details around arg passing, utilities to integrate with existing tracepoints, optimizing/modifying the generated IR to satisfy the verifier, etc that would need to be addressed.

**Comment by tqchen** [comment]
This sounds good, but I am wondering what would the runtime of them looks like, is it possible to expose an TVM runtime like API like we did for SGX?

**Comment by jroesch** [comment]
This sounds good to me too, would be cool to have some demos/targets to push forward. Could we create a little benchmark suite filled with the kinds of things it would be good to support.

**Comment by tqchen** [comment]
closing for now due to inactive status, we can always open new one as we plan to work on it
