### ISSUE TITLE
[WEB] Recover WASM and JS Flow on the Latest Emscripten

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-tvm#2425]
There have been some problems in using the web flow on the latest version of Emscripten. The main reason seems due to Emscripten moves the default from ASMJS to WASM and there is some gap in vector support.

It would be great if someone can look into them and revive the support. More generally, given the amount of interest in web support, we might want to do an upgrade to also move more of our runtime to WASM(perhaps with the rust runtime by @nhynes ) and do a proper interface with the tvm_runtime.js  for the cases that do not rely on WebGL.

**Comment by DavidGOrtega** [comment]
I'm looking the code. I'm interested on this. Should be possible to put back the code to a stable release before the change?

Also, should not WASM be compatible with ASMjs?

**Comment by tqchen** [comment]
WASM is compatible with ASMJS, but we might need some runtime changes to make sure that the runtime can hook into both of them.

We might not need the emscripten layer if we use the pure WASM

**Comment by tqchen** [comment]
The new webgpu and wasm support are now landed in the mainline
