### ISSUE TITLE
[Relay][RFC] Support layout altering for heterogeneous compilation

### ISSUE THREAD

**Issue by zhiics** [apache/incubator-tvm#2566]
The current `AlterOpLayout` optimization pass is implemented with only one target. For heterogeneous execution, we may need multiple targets for different `CallNode`. This RFC proposes to enable AlterOpLayout in heterogeneous compilation.

I am thinking of the following changes:
1. Pass `target` that could be a `dict` or tvm.Target to this pass. 
`def alter_op_layout(expr)` to `def alter_op_layout(expr, target)`
2. Collect the device information of each CallNode in the `func`.
3. Let [FTVMAlterOpLayout](https://github.com/dmlc/tvm/blob/master/include/tvm/relay/op_attr_types.h#L104) take a `target` attribute.

Another option I am ware of is that we can probably attach an device_callnode_mapping to the function as an attribute, but it looks that we cannot set it on an `Expr`.

@tqchen @merrymercy @yzhliu @jroesch @ZihengJiang, please comment and share any ideas that you may have. Thanks.

**Comment by tqchen** [comment]
Ping @zhiics would be great to comment on the current state

**Comment by zhiics** [comment]
Thanks for reminding. I think we should probably close this for now.
