### ISSUE TITLE
[Relay] restrict the domain of logical operators on bool

### ISSUE THREAD

**Issue by MarisaKirisame** [apache/incubator-tvm#2755]
#2743

**Comment by MarisaKirisame** [comment]
@tqchen I will do it, aint that hard.

**Comment by MarisaKirisame** [comment]
ooh, I know, there's a UW undergrad who want to work on relay. I will leave this to him.

**Comment by tqchen** [comment]
closing for now due to inactive status, we can always open new one as we plan to work on it
