### ISSUE TITLE
[RELAY][BUG] Nonsensical AST

### ISSUE THREAD

**Issue by jroesch** [apache/incubator-tvm#2820]
This currently works and leads to bizarre behavior, personally I believe this should be forbidden.

```
Python 3.7.2 (default, Feb 12 2019, 08:15:36)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from tvm.relay import TensorType
>>> TensorType(("gpu",))
TensorType(["gpu"], float32)
>>>
```

**Comment by jroesch** [comment]
cc @slyubomirsky

**Comment by slyubomirsky** [comment]
The Python bindings should be set up in such a way as to reject strings

**Comment by tqchen** [comment]
What is the status of this issue? We might want to fix promptly or mark as inactive and close it
