### ISSUE TITLE
[BUILD] Conda package to tvm

### ISSUE THREAD

**Issue by marcelotrevisani** [apache/incubator-tvm#3161]
Hello,

I am trying to create a package for ``tvm`` on [conda-forge](https://conda-forge.org/).
I already packaged the whole third-party dependencies. However, I am facing some errors in compilation time.

For now, I am just creating the package for Linux

PR opened for ``tvm`` : https://github.com/conda-forge/staged-recipes/pull/8316

Azure pipeline:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=33508

**Comment by marcelotrevisani** [comment]
TVM dependencies which I had to package:
https://github.com/conda-forge/dlpack-feedstock
https://github.com/conda-forge/dmlc-feedstock
https://github.com/conda-forge/rang-feedstock
https://github.com/conda-forge/halideir-feedstock

**Comment by junrushao1994** [comment]
Looking into the Azure pipeline, I saw the following error message
```
/home/conda/feedstock_root/build_artifacts/tvm_1557397107698/work/include/tvm/runtime/device_api.h: In function 'const char* tvm::runtime::DeviceName(int)':
/home/conda/feedstock_root/build_artifacts/tvm_1557397107698/work/include/tvm/runtime/device_api.h:194:10: error: 'kDLVulkan' was not declared in this scope
     case kDLVulkan: return "vulkan";
          ^~~~~~~~~
/home/conda/feedstock_root/build_artifacts/tvm_1557397107698/work/include/tvm/runtime/device_api.h:194:10: note: suggested alternative: 'kDLFloat'
     case kDLVulkan: return "vulkan";
          ^~~~~~~~~
          kDLFloat
/home/conda/feedstock_root/build_artifacts/tvm_1557397107698/work/include/tvm/runtime/device_api.h:199:10: error: 'kDLExtDev' was not declared in this scope
     case kDLExtDev: return "ext_dev";
          ^~~~~~~~~
```

`kDLVulkan` is defined in `3rdparty/dlpack/include/dlpack/dlpack.h`, so I would say that there might be some issues with the include search path.

**Comment by marcelotrevisani** [comment]
Hi @junrushao1994 , thanks for your answer 

I see I will try to add it then!
Any news I will continue to post here

**Comment by marcelotrevisani** [comment]
I am seeing a different error now
Please see
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=33871

**Comment by junrushao1994** [comment]
Hey, template with c linkage typically means that we are using `external C` somewhere but enclosed with c++ code, like templates. I am not an expert in building conda packages, but where can I see your build configurations files? Thanks!

**Comment by marcelotrevisani** [comment]
What do you mean by build configuration files?
environment variables which might be used are shown at the beginning of the build

**Comment by junrushao1994** [comment]
@marcelotrevisani Cool i will try building these stuff offline and get back to you asap

**Comment by marcelotrevisani** [comment]
@junrushao1994 , I think without the conda environment would be difficult to replicate the errors.
If you want to, you can download `[miniconda](https://docs.conda.io/en/latest/miniconda.html), install it, after that, you need to install the ``conda-build`` and add the ``conda-forge`` channel:
```
conda config --add channels conda-forge
conda install conda-build
```

so, you will need the recipe for ``tvm``, basically it is in my branch ``add-tvm``
https://github.com/marcelotrevisani/staged-recipes/tree/add-tvm

inside of the folder ``recipes/tvm``, just execute:
```
conda build . --dirty
```

The option ``dirty`` is just telling conda to not delete the environment after the build

**Comment by junrushao1994** [comment]
Hey I lost access to your branch today...

**Comment by marcelotrevisani** [comment]
Oh sorry for my delay. I deleted my fork. I am going to recreate it then

**Comment by PercyLau** [comment]
Hi, there! Anything new? I am struggling with compile tvm with anaconda environment.

**Comment by marcelotrevisani** [comment]
> Hi, there! Anything new? I am struggling with compile tvm with anaconda environment.

I am going to work wit it today

**Comment by marcelotrevisani** [comment]
@junrushao1994 
is it possible to use the nnvm compiler just compiling the tvm with gcc 7?

**Comment by marcelotrevisani** [comment]
> Hey I lost access to your branch today...

This branch is up again
