### ISSUE TITLE
[RFC] Real-Time Android Camera Demo

### ISSUE THREAD

**Issue by eqy** [apache/incubator-tvm#3192]
We recently implemented a camera demo that runs vision models in real time on android phones (with relatively beefy CPUs, such as the Pixel 2). Is there any interest in adding this to the collection of reference apps? This would also enable going directly from pretrained MxNet models to the corresponding library and parameter files for the phone.

**Comment by ColdCodeCool** [comment]
Yes, I am about to implement HDRnet in Real-Time on Android. Your effort would be great helpful to me.

**Comment by JiaoPaner** [comment]
Can you create a repository for this firstly ? I want to learn how to build a android app via tvm in detail ,the official docs is so confused for android.Thanks.

**Comment by tqchen** [comment]
#5005
