### ISSUE TITLE
[Relay] Improve frontend testing infrastructure.

### ISSUE THREAD

**Issue by jroesch** [apache/incubator-tvm#3247]
There has been a recent number of issues found in various frontends for Relay. I propose to ensure robustness and compatibility with popular model architectures we make an effort to import commonly used models and test their correctness. 

We should consider more complex scenarios such as PyTorch -> ONNX -> Relay. I have added some initial tests in #3084 but there are still some issues in supporting all of `torchvision`.

**Comment by tqchen** [comment]
close for now, the testcases has been improving and it would be good to open new smaller items that are actionable
