### ISSUE TITLE
[Feature Request] Support dot op in frontend 

### ISSUE THREAD

**Issue by antinucleon** [apache/incubator-tvm#3276]
eg: http://mxnet.incubator.apache.org/api/python/ndarray/ndarray.html?highlight=dot#mxnet.ndarray.dot

**Comment by jroesch** [comment]
cc @icemelon9 I thought you were working on `dot` at some point

**Comment by icemelon9** [comment]
Yes, I added AutoTVM template for dense op for better performance. But I think Bing is asking a full support of dot op. Currently dense op only supports AB^T.
