### ISSUE TITLE
[Hybrid Script] Code refactor, merging 2 symbol tables.

### ISSUE THREAD

**Issue by were** [apache/incubator-tvm#3339]
@merrymercy #3157 
I want to merge 2 symbol tables. Actually, I already have a symbol table to capture the global functions, and capturing the global variables should be very similar. Thus there is no point to have both `closure` and `symbols` 2 symbol tables.

I will open a PR to fix this these days.

Sorry I was too busy at the beginning of last month.

Thanks.

**Comment by tqchen** [comment]
@were what is the status on this?

**Comment by tqchen** [comment]
ping @were

**Comment by were** [comment]
Jesus, let me get some bandwidth this week. I am too busy now.

**Comment by tqchen** [comment]
ping @were
