### ISSUE TITLE
support for conv1D

### ISSUE THREAD

**Issue by mengquanrun** [apache/incubator-tvm#3518]
i want to compile a model which has some conv1D layers, and it seems like that relay cannot support conv1D, so i want to know is there some difficulties which are hard to solve? 
and i find that all operations about 1D are not supported by now, so i want to know the key difficulties about it.

Thanks  @Huyuwei

**Comment by Huyuwei** [comment]
It's just because conv1D hasn't been implemented. Most efforts are spent on optimizing models for image tasks that mainly rely on conv2D.

Is it possible to express conv1D as conv2D with kernel size being (convd_kernel_size, 1)?
