### ISSUE TITLE
OpNotImplemented: The following operators are not supported for frontend ONNX：LSTM

### ISSUE THREAD

**Issue by kunyao2015** [apache/incubator-tvm#3544]
I have converted CRNN model from pytorch into onnx format, and using codes like this:
`
target = 'llvm'

input_name = '0'
shape_dict = {input_name: x.shape}
mod, params = relay.frontend.from_onnx(onnx_model, shape_dict)

with relay.build_config(opt_level=1):
 intrp = relay.build_module.create_executor('graph', mod, tvm.cpu(0), target)
`

ERROR:
OpNotImplemented: The following operators are not supported for frontend ONNX：LSTM

I don't konw how to solve it

**Comment by loiccordone** [comment]
I second this, maybe you can provide us insights in the docs on how to develop operators for the ONNX and other frontends?
I'm encountering difficulties with inputs, attr, the calls to _op.X and AttrCvt, etc. while trying to implement ConstantOfShape, LSTM, and Tile.

Thanks ! @zhiics

**Comment by zacario-li** [comment]
> I second this, maybe you can provide us insights in the docs on how to develop operators for the ONNX and other frontends?
> I'm encountering difficulties with inputs, attr, the calls to _op.X and AttrCvt, etc. while trying to implement ConstantOfShape, LSTM, and Tile.
> 
> Thanks ! @zhiics

Same situation with you. I'm trying to implement ConstantOfShape

**Comment by tqchen** [comment]
https://github.com/apache/incubator-tvm/pull/4825
