### ISSUE TITLE
Int8 NHWC pack tensorize failure

### ISSUE THREAD

**Issue by anijain2305** [apache/incubator-tvm#3598]
If I replace `llvm` with `llvm -mcpu=skylake-avx512` at 

https://github.com/dmlc/tvm/blob/master/topi/tests/python/test_topi_conv2d_nhwc_pack_int8.py#L67

, the test fails with the following error

~~~
  File "/home/ubuntu/workplace/t1/tvm/src/op/tensorize.cc", line 226
TVMError: Check failed: is_one(e.region[i]->extent): Tensorize tensor_intrin: Input dimension mismatch with tensor intrin  expected shape=[16, 4], given region=[range(min=0, ext=1), range(min=0, ext=1), range(min=((ff.outer*16)/16), ext=(((((ff.outer*16) + 15)/16) + 1) - ff.outer)), range(min=(((((rc.outer.outer*16) + rc.outer.inner)*4)/4)*16), ext=((((((((rc.outer.outer*64) + (rc.outer.inner*4)) + 3)/4)*16) + 16) - (rc.outer.inner*16)) - (rc.outer.outer*256))), range(min=0, ext=4)]
~~~

@llyfacebook Can you please take a look?

**Comment by tqchen** [comment]
It seems was due to the recent revamp of integer simplification infra. One solution could be to introduce the bound information of the indices, (to hint ff.outer is non-negative) of Analyzer infra to tensorize.cc so the division simplification can be carried effectively. 

Another way would be to carry through the floordiv/mod change(I could do that but need to wait a few weeks due to recent time constrains).

Would be helpful if anyone could try the first approach

**Comment by llyfacebook** [comment]
It seems to be broken some time ago (Even before https://github.com/dmlc/tvm/pull/3526). Fortunately, I still have a working copy locally and try to dig into it this week.

**Comment by tqchen** [comment]
@llyfacebook @anijain2305  the reason was likely due what i mentioned in the last post(not being able to simplify certain expressions), we could try the proposed solutions

**Comment by anijain2305** [comment]
@tqchen Makes sense. As of now, I am busy with other stuff. Let's keep status help wanted for now. Maybe I can take a look later when I get some free cycles.

**Comment by anijain2305** [comment]
@tqchen @sgrechanik-h I am seeing this failure for my own tensorize implementations, prompting me to make this a priority to fix.

However, I have never touched this piece of code. Can you please do more little more hand-holding to help me solve the problem?

**Comment by jwfromm** [comment]
Just wanted to add that I'm also encountering this bug when using tensorize in some places.

**Comment by tqchen** [comment]
To elaborate a bit, the simplification would need hints about bounds of the iteration variables(that they are not negative). This information can be put into the simplifier of tensorizer so that the expression can be simplified

**Comment by anijain2305** [comment]
https://github.com/dmlc/tvm/pull/3981

@kimishpatel and @tchen are working on this

**Comment by tqchen** [comment]
closing for now due to inactive status, the new simplifier might resolve the problem, feel free to reopen
