### ISSUE TITLE
[AUTOTVM] Cleanup subprocess when main process exit abnormally

### ISSUE THREAD

**Issue by ghostplant** [apache/incubator-tvm#3602]
TVM engine uses many new python subprocesses to allocate tasks for kernel tuning. However, the problem is it doesn't clean all these processes when the main process is terminated before tuning is total done which takes unknown time to finish or other purpose for cancelling jobs manually.

This issue happens conditionally, so it might depend on what kind of work the subprocess is doing when the main process is to terminate.

Any plan to fix it?

**Comment by tqchen** [comment]
This seems to be a reasonable thing to fix, @ghostplant can you try to look into that? Likely setting the process to be demo would enable that

**Comment by ghostplant** [comment]
There are many TVM modes (e.g. remote server/local) and many components (e.g. XGBoost)  using sub-process which is managed multiple times from difference places, or even outside the management of TVM (e.g. XGBoost multiprocessing pool), so I think fixing it within TVM thoroughly seems not to be a quite reasonable workload, so that is why I create this issue instead of submitting a PR  :）

**Comment by tqchen** [comment]
Every issues need to be actionable. So while this is a problem that we need to address, it would be great if you can send in PRs on places you see that can partly address it. Then we go from there.

**Comment by tqchen** [comment]
#3640
