### ISSUE TITLE
[Rust] Runtime failed on windows

### ISSUE THREAD

**Issue by GalAster** [apache/incubator-tvm#3653]
- Windows10 X64

Build failure because type mismatch:

![image](https://user-images.githubusercontent.com/17541209/62056257-dbb8e980-b24f-11e9-902b-5aaa0438ca49.png)

https://github.com/dmlc/tvm/blob/cffb4fba03ea582417e2630bd163bca773756af6/rust/common/src/array.rs#L97-L104

`DLContext` seems defined in `CARGO_MANIFEST_DIR/src/c_runtime_api.rs`

It does an `i32` on my system.

![image](https://user-images.githubusercontent.com/17541209/62055988-4289d300-b24f-11e9-9bfb-ba1187006839.png)

---

If I changed to `i32`, `tvm-common` works but I still can't load `test.o`

I found that `goblin::Object::PE` has not been implemented yet.

But the previous step also has a problem, the result of `goblin::Object::parse(&buffer)` is `Unknow`, I can do nothing with that.

It was produced by llvm, I don't know why it can't be parsed.

So, how can I go further.

**Comment by tqchen** [comment]
cc @nhynes

**Comment by nhynes** [comment]
Cool, thanks for the report! I'll spin up a windows vm and give this a look. I didn't think anyone would be determined enough to get LLVM and friends working on windows, so I didn't even test this flow :)

**Comment by tqchen** [comment]
I believe this is fixed, so close for now. feel free to create another thread
