### ISSUE TITLE
[Relay][Documentation] List of passes invoked by opt_level does not seem to have been updated

### ISSUE THREAD

**Issue by slyubomirsky** [apache/incubator-tvm#3761]
The comment for `relay.transform.build_config()` gives the following list of passes per optimization level:
```
            OPT_PASS_LEVEL = {
                "SimplifyInference": 0,
                "OpFusion": 1,
                "FoldConstant": 2,
                "CombineParallelConv2D": 3,
                "FoldScaleAxis": 3,
                "AlterOpLayout": 3,
                "CanonicalizeOps": 3,
                "EliminateCommonSubexpr": 3,
            }
```

However, looking at the implementation of `Optimize()` in `src/relay/backend/build_module.cc`, I see more passes than just these being invoked and it is not clear from reading the code how the optimization level is taken into account. E.g.,
```
    pass_seqs.push_back(transform::EliminateCommonSubexpr(fskip));
    pass_seqs.push_back(transform::CombineParallelConv2D(3));
    pass_seqs.push_back(transform::FoldConstant());
    pass_seqs.push_back(transform::FoldScaleAxis());
    pass_seqs.push_back(transform::CanonicalizeCast());
    pass_seqs.push_back(transform::CanonicalizeOps());
```
(`CanonicalizeCast` was not listed in the comment quoted before.)

Is there any more accurate way we can document the passes that are invoked based on the optimization level specified? The implementations of files like `build_module.cc` and `transform.cc` are complicated at times and it takes a lot of reading to understand what exactly each part does.

**Comment by zhiics** [comment]
yeah, I agree that we need a better way to document/define the optimization level for a pass. I am not sure how the opt level is defined for each pass as well.

Do you think it is necessary to have a `-O` level system to control the passes instead of manually adding them in the `build_module.cc` file? We should probably have a separate doc to explain the passes and opt levels like what gcc does https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html.

**Comment by slyubomirsky** [comment]
I know @jroesch has long been against having the O-levels, so perhaps he might weigh in on this topic.

I dislike that the O-levels are opaque in that there is no stated rationale for the passes included in them nor (as far as I know) much of a process for deciding which passes should be in what level.

**Comment by tqchen** [comment]
close due to inactive status, feel free to open new dev discuss thread on https://discuss.tvm.ai/
