### ISSUE TITLE
[Relay] [RFC] is_cons, unpack_cons, is_s, unpack_s

### ISSUE THREAD

**Issue by MarisaKirisame** [apache/incubator-tvm#3874]
Pattern matching is hard. currently, aot, vm, interpreter all has to implement pattern matching, and it is a huge source of complexity - the most complex code in aot is probably the pattern matcher.

there should be a pass to desugar pattern matching into if/else, however, there is no way to break up an ADT except using pattern matching, so it is impossible.

We should add two function automatically for every constructor:
is_x: is it that constructor?
unpack_x: if it is that constructor, read all values out and put them in a tuple. If not, fatal error.

**Comment by MarisaKirisame** [comment]
@jroesch @wweic wdythink?

**Comment by junrushao1994** [comment]
does this kind of desugar compromise the ability to do dynamic batching?

**Comment by MarisaKirisame** [comment]
@junrushao1994 no. for tensorflow fold style dynamic batching, it seems like partial evaluation will give us a static computation graph, then u can just do static batching (CombineConv2d, etc) on it as usual. If it goes as plan it seems like we dont even need anymore pass (just intergrating these two pass will be enough).

**Comment by wweic** [comment]
I think it's a good idea to add a pass before aot/vm compilation, so we can apply pattern matching compilation optimization techniques only once, aot/vm will just be  a code generation pass. `is_XX`, `unpack_XX` sounds reasonable. These two functions will likely use pattern matching internally, but in a much simpler form. So aot/vm still has to support limited form of pattern matching, right?

**Comment by MarisaKirisame** [comment]
no, these two function is the 'primtive' of adt.
right now, pattern matching is implemented as: check if a pattern match the data, then unpack the data.
the 'check' part is is_x. the 'unpack' part is unpack_x.
one could imagine a typical example as follow:
fun double n = 
  match n
  | O => O
  | S n' => S (S n')
which double a peano natrual.
It could be decompiled into
fun double n =
  if (is_O n) then O else (if (is_S n) then S (S (unpack_S n).0) else fatal "unknown case")

**Comment by wweic** [comment]
@MarisaKirisame Yes, this is what the decompilation pass will do. But eventually interpreter/aot/vm has to deal with `is_X`/`unpack_S` function calls. There are 2 ways to handle them. One way is to change relay core to handle `is_*` and `unpack_*` specially. Another way is to dynamically generate these functions as normal relay function, but that requires some pattern matching support. Which do you think you would choose?

**Comment by MarisaKirisame** [comment]
it will be relay core. there is code inside pattern matching that does is_* and unpack_*, and I think we should expose them as we are a IR.

**Comment by tqchen** [comment]
close for now due to inactive status, feel free to open a new thread
