### ISSUE TITLE
[Relay][Bug] Type unification bug (when unifying quantified functions)

### ISSUE THREAD

**Issue by slyubomirsky** [apache/incubator-tvm#3946]
PR #3559 added the ability to unify functions with type arguments as part of allowing for quantified local functions (needed for continuation-passing style, if I understand correctly). However, unification with quantified functions appears to fail in some cases.

This case (see `test_type_solver.py`) results in a unification exception:
```
    solver = make_solver()
    a, b, c = relay.TypeVar('a'), relay.TypeVar('b'), relay.TypeVar('c')

    ft1 = relay.FuncType([a, relay.TupleType([b, c])], relay.TupleType([a, b, c]), [a, b, c])
    ft2 = relay.FuncType([a, relay.TupleType([a, c])], relay.TupleType([a, a, c]), [a, c])
    unified = solver.Unify(ft1, ft2) # crashes attempting to unify a and b
    assert unified == ft2
```

A case like this should work, since if we have a function `f` with type `fun[a, b, c](a, (b, c)) -> (a, b, c)` and we give it arguments of types `a`, `a`, and `c`, `f` would produce an output of type `(a, a, c)`. However, the unification fails because (I believe) the unification rule for func types makes the assumption that the type variables of the two function types should correspond to each other by their order, which does not hold in this case (`ft2` drops the middle type variable).

It is not clear how to solve this in our present approach to unification -- perhaps instantiate func types with fresh incomplete types in the func type unification case and then bind the result again over the substituted type vars? Should we be generalizing types elsewhere?

Thoughts, @jroesch @MarisaKirisame or others?

**Comment by tqchen** [comment]
https://github.com/apache/incubator-tvm/pull/3947
