### ISSUE TITLE
"Unexpected unqualified-id" with fresh build (Ubuntu16.04 & clang)

### ISSUE THREAD

**Issue by amm0063** [apache/incubator-tvm#4092]
@gussmith23 - This issue is for you, discovered at ADA symposium hackathon
Ubuntu 16.04 with fresh TVM build attempt using clang that comes with LLVM pre-built binary.

When making with `make -j8`, the following errors appear:

`[  5%] Building CXX object CMakeFiles/tvm.dir/src/relay/backend/build_module.cc.o
/home/mccrabb/gus/tvm/3rdparty/posit/posit-wrapper.cc:18:16: error: expected unqualified-id before string constant
 TVM_DLL extern "C" float Posit32es2ToFloat(uint32_t in) {
                ^`
[many errors similar to this, just with different line numbers]

For reference, there are also many warnings with the following error code:
`[  3%] Building CXX object CMakeFiles/tvm_runtime.dir/3rdparty/posit/posit-wrapper.cc.o
In file included from /home/mccrabb/gus/tvm/3rdparty/posit/posit-wrapper.cc:4:0:
/home/mccrabb/gus/tvm/3rdparty/universal/posit/math/sqrt.hpp:381:67: warning: missing terminating ' character
     uint32_t negRem = (shiftedFraction * shiftedFraction) & 0x0003'FFFF;`

**Comment by tqchen** [comment]
close due to inactive status. @gussmith23 can followup
