### ISSUE TITLE
[Relay][Topi] Conv NHWC pack int8 kernel layout

### ISSUE THREAD

**Issue by anijain2305** [apache/incubator-tvm#4122]
Relavant PR - https://github.com/dmlc/tvm/pull/4038

Currently, _declaration_conv_nhwc_pack expects (NHWC, HWOI). However. TOPI expects the kernel layout to be HWIO whenever the input data layout is NHWC. There is no easy way to pass around the kernel_layout to TOPI.

Currently, we are planning to comment out the code to achieve correct functionality. This issue is to record this activity, and track the progress of fixing the schedule.

@llyfacebook plans to take a look for now.

**Comment by tqchen** [comment]
close for now as the relevant PR get merged. Let us open a new thread for new items
