### ISSUE TITLE
Support parameter "out" in the graph runtime debug

### ISSUE THREAD

**Issue by koolkoffee** [apache/incubator-tvm#4203]
https://github.com/dmlc/tvm/blob/1ad6a2af672dbb94861d00985f4b9f8280d04d6e/python/tvm/contrib/debugger/debug_runtime.py#L200

**Comment by tqchen** [comment]
This is something that we should fix to make the semantics consistent with the graph runtime

**Comment by cchung100m** [comment]
Hi @tqchen 

Sorry for my late reply and I will get around to it ASAP.

**Comment by tqchen** [comment]
clsoe by #4598
