### ISSUE TITLE
[RFC][DEV] TVM Project Repo Migration

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-tvm#4212]
Dear Community, as part of of apache incubation process, we will need to migrate our repo to Apache. In order to ensure smooth transition, we have been checking with the committers to set up things correctly, as well as necessary options needed for CI setup. We have done most of that. This is an RFC for migrating the repo. This repo will be transferred to a new location```apache/incubator-tvm```

This RFC proposes to migrate the repo in a week and give everyone in the community a heads up about the move. I will come back with the specific time after confirming with ASF infra. 

Because github handles repo re-direction, likely we do not have to do anything for the migration. However, there might be some CI disruptions which we will aim to make sure to stablize as soon as we migrate the repo.

NOTE: this thread is mirrored to the dev@

**Comment by yzhliu** [comment]
I guess we will also need to change namespace `ml.dmlc.tvm` to `org.apache.tvm` in tvm4j

**Comment by xqdan** [comment]
Are we going to release 0.6 in new repo? @tqchen

**Comment by xqdan** [comment]
@tqchen Thanks. Both ok for us, as long as we can get a release in one or two month, is that possible?

**Comment by tqchen** [comment]
We will do our best to do the release in one to two month :)

**Comment by tqchen** [comment]
NOTE: the repo transfer is scheduled to happen at 9:30am PDT Nov 4th(monday)

**Comment by FrozenGene** [comment]
Does it affect developers? Especially the pull request in progress. Because the git remote url is changed.

**Comment by tqchen** [comment]
The repo has been migrated. All the PR has been preserved and original repo url will still work. We are working to recover the CIs to make sure we get all the original infra
