### ISSUE TITLE
About operators are not implemented

### ISSUE THREAD

**Issue by OriAlpha** [apache/incubator-tvm#4248]
Hi guys,
I am trying convert TensorFlow model to TVM version but have facing following issues 
ERRORS:
The following operators are not implemented: {'RandomUniform'}

Can anyone tell me what is this issue

**Comment by yzhliu** [comment]
currently we don't have random op support at relay level.

**Comment by tqchen** [comment]
consolidate to https://github.com/apache/incubator-tvm/issues/2591 would also be great if we can open new threads in the discuss forum

**Comment by KimBioInfoStudio** [comment]
this op can easily add with using numpy, but  we  want more tvmic op

**Comment by OriAlpha** [comment]
Thanks for Replaying
