### ISSUE TITLE
Feature request of pytorch interpolation and pixelshuffle operator

### ISSUE THREAD

**Issue by CoinCheung** [apache/incubator-tvm#4255]
Hi, 

I can export pytorch operator of `torch.nn.functional.interpolate` and `torch.nn.PixelShuffle` to onnx(opset11). I guess the onnx name of one of them is `Resize` and the other is `DepthtoSpace`. Current I find that tvm does not support the exported onnx operator of them, so I feel maybe it is not bad to open an issue to draw the attention of the community, since these are not so widely used as `conv` or `bn` operators. Please take some time to add support for these operators, thanks !!!

**Comment by tqchen** [comment]
Close for now, please open a new issue requesting the specific op in ONNX
