### ISSUE TITLE
Install from Source doc still says to clone dmlc/tvm

### ISSUE THREAD

**Issue by apivovarov** [apache/incubator-tvm#4256]
tvm moved to https://github.com/apache/incubator-tvm

Install from Source doc still says to clone dmlc/tvm https://docs.tvm.ai/install/from_source.html#build-the-shared-library

**Comment by yongwww** [comment]
besides this, we can see this issue (`github.com/dmlc/tvm`) in tons of other files. @tqchen

**Comment by tqchen** [comment]
Should be fixed by https://github.com/apache/incubator-tvm/pull/4257
