### ISSUE TITLE
[TEST][FLAKY] darknet/test_forward.py::test_forward_conv_batch_norm

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-tvm#4284]
http://ci.tvm.ai:8080/blue/rest/organizations/jenkins/pipelines/tvm/branches/master/runs/12/nodes/239/log/?start=0

**Comment by yongwww** [comment]
@siju-samuel  seems the flaky issue was introduced by DarkNet itself? test cases for batch_norm in other frontends are working well even w/ much smaller tolerance (`tvm.testing.assert_allclose(x, tvm_out, rtol=1e-5, atol=1e-5)`).

**Comment by tqchen** [comment]
could due to random number for variance issue, introduced a solution in https://github.com/apache/incubator-tvm/pull/4571, close for now
