### ISSUE TITLE
[Relay](TVM] tensor expression language

### ISSUE THREAD

**Issue by SemanticBeeng** [apache/incubator-tvm#4302]
Is the "tensor expression language" meant to also express and handle `tensor network`s?

Context
1.  https://github.com/google/TensorNetwork
2. https://twitter.com/semanticbeeng/status/1185928629743738885

**Comment by tqchen** [comment]
Thanks for asking the question, the community uses discuss forum to to discuss related questions, please open a new thread on https://discuss.tvm.ai/
