### ISSUE TITLE
Could I change the channel numbers on ResNet18 for pynq implementation

### ISSUE THREAD

**Issue by LYang-666** [apache/incubator-tvm#4354]
Hi!  
      Could I change the channel numbers for resnet18 using the given bitstream to implement on pynq. In other words, does the given bitstream (eg.,  1x16_i8w8a32_15_15_18_17.bit)  has the fixed conv  structure(fixed channels, filters number .. ), or it only related to the parameters on pynq_sample.json ?

     Thank you very much!

**Comment by tqchen** [comment]
Thanks for asking the question, please open a new thread on https://discuss.tvm.ai/
