### ISSUE TITLE
Is TVM incompatible with python's multiprocessing module?

### ISSUE THREAD

**Issue by Starethics** [apache/incubator-tvm#4355]
Hi there,
I was building a deep learning server that contains multiple CNN modules (some of these models were transformed into TVM for acceleration). I used multiprocessing.Process to run all the CNN modules in parallel.
However, this server occasionally and randomly hung after processing hundreds of requests. And this hanging seems to be very likely caused by combination of TVM and multiprocessing module. Because only if I turn off TVM can the server run stably without hanging.
Can TVM work with python's multiprocessing? if not, is there anyway to fix this issue?
Thanks a lot!

**Comment by zhiics** [comment]
@Starethics Could you please open the thread at the discussion forum: https://discuss.tvm.ai ? That's usually the place we post questions. Thanks.
