### ISSUE TITLE
I have trouble installing tvm.

### ISSUE THREAD

**Issue by wowow11111** [apache/incubator-tvm#4356]
Hello, I have serious issue getting TVM on my desktop, Wiindows10.

I'm trying to follow your tutorial-Intallation-Install from source
and I don't know how much you should be experienced to use this tool but
I got stuck from the first sentence : "build the shared library from C++ codes" because I didn't get shared anything!

It's been like 5 hours so far trying to get this tool on my desktop.
And now I am very confused to list the things I've tried for last few hours, but I have 
<< cmake-3.16.0-rc3-win64-x64.msi >> set up for sure,
<< cmake-3.16.0-rc3-win64-x64 >> unziped,
<< msys2-x86_64-20190524 >> installed and installed pacman ( I was made to do this in one of Readme script in CMake)
<< cmake-3.16.0-rc3 >> unziped,
<< incubator-tvm-master >> unziped which is  from GitHub.

I really am desperate for help. The instructions on the page  https://docs.tvm.ai/install/from_source.html#            seems to be too unkind for me to follow.

**Comment by wowow11111** [comment]
I am just starting my deep learning related study right now. So I don't have any other software tools than VS 2015. (I got Quartus, AVR, ADS, matlab, ... but I don't think those matters)

**Comment by jmorrill** [comment]
I think the devs suggest these conversations happen on http://discuss.tvm.ai

I do have a post about windows and tvm here where we can discuss further: https://discuss.tvm.ai/t/unofficial-autotvm-on-windows-guide/4711

Note that you do not need my fork if you're not doing autotvm.  But the instructions might be useful still... And my fork is extremely experimental.  Use at your own peril.

**Comment by tqchen** [comment]
Thanks and let us move to discuss
