### ISSUE TITLE
I think the dependency of topi is broken

### ISSUE THREAD

**Issue by CoinCheung** [apache/incubator-tvm#4361]
After building following the (documentation)[https://docs.tvm.ai/install/from_source.html]. I tried to import topi, and I got the error: 

```python
import topi
```

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/root/build/tvm/topi/python/topi/__init__.py", line 26, in <module>
    from . import nn

  File "/root/build/tvm/topi/python/topi/nn/__init__.py", line 6, in <module>
    from .deformable_conv2d import *

  File "/root/build/tvm/topi/python/topi/nn/deformable_conv2d.py", line 23, in <module>
    from ..cpp.image import bilinear_sample_nchw

ImportError: cannot import name 'bilinear_sample_nchw'

**Comment by OriAlpha** [comment]
ya it's true, but there is a temporary fix for that  

export LD_LIBRARY_PATH=/home/user/.local/lib/python3.6/site-packages/topi-0.6.dev0-py3.6.egg/topi

**Comment by junrushao1994** [comment]
Hmmm I am not sure, but I think probably the best way to use TVM is just setup PYTHONPATH, but not to pip install it, as it is not formally a pip package yet.

**Comment by CoinCheung** [comment]
Thanks, the method of exporting `PYTHONPATH` is really good. I am closing this.
