### ISSUE TITLE
About model conversion to TVM 

### ISSUE THREAD

**Issue by OriAlpha** [apache/incubator-tvm#4362]
Hallo, 

I have tried to compile model to TVM, and the model is consists of a 1SimpleRNN layer and dense layers. but when I try to compile it gives out me error. 

AttributeError: <class 'tvm.relay.expr.Call'> has no attribute type_annotation

Anyone know this issue

**Comment by tqchen** [comment]
Thanks for bringing this up. Please open threads on https://discuss.tvm.ai/ :)
