### ISSUE TITLE
correct the instructions/scripts after repository name is changed to incubator-tvm

### ISSUE THREAD

**Issue by gittripley** [apache/incubator-tvm#4376]
I started to follow the instructions to use tvm and found that many places are still using tvm instead of incubator-tvm.

For example, in https://docs.tvm.ai/tutorials/cross_compilation_and_rpc.html#sphx-glr-tutorials-cross-compilation-and-rpc-py

```
git clone --recursive https://github.com/apache/incubator-tvm
cd tvm
```

**Comment by tqchen** [comment]
great points, can you send a PR to fix this? we need to change that to

```
git clone --recursive https://github.com/apache/incubator-tvm tvm
```

**Comment by gittripley** [comment]
@tqchen 
It looks like I don't have the permission to raise PR.

```
Username for 'https://github.com': gittripley
Password for 'https://gittripley@github.com':
remote: Permission to apache/incubator-tvm.git denied to gittripley.
fatal: unable to access 'https://github.com/apache/incubator-tvm.git/': The requested URL returned error: 403
```

**Comment by gittripley** [comment]
https://github.com/apache/incubator-tvm/pull/4398 is merged.

**Comment by tqchen** [comment]
Thanks @gittripley !
