### ISSUE TITLE
The python binding copies over and installs again libtvm.so and libtvm_runtime.so that have already been istalled by tvm

### ISSUE THREAD

**Issue by yurivict** [apache/incubator-tvm#4411]
It installs these two files:
```
tvm/libtvm.so
tvm/libtvm_runtime.so
```
such that they are under $(PREFIX):
$(PREFIX}/tvm/libtvm.so and $(PREFIX}/tvm/libtvm_runtime.so.

**Comment by tqchen** [comment]
This is the expected behavior of the installation, as sometimes users do not want to install the libtvm into their system path. The path selection code in the python works for both cases.

**Comment by yurivict** [comment]
So eventually the system would be full of multiple copies of various files and there would be plenty of confusion.

**Comment by tqchen** [comment]
This is unfortunately a trade-off we have to make. Most of the python users are not used to install libraries as system-level dependencies, and we want to be able to enable those use cases as well
