### ISSUE TITLE
[PYTHON] Add optional dependencies to extras_require in setup.py

### ISSUE THREAD

**Issue by yurivict** [apache/incubator-tvm#4413]
This file imports ````tornado```:
```
tvm/rpc/proxy.py:    import tornado
```
but ```setup.py``` doesn't mention it as a dependency.

Same with PIL:
```
tvm/relay/testing/yolo_detection.py:    from PIL import Image
```

Please review what libraries are needed and add them to ```setup.py```.

**Comment by tqchen** [comment]
Thanks for reporting the problem, these are extra optional dependencies that are only needed for the running tests or using the specified feature. Perhaps we should add them to the ```extras_require``` fields

**Comment by yurivict** [comment]
> Perhaps we should add them to the extras_require fields

Yes.
