### ISSUE TITLE
Build blocked by dmlc/thread_local.h' file not found during android_deploy

### ISSUE THREAD

**Issue by cszhz** [apache/incubator-tvm#4422]
> Task :app:buildJni FAILED
Android NDK: WARNING: APP_PLATFORM android-17 is higher than android:minSdkVersion 1 in /workspace/apps/android_deploy/app/src/main/AndroidManifest.xml. NDK binaries will *not* be compatible with devices older than android-17. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.    
Android NDK: WARNING:/workspace/apps/android_deploy/app/src/main/jni/Android.mk:tvm4j_runtime_packed: non-system libraries in linker flags: -latomic    
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    
Android NDK:     current module    
make: Entering directory `/workspace/apps/android_deploy/app/src/main/jni'
[arm64-v8a] Compile++      : tvm4j_runtime_packed <= org_apache_tvm_native_c_api.cc
In file included from /workspace/apps/android_deploy/app/src/main/jni/org_apache_tvm_native_c_api.cc:25:
In file included from /workspace/apps/android_deploy/app/src/main/jni/tvm_runtime.h:27:
/workspace/apps/android_deploy/app/src/main/jni/../../../../../../include/../src/runtime/c_runtime_api.cc:24:10: fatal error: 'dmlc/thread_local.h' file not found
#include <dmlc/thread_local.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [/workspace/apps/android_deploy/app/src/main/obj/local/arm64-v8a/objs/tvm4j_runtime_packed/org_apache_tvm_native_c_api.o] Error 1
make: Leaving directory `/workspace/apps/android_deploy/app/src/main/jni'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:buildJni'.

**Comment by tqchen** [comment]
Thanks for reporting the problem, please open a new trouble shooting thread on https://discuss.tvm.ai/ where the community members uses for this kind of questions
