### ISSUE TITLE
[DOC] Documentation on Quantization

### ISSUE THREAD

**Issue by masahi** [apache/incubator-tvm#4435]
With v0.6 adding quantization support, I think it is good time to add documentation on our quantization story. 

There have been many questions on the forum, some of which are listed at the bottom. I myself have recently become interested in the topic, but I'm having hard time digging through the forum, github issues, PRs etc. 

It would be great if we could add an end to end quantization usage tutorial or design document to our [developer guide](https://docs.tvm.ai/dev/index.html).

[Current state of quantization effort](https://discuss.tvm.ai/t/current-state-of-quantization-effort/4353)
[Is there a complete quantization tutorial including the use of various quantization algorithms and the addition of operators?](https://discuss.tvm.ai/t/is-there-a-complete-quantization-tutorial-including-the-use-of-various-quantization-algorithms-and-the-addition-of-operators/4819)
[Quantization Configuration Documentation?](https://discuss.tvm.ai/t/quantization-configuration-documentation/3211)
[How to choose different quantization methods?](https://discuss.tvm.ai/t/how-to-choose-different-quantization-methods/4900)
[Int8 tutorial request](https://discuss.tvm.ai/t/int8-tutorial-request/1457)
[ Understanding the quantization passes](https://discuss.tvm.ai/t/quantization-understanding-the-quantization-passes/4573)
[Which operators are quantized in TVM?](https://discuss.tvm.ai/t/quantization-which-operators-are-quantized-in-tvm/3672)
[Does tvm support quantization](https://discuss.tvm.ai/t/does-tvm-support-quantization/1569)

**Comment by vinx13** [comment]
I'm working on cuda quantization tutorial, it will be out soon

**Comment by masahi** [comment]
#4667, #5321, #5362, #5585 added tutorials for quantization.

**Comment by junrushao1994** [comment]
@masahi Hey the last link should be #5595, not #5585

**Comment by masahi** [comment]
@junrushao1994 Thanks, fixed.
