### ISSUE TITLE
How to forward in batches

### ISSUE THREAD

**Issue by jayle19930918** [apache/incubator-tvm#4436]
I have some problems about batch forward.
-In model compile, for example, batch_size=1, input_shape=(1, 3, H, W), then the models for TVM are produced
-When inferring with TVM, the input_shape must be (1, 3, H, W)
-How to batch forward with TVM ?

**Comment by yongwww** [comment]
Free free to discuss this in tvm discuss forum - https://discuss.tvm.ai/

If your batch size is changing during inference, then dynamic batching is needed here. your input shape should be like (?, 3, H, W) or (any, 3, H, W). Dynamisim will be covered in tvm conf next week.

**Comment by tqchen** [comment]
let us move the discussion to the discuss forum
