### ISSUE TITLE
[TEST][FLAKY] test_adaptive_pool FAILED

### ISSUE THREAD

**Issue by apivovarov** [apache/incubator-tvm#4444]
I submitted PR to add new op to TFLite frontend.
All my frontend tests passed.
But one of the test in `topi GPU` keeps failed.
```
topi/tests/python/test_topi_pooling.py::test_adaptive_pool FAILED        [ 49%]
 Mismatch: 33.3%
```
I think this test has nothing to do with my changes
https://ci.tvm.ai/blue/organizations/jenkins/tvm/detail/PR-4440/4/pipeline

https://github.com/apache/incubator-tvm/pull/4440

**Comment by tqchen** [comment]
Thanks for reporting the problem, you might want to retrigger(by sending new commit) and see what happens. If the error happens disappears, we need to mark the error as flaky, and report the error with a [FLAKY][TEST]  prefix like https://github.com/apache/incubator-tvm/issues/4167

If the error occurs persistently, it would be great if you can look into the PR. Note that you can try to reproduce locally using the same docker image setup. It could be possible some changes in your PR interferes with the test, and could indicate a potential problem in the propose change

**Comment by apivovarov** [comment]
3rd attempt was successful https://ci.tvm.ai/blue/organizations/jenkins/tvm/detail/PR-4440/5/pipeline/

**Comment by tqchen** [comment]
cc @kevinthesun please look into the flaky issue

**Comment by tqchen** [comment]
@kevinthesun do you have any updates?

**Comment by tqchen** [comment]
#4836
