### ISSUE TITLE
Windows build error

### ISSUE THREAD

**Issue by chinakook** [apache/incubator-tvm#4460]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2990	'tvm::runtime::InplaceArrayBase': non-class template has already been declared as a class template (compiling source file E:\proj\dev\tvm\src\runtime\vm\vm.cc)	tvm	E:\proj\dev\tvm\include\tvm\runtime\container.h	201

**Comment by wweic** [comment]
https://github.com/apache/incubator-tvm/pull/4455 should fix it.
