### ISSUE TITLE
ci.tvm.ai is down

### ISSUE THREAD

**Issue by apivovarov** [apache/incubator-tvm#4473]
https://ci.tvm.ai/ is down 
@tqchen

**Comment by Vigilans** [comment]
I also cannot reach https://docs.tvm.ai from both proxy server and local network.

**Comment by leeexyz** [comment]
+1

**Comment by tqchen** [comment]
Thanks for reporting Double checked and seems the ci and docs are online atm. Closing for now, please feel free open new threads
