### ISSUE TITLE
Issue with running cpp test

### ISSUE THREAD

**Issue by gittripley** [apache/incubator-tvm#4490]
I followed the instruction in https://docs.tvm.ai/install/from_source.html to install the google test.

However, `make cpptest` failed, because of missing google test header files.

So I have to update the CMakeLists.txt to specify the path. Maybe I missed something.

Here is my changes.
`-find_path(GTEST_INCLUDE_DIR gtest/gtest.h)
+find_path(GTEST_INCLUDE_DIR gtest/gtest.h "/usr/local/include")`

If I run tests/scripts/task_cpp_unittest.sh, I got another error. 
Here is my update.
`-rm -f build/*_test
+rm -f *_test`

`-for test in build/*_test; do
+for test in *_test; do`

**Comment by tqchen** [comment]
Please open a new thread on https://discuss.tvm.ai/ for development and troubleshooting. In your particular case, it depends on the folder you use for the change. Seems you are using the current root folder instead of the build folder.

**Comment by Sophia0806** [comment]
Hi have you resolved this problem? I meet the same one.
