### ISSUE TITLE
Improve ANTLR Language Dependency

### ISSUE THREAD

**Issue by yinghai** [apache/incubator-tvm#4495]
It seems that Relay VM compilation now depends on ANTLR library, which in turn depends on Java runtime. This creates an issue in terms of certain deployment scenario, where we want to compile the model the the fly. Are there any thoughts on relaxing the dependency on Java? 

cc: @hlu1 @ajtulloch

**Comment by wweic** [comment]
We can add similar flag like `-nostdinc++` in gcc for relay, for example `no_prelude`. So we can exclude all the Relay default vended functions in `prelude.py` and `prelude.rly`.

**Comment by tqchen** [comment]
It would be great if we can clarify further, as the ATLNR java package is only used to generate the parser, and the parser itself depends on antlr runtime of the corresponding language(in this case python) but does not depend on the ANTLR java

**Comment by tqchen** [comment]
NOTE that we started with ANTLR python for simplicity, we could in theory move over to ATNLR c++ runtime, which will get around the issue altogether. Would be great if we can get an assessment of feasibility. cc @jroesch

**Comment by tqchen** [comment]
https://github.com/apache/incubator-tvm/pull/5932 is an effort to replace the ANTLR parser

**Comment by tqchen** [comment]
https://github.com/apache/incubator-tvm/pull/6162
