### ISSUE TITLE
[NNVM][RFC] Begin the removal of NNVM Compiler

### ISSUE THREAD

**Issue by jroesch** [apache/incubator-tvm#4496]
After one cycle of deprecation it is now time to start the removal of legacy NNVM code. NNVM's existence in the repo is preventing some refactoring to occur for @icemelon9's new dynamically sized kernel generation work. 

I know we still have some external consumers of NNVM and we should be mindful of removing things in the correct order. If we could start a discussion to collect maintenance requirements before starting to remove NNVM would be great, then we can implement the action plan over the course of the next few weeks.

**Comment by masahi** [comment]
Our rust code uses NNVM for testing and a usage document. They need to be updated.

**Comment by tmoreau89** [comment]
VTA's dependence on NNVM (#4419) has mostly been removed; documentation and CI dockerfiles have to be updated to reflect this.

**Comment by tqchen** [comment]
NOTE, we will only remove the nnvm compiler component, as mxnet's still makes use the core data structures.

**Comment by tqchen** [comment]
https://github.com/apache/incubator-tvm/pull/4535 removes the dependencies in apps, rust

**Comment by tqchen** [comment]
https://github.com/apache/incubator-tvm/pull/4562

**Comment by tqchen** [comment]
https://github.com/apache/incubator-tvm/pull/4571

**Comment by tqchen** [comment]
NNVM compiler is removed from the mainline as of #4571 The core nnvm data structures still will be maintained.
