### ISSUE TITLE
Must ONNX be used to convert the pytorch model?

### ISSUE THREAD

**Issue by huang229** [apache/incubator-tvm#4512]
Thank you very much for the work of the great God. Cross deployment platform, cross depth learning framework, is really a great job. However, I have a question about how I didn't see relay directly loading the pytorch model. Relay has not yet implemented support for the python model. Must onnx be used to convert the pytorchmodel?

**Comment by masahi** [comment]
Yes, we have to go through ONNX at the moment. A direct Pytorch to TVM route is [being discussed](https://discuss.tvm.ai/t/discuss-adding-a-pytorch-frontend/5026?u=masahi) right now.

**Comment by huang229** [comment]
That's really something to look forward to. I hope this day will come soon.
