### ISSUE TITLE
[Relay] VM executor doesn't work with higher order gradient function

### ISSUE THREAD

**Issue by SWu** [apache/incubator-tvm#4519]
I'm using the 0.6.0 release of TVM, and functions generated by `relay.transform.gradient()` in higher order mode break with the following cryptic message when running in a VM executor:

```
tvm._ffi.base.TVMError: Traceback (most recent call last):
  [bt] (8) /usr/tvm/build/libtvm.so(tvm::relay::ExprFunctor<void (tvm::relay::Expr const&)>::VisitExpr(tvm::relay::Expr const&)+0x8a) [0x7f95e58a7d0a]
  [bt] (7) /usr/tvm/build/libtvm.so(tvm::relay::vm::VMFunctionCompiler::VisitExpr_(tvm::relay::LetNode const*)+0x76) [0x7f95e5a27666]
  [bt] (6) /usr/tvm/build/libtvm.so(tvm::relay::ExprFunctor<void (tvm::relay::Expr const&)>::VisitExpr(tvm::relay::Expr const&)+0x8a) [0x7f95e58a7d0a]
  [bt] (5) /usr/tvm/build/libtvm.so(tvm::relay::vm::VMFunctionCompiler::VisitExpr_(tvm::relay::LetNode const*)+0x76) [0x7f95e5a27666]
  [bt] (4) /usr/tvm/build/libtvm.so(tvm::relay::ExprFunctor<void (tvm::relay::Expr const&)>::VisitExpr(tvm::relay::Expr const&)+0x8a) [0x7f95e58a7d0a]
  [bt] (3) /usr/tvm/build/libtvm.so(tvm::relay::vm::VMFunctionCompiler::VisitExpr_(tvm::relay::LetNode const*)+0x26) [0x7f95e5a27616]
  [bt] (2) /usr/tvm/build/libtvm.so(tvm::relay::ExprFunctor<void (tvm::relay::Expr const&)>::VisitExpr(tvm::relay::Expr const&)+0x8a) [0x7f95e58a7d0a]
  [bt] (1) /usr/tvm/build/libtvm.so(tvm::relay::ExprFunctor<void (tvm::relay::Expr const&)>::VisitExprDefault_(tvm::runtime::Object const*)+0x71) [0x7f95e58a61e1]
  [bt] (0) /usr/tvm/build/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x32) [0x7f95e5378a32]
  File "/usr/tvm/include/tvm/relay/expr_functor.h", line 120
TVMError: Do not have a default for relay.RefCreate
```

I'm not sure what exactly is missing in the VM implementation to support this; is there already an issue tracking what is needed for full support of executing Relay functions in the VM? In the meantime, should `relay.transform.gradient` default to `mode="first_order"` to reduce confusion by people trying to run those results in an executor?

**Comment by MarisaKirisame** [comment]
@jroesch 
The VM currently doesnt support References. Meanwhile, you can use mode=first_order or run PE followed by DCE.

**Comment by SWu** [comment]
ParialEvaluate + DeadCodeElimination segfaults for me

I actually have a lot of trouble running gradient functions (even first_order) through the VM, it seems some pass doesn't play nicely with gradient function and DeadCodeElimination always triggers a segfault somewhere in 0.6.0 release. I didn't have this problem before all of the compile optimization passes were added, but I also haven't been able to find a minimal reproducible example. All I know is that DeadCodeElimination at some point during CalcDep probably tries to visit some invalid reference variable. It's only with generated gradient functions that I run into this, regular feed forwards seems to be fine.

**Comment by MarisaKirisame** [comment]
@SWu can you give me a reproducible? I will try to fix it.

**Comment by SWu** [comment]
I figured out the issue I was running into, which I believe is a regression in relay, so I've opened a separate issue detailing it here: https://github.com/apache/incubator-tvm/issues/4534#issue-539162046

After increasing my ulimit, the following works with VM:

```python
mod = relay.Module.from_expr(relay.transform.gradient(loss_func))
seq = relay.transform.Sequential(
    [relay.transform.PartialEvaluate(), relay.transform.DeadCodeElimination()]
)
with relay.build_config(opt_level=3):
    mod = seq(mod)

exec = relay.create_executor(kind="vm", mod=mod)
loss, grads = exec.evaluate()(label, data, *params)
```

It would be useful to add this information to the relay documentation about running higher order gradient functions in the VM
