### ISSUE TITLE
Error, when import otrch and import tvm!

### ISSUE THREAD

**Issue by idealboy** [apache/incubator-tvm#4526]
whether I do like:

import tvm 
import torch

or :

import torch 
import tvm

it seems as there are some confliction.

Environment:

pytorch:1.3.1
cuda:10.0
cudnn:7.5
tvm:0.6.0
python:3.7

thank you very much for this problem!

**Comment by tqchen** [comment]
Thanks for reporting, please open a new thread on https://discuss.tvm.ai/
