### ISSUE TITLE
[WINDOWS] Fix python exception Creation in Windows

### ISSUE THREAD

**Issue by kice** [apache/incubator-tvm#4529]
https://github.com/apache/incubator-tvm/blob/8e3b5d39c388f6767a2e69afff27eac55557567e/python/tvm/autotvm/task/task.py#L192

Looks like the C++ code dose not raise `AttributeError`, it just print the message.

https://github.com/apache/incubator-tvm/blob/8e3b5d39c388f6767a2e69afff27eac55557567e/src/node/reflection.cc#L108-L111

Should we print the message or raise a error?

ref: https://github.com/apache/incubator-tvm/issues/2279

**Comment by tqchen** [comment]
see https://github.com/apache/incubator-tvm/pull/2838 it will automatically translate to the corresponding error in the python side. For further development related discussions, please open a new thread on https://discuss.tvm.ai/:)

**Comment by kice** [comment]
In fact, on windows, it wont.

**Comment by tqchen** [comment]
hmm, interesting finding. This might be a bug that we can fix, could relates to \n \r difference

**Comment by tqchen** [comment]
reopen and label as help wanted, @kice can you dig a bit further?

**Comment by kice** [comment]
Here return C error string

https://github.com/apache/incubator-tvm/blob/10392854076a369bd8dfdf4d4044cad917285345/src/node/reflection.cc#L109-L110

`[23:21:56] C:\src\tvm-win\src\node\reflection.cc:109: AttributeError: Schedule object has no attributed code_hash`

https://github.com/apache/incubator-tvm/blob/10392854076a369bd8dfdf4d4044cad917285345/python/tvm/_ffi/base.py#L192-L198

`_find_error_type` return `None` since after the split, `err_name` is `[23:`, thus `_valid_error_name` return `False`, which make `get_last_ffi_error` think it was not a py error and throw `<class 'tvm._ffi.base.TVMError'>`. 

https://github.com/apache/incubator-tvm/blob/10392854076a369bd8dfdf4d4044cad917285345/python/tvm/_ffi/base.py#L175-L177

I would suggest split the c error string into tokens by `:`, and check every token to see if it is a py error. 

I think we should add a api to query which error was happened, instead of checking the error string.

But base on my analysis, this should also happen on Linux. Wired.

**Comment by tqchen** [comment]
Here is the code that normalizes the error message https://github.com/apache/incubator-tvm/blob/master/src/runtime/c_runtime_api.cc#L203

which will removes the header, but somehow fails your case

**Comment by kice** [comment]
https://ideone.com/LbSfYC

Looks like the `:` in the path cause the issue

**Comment by tqchen** [comment]
@kice would you like to propose a fix ?

**Comment by tqchen** [comment]
I think the main fix could be in the NormalizeError function to fix the windows case if possible
