### ISSUE TITLE
Please allow to use the external dmlc-core: include/dmlc/any.h conflicts with the package dmlc-core

### ISSUE THREAD

**Issue by yurivict** [apache/incubator-tvm#4530]
With ```INSTALL_DEV=ON``` ```tvm``` fails to install:
```
pkg-static: tvm-0.6.0_2 conflicts with dmlc-core-0.3.123 (installs files into the same place).  Problematic file: /usr/local/include/dmlc/any.h
```

```dmlc-core``` exists as a package on several systems: https://repology.org/project/dmlc-core/versions

On FreeBSD the ```tvm``` port uses ```dmlc-core``` as a dependency. Please add a cmake option to use the external ```dmlc-core``` to prevent this conflict.

**Comment by tqchen** [comment]
https://github.com/apache/incubator-tvm/blob/master/CMakeLists.txt#L48 already support this
