### ISSUE TITLE
About Openvino and tvm?

### ISSUE THREAD

**Issue by idealboy** [apache/incubator-tvm#4552]
when I test mobilentv2 on intel x86_64 archetecture, I found, the openvino is 5X faster than tvm, what is the main difference between the two?

the memory?

I found that they all used 4 threads as default.

thank you very much!

**Comment by idealboy** [comment]
why is it always "-mcpuskylake-avx512" in /root/.tvm/tophub/llvm_v0.03.log, whether I workd on Xeon or i7-6700?

Is there any better chapter to read the code in tvm?

thank you very much.

**Comment by tqchen** [comment]
Thanks for asking these questions, please open a new thread on https://discuss.tvm.ai/
