### ISSUE TITLE
Tuning group_conv for x86

### ISSUE THREAD

**Issue by weirdkerneltrick** [apache/incubator-tvm#4556]
Hello! I've tried to tune VarGFaceNet for fast inference via TVM, but got no speed boost. It seems that tuning group_conv for x86 isn't supported at the moment. Is that so? What can be done to tune VarGFaceNet's group convolutions?

**Comment by comaniac** [comment]
Hello, please open a new issue at [https://discuss.tvm.ai/](https://discuss.tvm.ai/) for development and troubleshooting. For your question, TOPI doesn't have a tunable schedule for depthwise conv2d on x86.
