### ISSUE TITLE
Compile error from ir_functor.c & ir_functor_ext.h

### ISSUE THREAD

**Issue by kevinyuan** [apache/incubator-tvm#4625]
tvm/build>make -j10
...
[ 27%] Building CXX object CMakeFiles/tvm.dir/src/pass/lower_custom_datatypes.cc.o
In file included from /home/kevinyuan/dev/tvm/src/pass/ir_functor.cc:22:0:
/home/kevinyuan/dev/tvm/include/tvm/ir_functor_ext.h: In lambda function:
/home/kevinyuan/dev/tvm/include/tvm/ir_functor_ext.h:472:8: error: ‘virtual tvm::Stmt tvm::ir::StmtMutator::VisitStmt(const tvm::Stmt&)’ is protected
   Stmt VisitStmt(const Stmt& stmt) override {
        ^
/home/kevinyuan/dev/tvm/src/pass/ir_functor.cc:76:38: error: within this context
       return StmtMutator::VisitStmt(s);
                                      ^
In file included from /home/kevinyuan/dev/tvm/src/pass/ir_functor.cc:22:0:
/home/kevinyuan/dev/tvm/include/tvm/ir_functor_ext.h: In lambda function:
/home/kevinyuan/dev/tvm/include/tvm/ir_functor_ext.h:130:13: error: ‘R tvm::ir::ExprFunctor<R(const tvm::Expr&, Args ...)>::VisitExpr(const tvm::Expr&, Args ...) [with R = tvm::Expr; Args = {}]’ is inaccessible
   virtual R VisitExpr(const Expr& n, Args... args) {
             ^
/home/kevinyuan/dev/tvm/src/pass/ir_functor.cc:81:38: error: within this context
       return ExprMutator::VisitExpr(e);
                                      ^
[ 27%] Building CXX object CMakeFiles/tvm.dir/src/pass/lower_intrin.cc.o
[ 28%] Building CXX object CMakeFiles/tvm.dir/src/pass/lower_thread_allreduce.cc.o
make[2]: *** [CMakeFiles/tvm.dir/src/pass/ir_functor.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/tvm.dir/all] Error 2
make: *** [all] Error 2

**Comment by tqchen** [comment]
Thanks for reporting, should be fixed by https://github.com/apache/incubator-tvm/pull/4626
