### ISSUE TITLE
[Relay] Bias missing in final layer of Mobilenet?

### ISSUE THREAD

**Issue by gussmith23** [apache/incubator-tvm#4670]
https://github.com/apache/incubator-tvm/blob/3f43bee01ea50d21ef93f618be3540bcf5231cd7/python/tvm/relay/testing/mobilenet.py#L123

Should there be a bias added here? I'm not 100% sure on this.

**Comment by FrozenGene** [comment]
Yes. I think we miss it.

**Comment by tqchen** [comment]
Yes, we should add it, PRs is more than welcomed
