### ISSUE TITLE
tvm Running result error

### ISSUE THREAD

**Issue by vajic** [apache/incubator-tvm#4691]
when i use tvm , I have this problem

**Comment by vajic** [comment]
model：insightface+ resnet+mxnet

1. mat A = mxnet load model ,get output
2.mat B = tvm load model, get output

mat  A  ≠ mat B

**Comment by wweic** [comment]
@vajic Thanks for the report, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

**Comment by tqchen** [comment]
Please open a new trouble shooting thread on https://discuss.tvm.ai/ :)

**Comment by vajic** [comment]
> Please open a new trouble shooting thread on https://discuss.tvm.ai/ :)

ok,thanks
