### ISSUE TITLE
Export builtin_fp16 functions on Windows

### ISSUE THREAD

**Issue by vexilligera** [apache/incubator-tvm#4726]
Hello, I'm working to support tvm ops in MXNet on Windows. The tvm ops are compiled into libtvmop.dll, which requires the builtin_fp16 functions. The linker would throw unresolved external symbols error at this moment. Can we export these two functions on Windows as well? The following code (src/runtime/builtin_fp16.cc) seems to work well for me.

```cpp
#include <builtin_fp16.h>
#include <tvm/runtime/c_runtime_api.h>

extern "C" {

// disable under msvc
#ifndef _MSC_VER

TVM_DLL TVM_WEAK uint16_t __gnu_f2h_ieee(float a) {
  return __truncXfYf2__<float, uint32_t, 23, uint16_t, uint16_t, 10>(a);
}

TVM_DLL TVM_WEAK float __gnu_h2f_ieee(uint16_t a) {
  return __extendXfYf2__<uint16_t, uint16_t, 10, float, uint32_t, 23>(a);
}

#else

TVM_DLL uint16_t __gnu_f2h_ieee(float a) {
  return __truncXfYf2__<float, uint32_t, 23, uint16_t, uint16_t, 10>(a);
}

TVM_DLL float __gnu_h2f_ieee(uint16_t a) {
  return __extendXfYf2__<uint16_t, uint16_t, 10, float, uint32_t, 23>(a);
}

#endif
}
```

**Comment by tqchen** [comment]
Looks good, please feel free to send a PR

**Comment by vexilligera** [comment]
> Looks good, please feel free to send a PR
Hi, I have created a PR.
https://github.com/apache/incubator-tvm/pull/4731
