### ISSUE TITLE
[Build][Bug] Updating CUDA from 10.0 to 10.1 resulted in a broken build even after running make clean

### ISSUE THREAD

**Issue by slyubomirsky** [apache/incubator-tvm#4745]
A bit of a strange case, but I wonder if there is a way to ensure that running `make clean` would result in correct behavior here.

I updated CUDA on my system (Ubuntu 18.04) from 10.0 to 10.1; TVM found the correct NVidia binaries, but after running `make clean` and trying to build TVM again (with `/usr/local/cuda` specified in the `USE_CUDA` configuration option), there was an error building `CMakeFiles/tvm.dir/src/runtime/cuda/cuda_device_api.cc.o` that stated `No rule to make target '/usr/local/cuda-10.0/lib64/libnvrtc.so' needed`. I had deleted `/usr/local/cuda-10.0` and `/usr/local/cuda` pointed to the CUDA 10.1 install directory.

Notably, after I deleted my TVM directory and cloned again, the build succeeded. It seems that there were some remaining references to the old CUDA installation that were not removed when running `make clean`.

**Comment by tqchen** [comment]
It might has something to do with stale cmake cache. So it may not be a bug if you removed your build dir or build succeed in a clean clone.

**Comment by slyubomirsky** [comment]
I see, so probably not a problem on TVM's end. Thanks for the explanation
