### ISSUE TITLE
Can’t pull the docker image `tvmai/demo-gpu`

### ISSUE THREAD

**Issue by llhuii** [apache/incubator-tvm#4755]
When I run the command `tvm/docker/bash.sh tvmai/demo-gpu` or `docker pull tvmai/demo-gpu`, get the error message 
`unauthorized: authentication required`. 
 It's ok for the command `tvm/docker/bash.sh tvmai/demo-cpu`

**Comment by tqchen** [comment]
I confirmed that it works on my machine, and the latest tag exists. Please feel free to open a new trouble shooting thread on https://discuss.tvm.ai/, unfortunately we cannot have enough info to act on this. Another possible way would be to try to set a specific tag on the repo.

**Comment by llhuii** [comment]
Sorry, here are the more details that may help:
I run in ubuntu-16.04 and docker ce 19.03.1 behinds the proxy.
I have tried many times, same error appears, below is the info I build the image manually.
``` sh
$ bash build.sh demo_gpu -it bash
WORKSPACE: /root/llh/tvm/docker/../
CI_DOCKER_EXTRA_PARAMS: -it
COMMAND: bash
CONTAINER_TYPE: demo_gpu
BUILD_TAG: tvm
DOCKER CONTAINER NAME: tvm.demo_gpu

Building container (tvm.demo_gpu)...
Sending build context to Docker daemon  161.3kB
Step 1/8 : FROM tvmai/ci-gpu:v0.54
v0.54: Pulling from tvmai/ci-gpu
35b42117c431: Pulling fs layer 
ad9c569a8d98: Pulling fs layer 
293b44f45162: Pulling fs layer 
0c175077525d: Waiting 
8983152b809d: Waiting 
21e5225fc8b5: Waiting 
eeb42165b239: Waiting 
d0fda2388154: Waiting 
ba199033e468: Waiting 
883065e8abc3: Waiting 
592fa6acc949: Waiting 
7e49e6f7bc45: Waiting 
ee3c4189d4dc: Waiting 
cb280324acef: Waiting 
8cd6e2ffd407: Waiting 
788d2ab395f2: Waiting 
b22b921f093d: Waiting 
b22b921f093d: Downloading [==================>                                ]  136.4MB/372.6MB
9ce1854979d9: Download complete 
378824b12b7d: Download complete 
e57d2a9dd696: Downloading [====================>                              ]  107.9MB/256.9MB
7d55488dad22: Download complete 
7def39b49809: Download complete 
bce766eef98f: Downloading 
390c78f9dca9: Waiting 
19ea5be69cf5: Waiting 
896b68d32e6f: Waiting 
9d3146d73e7a: Waiting 
7a4ba4e68718: Waiting 
bdf385ae7703: Waiting 
b98349b16afd: Waiting 
5628f626030a: Waiting 
2b6b7cdf730b: Waiting 
8c0ea8339751: Waiting 
f6e06227091e: Waiting 
2d8acfcfe93d: Waiting 
ee2ea0c724e4: Waiting 
7d8739564479: Waiting 
72fb7a8d9707: Waiting 
0dff6b36585c: Waiting 
44bb2e848995: Waiting 
305032197312: Waiting 
b9c18d9138f9: Waiting 
24d5994b37dd: Waiting 
4e0ccb22e608: Waiting 
dc66ae2385e5: Waiting 
f72588aa159d: Waiting 
f44d39a238fc: Waiting 
30662209b09f: Waiting 
e4900390300d: Waiting 
7d89d1c83696: Waiting 
0e2deda55d55: Waiting 
e60970214c2a: Waiting 
567a1843a041: Waiting 
26a6bafb6237: Waiting 
138df96f0499: Waiting 
c8f504f548e1: Waiting 
e4671a6ecd90: Waiting 
8ed80814a1ad: Waiting 
24ff96285c21: Waiting 
640528813e4d: Waiting 
unauthorized: authentication required
ERROR: docker build failed.
```

**Comment by llhuii** [comment]
the log of dockerd:
`
Jan 22 12:08:41 ubuntu dockerd[20804]: time="2020-01-22T12:08:41.386491498+08:00" level=debug msg="Applied tar sha256:bd0803b37ff4777a1f42be7c160ff571e2eaf24cc646b3bfd8b201687b7ac1b2 to 0fb01e64e303a580fd027afbe7b665b89dd6cf63f6802d350e2f69a8b5ae10ed, size: 1115"
Jan 22 12:09:04 ubuntu dockerd[20804]: time="2020-01-22T12:09:04.754850355+08:00" level=debug msg="Downloaded 24d5994b37dd to tempfile /var/lib/docker/tmp/GetImageBlob701148629"
Jan 22 12:09:04 ubuntu dockerd[20804]: time="2020-01-22T12:09:04.754913691+08:00" level=debug msg="pulling blob \"sha256:4e0ccb22e608a52831597245aa5ce1f159c7fdbd76e80c945a9d5a7af4068baf\""
Jan 22 12:09:05 ubuntu dockerd[20804]: time="2020-01-22T12:09:05.983270230+08:00" level=debug msg="Downloaded 4e0ccb22e608 to tempfile /var/lib/docker/tmp/GetImageBlob530620058"
Jan 22 12:09:05 ubuntu dockerd[20804]: time="2020-01-22T12:09:05.983859447+08:00" level=debug msg="pulling blob \"sha256:dc66ae2385e57343681f4ef5864d437b7fad20834a199c5d0ba33bac608d9b95\""
Jan 22 12:09:31 ubuntu dockerd[20804]: time="2020-01-22T12:09:31.073925554+08:00" level=debug msg="Downloaded 305032197312 to tempfile /var/lib/docker/tmp/GetImageBlob488157837"
Jan 22 12:09:31 ubuntu dockerd[20804]: time="2020-01-22T12:09:31.074174758+08:00" level=debug msg="pulling blob \"sha256:f72588aa159d8556ddc4e635bad2f05a70e9bcd6d23e4223d38cd9d9b1744777\""
Jan 22 12:09:32 ubuntu dockerd[20804]: time="2020-01-22T12:09:32.381571921+08:00" level=debug msg="Downloaded f72588aa159d to tempfile /var/lib/docker/tmp/GetImageBlob164006620"
Jan 22 12:09:32 ubuntu dockerd[20804]: time="2020-01-22T12:09:32.381616560+08:00" level=debug msg="pulling blob \"sha256:f44d39a238fc35441ac112376ca38306f0861c442e4b3a274c39a6c561ca9cc0\""
Jan 22 12:09:34 ubuntu dockerd[20804]: time="2020-01-22T12:09:34.084027077+08:00" level=debug msg="Downloaded f44d39a238fc to tempfile /var/lib/docker/tmp/GetImageBlob925293195"
Jan 22 12:09:34 ubuntu dockerd[20804]: time="2020-01-22T12:09:34.084577306+08:00" level=debug msg="pulling blob \"sha256:30662209b09f325e9c84d23022675511b12d16e1b0335c4db192db9b4467e5ac\""
Jan 22 12:09:35 ubuntu dockerd[20804]: time="2020-01-22T12:09:35.332294790+08:00" level=debug msg="Downloaded 30662209b09f to tempfile /var/lib/docker/tmp/GetImageBlob065967214"
Jan 22 12:09:35 ubuntu dockerd[20804]: time="2020-01-22T12:09:35.332842871+08:00" level=debug msg="pulling blob \"sha256:e4900390300d38aaba048a103e6c9293db8551236bad227077f68eeee63460df\""
Jan 22 12:11:02 ubuntu dockerd[20804]: time="2020-01-22T12:11:02.415653750+08:00" level=debug msg="Downloaded 5628f626030a to tempfile /var/lib/docker/tmp/GetImageBlob925328016"
Jan 22 12:11:02 ubuntu dockerd[20804]: time="2020-01-22T12:11:02.415780603+08:00" level=debug msg="pulling blob \"sha256:7d89d1c83696ee6ca6f0bc16acf27b0d51c059dd92d7b86f5d38b44672649876\""
Jan 22 12:11:02 ubuntu dockerd[20804]: time="2020-01-22T12:11:02.416859909+08:00" level=debug msg="Applying tar in /var/lib/docker/overlay2/1d56f4d4f2b79ddbdd1409ed3cbfb8da3e3dc04accdab5c83156d9ab8f8ea6b2/diff" storage-driver=overlay2
Jan 22 12:11:04 ubuntu dockerd[20804]: time="2020-01-22T12:11:04.447026041+08:00" level=error msg="Download failed: unauthorized: authentication required"
Jan 22 12:11:04 ubuntu dockerd[20804]: time="2020-01-22T12:11:04.447952358+08:00" level=info msg="Attempting next endpoint for pull after error: unauthorized: authentication required"
Jan 22 12:11:04 ubuntu dockerd[20804]: time="2020-01-22T12:11:04.516909327+08:00" level=debug msg="Cleaning up layer 1d56f4d4f2b79ddbdd1409ed3cbfb8da3e3dc04accdab5c83156d9ab8f8ea6b2: Error 
processing tar file(exit status 1): unexpected EOF"
`

**Comment by llhuii** [comment]
So I switch to build it manually, and I got the error 
```
Cloning into '3rdparty/dmlc-core'...
Submodule path '3rdparty/dmlc-core': checked out '808f485387f9a03f78fa9f1159f387d0d91b7a28'
Cloning into '3rdparty/rang'...
Submodule path '3rdparty/rang': checked out 'cabe04d6d6b05356fa8f9741704924788f0dd762'
fatal: reference is not a tree: 4b13bf668edc7099b38d463e5db94ebc96c80470
The command '/bin/sh -c bash /install/install_tvm_gpu.sh' returned a non-zero code: 128
ERROR: docker build failed.
```
