### ISSUE TITLE
I want get graph_json from tvm.relay.from_tensorflow(), but I donnot install LLVM. What i can do?

### ISSUE THREAD

**Issue by caoqichun** [apache/incubator-tvm#4777]
mod, params = relay.frontend.from_tensorflow(graph_def,   layout=layout,  shape=shape_dict)
target = 'c'
target_host = 'c'
with relay.build_config(opt_level=3):
    graph_json, lib, params = relay.build(mod,  target=target,  target_host=target_host, params=params)

but I get "TVMError:  cannot convert type float32x512 to c type", I only want to get graph_json.

**Comment by tqchen** [comment]
Thanks for reporting the problem, please open a new trouble shooting thread on https://discuss.tvm.ai/
