### ISSUE TITLE
[Relay][FrontEnd][MxNet] incorrect data_min_idx and data_max_idx in _qnn_conv

### ISSUE THREAD

**Issue by GuoliangLiCN** [apache/incubator-tvm#4831]
In the lines 1409-1413 of file python/tvm/relay/frontend/mxnet.py, are there typos when has_sum is False?
>             data_min_idx = -1
>             data_max_idx = -2
>             if has_sum:
>                 data_min_idx = -4
>                 data_max_idx = -3

Should data_min_idx be -2 and data_max_idx be -1 according to lines 467-474 of https://github.com/apache/incubator-mxnet/blob/master/src/operator/subgraph/mkldnn/mkldnn_conv.cc

>   if (param.full_conv_param.mkldnn_param.quantized) {
>     input_names.emplace_back("data_min");
>     input_names.emplace_back("data_max");
>     if (param.full_conv_param.mkldnn_param.with_sum) {
>       input_names.emplace_back("sum_min");
>       input_names.emplace_back("sum_max");
>     }
>   }

**Comment by tqchen** [comment]
cc @kevinthesun @zhiics  can you help check on this ?

**Comment by zhiics** [comment]
yeah, it looks flipped to me as well. @shoubhik can you confirm? Thanks.

**Comment by shoubhik** [comment]
taking a look at it.

**Comment by anijain2305** [comment]
Thanks for finding the bug @GuoliangLiCN 
Yeah, it is flipped. The bug hid because the scale and zero point remained same even if the data_min and data_max were flipped.

**Comment by shoubhik** [comment]
yes, it does needs a flipping. the test case passes because the scale value remains the same. I'll send a PR a little later.

**Comment by tqchen** [comment]
What is the state of this issue? @anijain2305 @shoubhik

**Comment by shoubhik** [comment]
sorry got swamped. I will definitely send a fix on Monday.

**Comment by tqchen** [comment]
#4831
