### ISSUE TITLE
Nvcc fatal : Value ‘sm_75’ is not defined for option ‘gpu-architecture’

### ISSUE THREAD

**Issue by jikechao** [apache/incubator-tvm#4839]
Nvcc fatal : Value ‘sm_75’ is not defined for option ‘gpu-architecture’

**Comment by tqchen** [comment]
Please open a new thread on https://discuss.tvm.ai/ for related questions. In your case, it is due to too low version of your cuda

**Comment by austinmw** [comment]
Hey, looks like the docker hub images are using CUDA 8.0, is there any plan to upgrade?
