### ISSUE TITLE
[REFACTOR] Move python vm runtime into runtime/vm.py

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-tvm#4854]
as https://github.com/apache/incubator-tvm/pull/4818 we are moving to put the core runtime related modules in python to the runtime folder.

We will need to do the same thing for relay related codes, in particular:
- vm.py perhaps need to goto the runtime folder
- Data structures (e.g. ADT) goes to runtime/container.py

**Comment by tqchen** [comment]
cc @zhiics @wweic please see if you are interested

**Comment by zhiics** [comment]
Yeah, I just noticed this a few days ago. Will take a stab on it.

**Comment by zhiics** [comment]
#4855
