### ISSUE TITLE
Error in Build NNPACK @mbp

### ISSUE THREAD

**Issue by KindleHe** [apache/incubator-tvm#4858]
There might be some error in `Build NNPACK` when running in macbook pro.
```shell
# Add PIC option in CFLAG and CXXFLAG to build NNPACK shared library
sed -i "s|gnu99|gnu99 -fPIC|g" CMakeLists.txt
sed -i "s|gnu++11|gnu++11 -fPIC|g" CMakeLists.txt
```
when running `sed .......`, get error :
```shell
sed: 1: "CMakeLists.txt": invalid command code C
```
I found that there is no `gnu99` and `gnu++11` in  `CmakeLists.txt`, 
Could you give some advices, thanks very much!

**Comment by tqchen** [comment]
Please open a new trouble shooting thread on https://discuss.tvm.ai/ note that NNPack is completely optional, and you do not have to build with NNPack enabled
