### ISSUE TITLE
[DOCS] Fix Sphinx Warnings

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-tvm#4908]
While the docs builds just fine in the CI. There are a bunch of warnings being generated. Se the logs in http://ci.tvm.ai:8080/job/tvm/job/master/458/execution/node/304/log/ for example

We do not need to fix all the categories(e.g. the warning about image scale can simply be ignored), but some other warnings may affect the result of rendered document(in the case of bad format of embedded rst).

This thread calls for volunteers to help fix these issues(in most cases by changing the docstring to the correct format or change the rst content). After we collectively fixed most of them, we can start to introduce more strict checks in the CI to fail when new type of warnings occur.

To reproduce locally, run the following command in the docs folder(which does not need to execute the sphinx gallery part)

```bash
TVM_TUTORIAL_EXEC_PATTERN=none make html
```

- [x] Fix one target found for cross-reference warnings
- [x] Fix Unexpected indentation
- [x] Introduce new checks in the CI to check the stderr log of generated by the sphinx

**Comment by comaniac** [comment]
Improving documentation process is definitely important. I can be one of the helpers.

**Comment by cchung100m** [comment]
I am interested in Improving documentation, too. I can be one of the helpers.

**Comment by tqchen** [comment]
Thanks @comaniac @cchung100m How about each of you try to work on one of the error type, and send PRs. We can coorindate in this thread

**Comment by comaniac** [comment]
I could make a PR to fix the indent and format related warnings.

**Comment by cchung100m** [comment]
Hi all,

I would go to check the target-related warnings, for example:

`/tvm/docs/tutorials/autotvm/tune_relay_x86.rst:34: WARNING: 'any' reference target not found: relay.testing.resnett`

**Comment by comaniac** [comment]
FYI: I fixed some of them in the Python doc strings by changing them to `:py:class`.

**Comment by comaniac** [comment]
@cchung100m I supposed you will also cover the Unknown target warning, such as `Unknown target name: src/relay/pass`. Am I understanding correctly?

**Comment by cchung100m** [comment]
@comaniac 

  Thanks for the notification. I would work on it, too.

**Comment by tqchen** [comment]
Thanks to @comaniac @cchung100m 's effort, we have now cleaned up all the WARNINGS and setup a CI check. A remaining step would be to bring the sphinx check to an earlier stage if we find docs error frequently, but that is an efficiency opt which we can do later
