### ISSUE TITLE
how the file of "module.loadfile_clbin" produce and use it with opencl

### ISSUE THREAD

**Issue by feixuedudiao** [apache/incubator-tvm#4911]
i'm using tvm on pc with opencl, i find that it use the file "module.loadfile_cl"  is called int tvm,but how to use the another file of "module.loadfile_clbin". The file of "module.loadfile_clbin" how is genreated, is not known, i find this problem is rarely asked and ansered online.

**Comment by tqchen** [comment]
Please open a new question thread on https://discuss.tvm.ai/
