### ISSUE TITLE
[FRONTEND] Tensorflow Op: Resampler, SparseReshape, Atan2, SparseTensorDenseMatMul

### ISSUE THREAD

**Issue by Robeast** [apache/incubator-tvm#4914]
Hello there,

I'm currently working on an in-house network and I encountered some unsupported Tensorflow operators when importing to TVM:

```
NotImplementedError: The following operators are not implemented: {'Resampler', 'SparseReshape', 'Atan2', 'SparseTensorDenseMatMul'}
```
Is there any plan for implementing these / any of these operators in TVM? Support is highly appreciated! Thank you!

**Comment by DaniDeniz** [comment]
Hello,
I also found when trying to import a model from Tensorflow to TVM that the operator AddV2 is unsupported. 

`NotImplementedError: The following operators are not implemented: {'AddV2'}`

Is there any plan to implement it as well?
Thank you!

**Comment by hypercubestart** [comment]
> Hello,
> I also found when trying to import a model from Tensorflow to TVM that the operator AddV2 is unsupported.
> 
> `NotImplementedError: The following operators are not implemented: {'AddV2'}`
> 
> Is there any plan to implement it as well?
> Thank you!

AddV2 added in #5046

**Comment by Robeast** [comment]
Thank you very much @hypercubestart for taking the initiative!

**Comment by tqchen** [comment]
Close for now as part of the request has been fullfilled by #5104  feel free to open new thread if there is request to support remaining ones

**Comment by Robeast** [comment]
Great! Thanks a lot for your support! Will open a new issue with the remaining operators.
