### ISSUE TITLE
[CI][Docker] ubuntu_install_sgx.sh breaks when trying to download patch file

### ISSUE THREAD

**Issue by leandron** [apache/incubator-tvm#4946]
`ubuntu_install_sgx.sh` points to a patch file on a GitHub gist, which now seems to be removed. This makes the process of rebuilding the Docker images that invoke `ubuntu_install_sgx.sh` to crash.

This is the relevant line:
https://github.com/apache/incubator-tvm/blob/588523ddb6e938637d96745bcce145375307247f/docker/install/ubuntu_install_sgx.sh#L40

The repository name changed as well (probably not very relevant for the issue here), from https://github.com/baidu/rust-sgx-sdk to https://github.com/apache/incubator-teaclave-sgx-sdk.

I'm not very familiar with the Rust SGX SDK, that is why I'm asking: is this patch something we still need, or is it something that needs to be removed from the script?

**Comment by tqchen** [comment]
cc @nhynes

**Comment by nhynes** [comment]
hmm, I'll fix this now. SGX is unfortunately quite deprecated at this time (😬) and I think it reasonable to temporarily remove

**Comment by leandron** [comment]
Thanks for fixing this, but I would suggest another issue to track the need for a proper fix for this?
 
Further, there is a this app[1], that uses `ubuntu_install_sgx.sh`, which in practice still depends on this _GitHub gist_ and thus needs to be fixed as well. How do we not lose this information?

[1] https://github.com/apache/incubator-tvm/tree/cffb4fba03ea582417e2630bd163bca773756af6/apps/sgx
