### ISSUE TITLE
The links not found in Depthwise Convolution tutorial 

### ISSUE THREAD

**Issue by pingsutw** [apache/incubator-tvm#4950]
Some links in this [tutorial](https://tvm.apache.org/2017/08/22/Optimize-Deep-Learning-GPU-Operators-with-TVM-A-Depthwise-Convolution-Example) can not be found.

> Show me the code
> - Declare: https://github.com/dmlc/tvm/blob/master/topi/python/topi/nn/convolution.py
> - Schedule: https://github.com/dmlc/tvm/blob/master/topi/python/topi/cuda/depthwise_conv2d.py
> - Test: https://github.com/dmlc/tvm/blob/master/topi/recipe/conv/depthwise_conv2d_test.py

**Comment by cchung100m** [comment]
Hi @pingsutw 

Thanks for identifying the dead link. I can help to review it if you'd like to send a PR for fixing it.

**Comment by pingsutw** [comment]
Thanks @cchung100m.
sure, I'm going to send a PR

**Comment by pingsutw** [comment]
https://tvm.apache.org/2017/08/22/Optimize-Deep-Learning-GPU-Operators-with-TVM-A-Depthwise-Convolution-Example.html

This doc seems cannot be modified, I can't find the doc's content in this repo.

**Comment by cchung100m** [comment]
Hi @pingsutw 

It seems that we need to do this work in another repo as link below.

https://github.com/tvmai/tvmai.github.io/blob/master/_posts/2017-08-22-Optimize-Deep-Learning-GPU-Operators-with-TVM-A-Depthwise-Convolution-Example.md

**Comment by cchung100m** [comment]
Hi @pingsutw 

Sorry for the misleading.

I think the `tvmai.github.io` was moved to `incubator-tvm-site` repo.

https://github.com/apache/incubator-tvm-site/blob/master/_posts/2017-08-22-Optimize-Deep-Learning-GPU-Operators-with-TVM-A-Depthwise-Convolution-Example.md

cc. @tqchen  

Please correct me if I am wrong.

Thanks for your kindly reply.

**Comment by tqchen** [comment]
yes, please send pr to https://github.com/apache/incubator-tvm-site/

**Comment by pingsutw** [comment]
@cchung100m and @tqchen Thanks for the help.
send pr to https://github.com/apache/incubator-tvm-site/
https://github.com/tvmai/tvmai.github.io/pull/48

**Comment by tqchen** [comment]
The pr has been merged
