### ISSUE TITLE
[RFC] Require C++14 in 0.7 release cycle

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-tvm#4958]
This RFC proposes we move to c++14 in the 0.7 release cycle. The reasons are:

-  The latest LLVM will depend on c++14
-  We  also start to see  needs of a few C++14 features, in particular, ```std::string_view```(it was experimental in c++14) to support some of our container features without introducing a lot boilerplate. 

## Compiler Support Status

gcc5 support c++14, which is enabled in ubuntu 16.04

**Comment by tqchen** [comment]
Discuss thread https://discuss.tvm.ai/t/c-14-requirement-for-0-7/5614

**Comment by leezu** [comment]
An alternative is to require C++17 which gcc7 supports and ships by default in Ubuntu 18.04.
C++17 compiler can be used on as old systems as RHEL6 / CentOS 6 from 2010, via Redhats devtoolset. Thus GLIBC 2.12 from 2010 is the minimum glibc required for C++17.

One concern mentioned in the discussion thread is about edge device coverage. Is there any data on the edge devices and supported toolchains?

Further

> Seems MXNet (which uses TVM as submodule) is still stuck on c++11?

We can propose requiring C++17 or C++14 in MXNet 2.

> However, we depend some 3rd party code, for example dmlc-core. We should be careful whether it could accept -std=c++14 / -std=c++1y and have correct macro (such as __cplusplus >= 201103L, not __cplusplus == 201103L)

dmlc-core could also introduce a C++17 or C++14 requirement.

**Comment by tqchen** [comment]
GCC5 is enough for c++14 support and should be available in most edge devices. For runtime only support, the community recently introduce a pure C runtime which does not depend on any of the c++ features and can be used for these case

**Comment by leezu** [comment]
> GCC5 is enough for c++14 support and should be available in most edge devices.

Is there any overview on the edge devices to be supported and on the latest compiler available?
I'd expect gcc 7 to be available as well, but maybe that assumption is wrong.

> For runtime only support, the community recently introduce a pure C runtime which does not depend on any of the c++ features and can be used for these case

Runtime still requires the glibc version used during compilation. Newer versions of compilers require newer versions of glicb. Thus requiring a newer C++ standard also affects the runtime. Fortunately both gcc5 and gcc7 can run with glibc 2.12 from 2010 and there should be no concerns for runtime.

**Comment by tqchen** [comment]
#5056
