### ISSUE TITLE
[VTA][Chisel] build in Catalina (OSX)

### ISSUE THREAD

**Issue by vegaluisjose** [apache/incubator-tvm#4999]
Hey @liangfu and @tmoreau89 ,

I was trying to figure out today why building the Chisel backend in VTA is failing in Catalina:

* [This](https://github.com/apache/incubator-tvm/blob/master/vta/hardware/chisel/Makefile#L107) fails if XCode is not installed, maybe we should add another option instead of just checking OS?. Making XCode as a dependency might not be a good idea?

* [This](https://github.com/apache/incubator-tvm/blob/master/vta/hardware/chisel/Makefile#L96) is true if `nproc` is not installed. This is bad because the number of threads won't be a number, making the `Verilator` rule fail later on

* The `sbt` [version](https://github.com/apache/incubator-tvm/blob/master/vta/hardware/chisel/project/build.properties#L20) has to be updated to `1.3.2`. The [chisel template](https://github.com/freechipsproject/chisel-template/blob/release/project/build.properties) has updated that version.

* Update the `chisel-iotesters` [version](https://github.com/apache/incubator-tvm/blob/master/vta/hardware/chisel/build.sbt#L65) to `1.2.4`.

I can do the last two, I don't know what are you thoughts in the first two @liangfu ?

**Comment by tqchen** [comment]
It would be great if the related discussions are moved to https://discuss.tvm.ai/ :) Please open a new thread there
