### ISSUE TITLE
[OpenCL] Max Buildin Type Error

### ISSUE THREAD

**Issue by zchuang11** [apache/incubator-tvm#5024]
I tried debug the resnet model with relay, arm64-cpu on rpc app is ok, but opencl with errors:
tvm._ffi.base.TVMError: Traceback (most recent call last):
                                                                                ^~~
   compute[((((int)get_group_id(0)) * 256) + ((int)get_local_id(0)))] = max(min(max((placeholder[((((int)get_group_id(0)) * 256) + ((int)get_local_id(0)))] + placeholder1[((((int)get_group_id(0)) * 256) + ((int)get_local_id(0)))]), (char)0), (char)127), (char)-127);
TVMError: Except caught from RPC call: [19:12:17] D:/Desktop/tvm_gpu_rpc/tvm_gpu_rpc/app/src/main/cpp/src/runtime/library_module.cc:91: Check failed: ret == 0 (-1 vs. 0) : [19:12:17] D:/Desktop/tvm_gpu_rpc/tvm_gpu_rpc/app/src/main/cpp/src/runtime/opencl/opencl_module.cc:234: OpenCL build error for device=0x7bd92eebb8BC-src-code:918:80:{918:80-918:83}: error: call to builtin 'max' is ambiguous due to multiple possible argument type matches
BC-src-code:922:80:{922:80-922:83}: error: call to builtin 'max' is ambiguous due to multiple possible argument type matches
   compute[((((int)get_group_id(0)) * 256) + ((int)get_local_id(0)))] = max(min(max((placeholder[((((int)get_group_id(0)) * 256) + ((int)get_local_id(0)))] + placeholder1[((((int)get_group_id(0)) * 256) + ((int)get_local_id(0)))]), (char)0), (char)127), (char)-127);

**Comment by tqchen** [comment]
Thanks for reporting the problem, the community uses https://discuss.tvm.ai/ to trouble shoot the problem and discussing possible solutions. Please consider open a trouble shooting thread there.

It would also be great if you can try to print out all the entire generated opencl kernel, instead of the single line. The error seems to be related to int8 support but need more details to confirm to see if the problem is tied to a specific opencl backend.

**Comment by zchuang11** [comment]
> Thanks for reporting the problem, the community uses https://discuss.tvm.ai/ to trouble shoot the problem and discussing possible solutions. Please consider open a trouble shooting thread there.
> 
> It would also be great if you can try to print out all the entire generated opencl kernel, instead of the single line. The error seems to be related to int8 support but need more details to confirm to see if the problem is tied to a specific opencl backend.

I have update the [details，](https://discuss.tvm.ai/t/relay-opencl-quantization-error/5963) and new error with [link](https://discuss.tvm.ai/t/relay-opencl-inference-result-error/5965)  please help check the error with bug ? Thanks a lot

**Comment by zchuang11** [comment]
@tqchen I have pushed a unsupported op as [Lambda in keras](https://discuss.tvm.ai/t/lambda-op-for-keras/6408) Thanks  for your replay!
