### ISSUE TITLE
[Runtime] Python String container interface

### ISSUE THREAD

**Issue by wweic** [apache/incubator-tvm#5047]
* Provide python interface to use runtime String container.
* Migrate existing string use cases to the python interface.

**Comment by tqchen** [comment]
cc @zhiics @mbaret @comaniac @jroesch we probably needs to migrate the use of StringImm to String once the string container is introduced

**Comment by wweic** [comment]
@tqchen Could you give me pointers to codes where we can use the python string api to pass strings around? I'll use them as example to drive my  implementation.

**Comment by zhiics** [comment]
@wweic, probably all places we used stringing?

**Comment by tqchen** [comment]
I can see the following steps:

- Introduce the string container
   - We need to think about how to make the String object works like a normal python string(possibly subclass str?, I haven't dig deep)
   - At this stage users can pass and return String but need to explicitly do so
- Add automatic conversion from TVMArgValue to String, when the argument is c string pointer and bytes, automatically convert to a String container(via copy).
- Change the original usage of StringImm to use String instead
- Change automatic object conversion(tvm.convert) https://github.com/apache/incubator-tvm/blob/master/python/tvm/runtime/object_generic.py#L59 to convert python str to String object

**Comment by tqchen** [comment]
https://github.com/apache/incubator-tvm/pull/5426
