### ISSUE TITLE
[RELAY] Update the Python FFI Convention

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-tvm#5068]
So far as part of the refactor, we have updated the python FFI convention as per https://github.com/apache/incubator-tvm/issues/4812

Most of the new folders involved as part of the refactor has been updated. See examples 
- https://github.com/apache/incubator-tvm/tree/master/python/tvm/tir

However, we did not yet update the relay python folder to this new convention. This issue is to track the FFI refactor change on the relay side, in particular

- [x] Introduce _ffi_api for exposing FFI functions
- [x] Consider move relay.Function to relay/function.py to be consistent with the c++ side

cc @jroesch  @icemelon9 @zhiics  @MarisaKirisame @slyubomirsky

**Comment by zhiics** [comment]
#5068 finishes most of it

**Comment by zhiics** [comment]
@tqchen for docs, should we keep the current docs under python/relay expr.rst and base.rst etc? I think we should remove them. But what should we have instead to represent relay namespace in python?

do we want to have relay.rst? if so, I am not sure where we should put it. It seems it wired to put it either under docs/api/python/relay or docs/api/python. Or we want to have ir.rst under docs/api/python/relay to represent relay.rst? It looks not good either.

**Comment by tqchen** [comment]
One way to think about it is that we should expose it as a user facing interface. That means we could have

- relay
- relay.nn
- relay.vision

If we decide to fold the relay into subfolders, then the root relay namespace should be presented under api/python/relay/index.rst

We might need to remove the autofunction(but keep autosumamry, so the summary can link to apo docs) in https://github.com/apache/incubator-tvm/blob/master/docs/langref/relay_op.rst to avoid duplications
