### ISSUE TITLE
[VOTE] VTA HW/SW refactor

### ISSUE THREAD

**Issue by tmoreau89** [apache/incubator-tvm#5102]
It's been great to see growth in the TVM community contributing to VTA in the recent years. VTA is TVM's open source hardware accelerator stack, and consists of multiple components bridging hardware and software design, including RTL sources in Chisel and HLS, driver libraries, simulation libraries, runtime and JIT, TVM and Relay compiler support and passes, TOPI operator libraries for AutoTVM, and python scripts and tutorials.

We had an RFC last week to introduce a proposal to refactor hardware-related sources under `vta/vta-hw` (RTL sources, FPGA scripts, simulator sources, driver code) into a separate apache repository `apache/incubator-tvm-vta` , which will be added to the TVM repo as a submodule under `3rdparty/vta-hw`. 

Link to the discuss thread: [https://discuss.tvm.ai/t/rfc-vta-vta-hw-sw-refactor/5959](https://discuss.tvm.ai/t/rfc-vta-vta-hw-sw-refactor/5959)

The main reasons are:

1. We want to enable broader contributions from organizations who want contribute exclusively to the software or hardware part of the TVM stack.
2. We can increase CI HW testing in the hardware repo ensure robust hardware design (e.g. long cycle accurate simulation, running in parallel with FPGA bitstream compilation tests), while decreasing the load of long simulation CIs in `tvm`.
3. This re-org is can also incite people to upstream their TVM back-end support to their open source hardware by making the separation of TVM compiler support, and hardware sources more clear.

It is worth reiterating:

- The main compiler and runtime for VTA will continue to live in the TVM repo, with the same CI and toolchains setup; this is to ensure that we can evolve the compiler toolchain quickly and build first class compiler support for modern accelerators.
- The hardware part is under the same governance by the Apache TVM community. All of contribution history will be preserved in this new repo; and roles obtained through contributions to tvm will remain valid and open to promotion upon further contributions.
- The contributions to either repos are viewed as contributions to one and the same project. This would also give the community more flexibility to try out new hardware design variants.

This is a formal vote about the refactor proposal. This thread is automatically mirrored in dev@. Everyone in the community is welcomed to participate. Please vote by
explicitly reply to this thread, or reply to the email in dev@

The vote will last for one week and close on March 26th 2020 at noon Pacific Time.

Please vote:
+1 if you agree
+0 neutral
-1 because...

**Comment by tqchen** [comment]
+1 TQ

**Comment by tmoreau89** [comment]
@huajsj @liangfu @pasqoc @vegaluisjose

**Comment by jroesch** [comment]
+1

**Comment by vegaluisjose** [comment]
`+1`

**Comment by kparzysz-quic** [comment]
+1

**Comment by icemelon9** [comment]
+1

**Comment by pasqoc** [comment]
+1

**Comment by kazum** [comment]
+1

**Comment by liangfu** [comment]
+1

**Comment by cchung100m** [comment]
+1

**Comment by ZihengJiang** [comment]
+1

**Comment by mikeseven** [comment]
+1

**Comment by tmoreau89** [comment]
Thanks for everyone that voted closing the vote now.

**Comment by tmoreau89** [comment]
I'm glad to announce the results of the vote on VTA HW/SW refactor.

This vote passes with 11 +1 votes, no 0 votes, and 0 -1 vote.

+1 votes

    Tianqi Chen
    Jared Roesch
    Luis Vega
    Krzysztof Parzyszek
    Haichen Shen
    Pasquale Cocchini
    Kazutaka Morita
    Liangfu Chen
    Neo Chien
    Ziheng Jiang
    "Mike Seven"

0 votes

    No votes

-1 votes

    No votes
