### ISSUE TITLE
[Relay] CompilerAttrs hasn't registered with TVM_REGISTER_NODE_TYPE

### ISSUE THREAD

**Issue by windclarion** [apache/incubator-tvm#5108]
if expr has CompilerAttrs , and use astext() to show it, compiler will report error: relay.attrs.CompilerAttrs is not registered via TVM_REGISTER_NODE_TYPE.  test_pass_partition_graph.py doesn't report the error because it doesn't contain any log.

**Comment by tqchen** [comment]
cc @comaniac
