### ISSUE TITLE
 [BUG][TUTORIAL] Tutorial for quantization need update

### ISSUE THREAD

**Issue by Robeast** [apache/incubator-tvm#5145]
Dear community,
I've noticed that the [stock tutorial for quantization](https://github.com/apache/incubator-tvm/blob/master/tutorials/frontend/deploy_quantized.py) fails if the following call is changed from local scales to global scales:

```
...
mod = quantize(mod, params, data_aware=True) # -> fails with data_aware=False 
...

ValueError: Unknown calibrate mode global
```

The fix is straight forward:

```
-         with relay.quantize.qconfig(calibrate_mode='global', global_scale=8.0):
---
+        with relay.quantize.qconfig(calibrate_mode='global_scale', global_scale=8.0):
```

I would like to kindly ask @vinx13 to update the tutorial. Thank you very much in advance & best regards!

**Comment by tqchen** [comment]
feel free to send a PR to fix this

**Comment by Robeast** [comment]
@tqchen I'm extremely ashamed to say this, but due to company policy I'm not allowed to contribute to anything other than company code bases. Especially shameful since it's only 1 string change... :( I'm really sorry.

**Comment by tqchen** [comment]
no problem, thanks @Robeast for reporting the problem :)

**Comment by Robeast** [comment]
Thank you for your understanding... And thank you very much for @vinx13 for fixing!
