### ISSUE TITLE
ONNX Compatibility

### ISSUE THREAD

**Issue by JishinMaster** [apache/incubator-tvm#5152]
Dear all, 

- What is the ONNX compatibility of the latest incubator-tvm version? (onnx v1.5?)
- Does incubator-tvm supports the classical ML operators described in onnx-ml (svm, tree, linear classifier, etc)?
I also understand that the llvm cpu backend supports more than the opengl or vulkan ones. Where can I find the information as to which backend supports which operations?

Thank you for your support!

**Comment by tqchen** [comment]
Thanks for asking the question, please open a new thread on https://discuss.tvm.ai/
