### ISSUE TITLE
[RELAY] Migrate AlphaEqual StructuralEqual, Relay::StructuralHash to StructuralHash

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-tvm#5159]
https://github.com/apache/incubator-tvm/pull/5154 inroduces StructuralEqual that supersedes AlphaEqual. 

https://github.com/apache/incubator-tvm/pull/5160 Introduces StructuralHash

We should update the relay's AlphaEqual usage to StructuralEqual instead

- [x] Migrate alpha_equal and assert_alpha_equal from python to structural equal
- [x] Migrate AlphaEqual(lhs, rhs) in C++ to StructuralEqual()(lhs, rhs)
- [x] Remove analysis/alpha_equal.cc
- [x] Remove AttrsEqual and related features(as they are also covered by StructuralEqual)

We should also update relay's StructuralHash to the new one
- [x] Migrate relay::StructuralHash to StructuralHash
- [x] Remove relay/ir/hash.cc
- [x] Remove AttrsHash and related features

**Comment by tqchen** [comment]
cc @zhiics @MarisaKirisame @slyubomirsky see if you are interested

**Comment by zhiics** [comment]
I can probably try to squeeze some time to work on some of them over the weekend

**Comment by tqchen** [comment]
Thanks @zhiics I also updated the thread to include related items for StructuralHash

**Comment by zhiics** [comment]
@tqchen I can probably spend some time this afternoon/night to finish the other items. Could you take a look and see if this is a bug?

https://github.com/apache/incubator-tvm/pull/5154#discussion_r399839877

**Comment by tqchen** [comment]
Thanks @zhiics !
