### ISSUE TITLE
TVMError: Check failed: ObjectTypeChecker: :Check(ptr): Expect relay.Expr but get IRModule

### ISSUE THREAD

**Issue by qinxianyuzi** [apache/incubator-tvm#5218]
When I use this code for evaluating, An TVMError has occurred.
`with relay.build_config(opt_level=0):
    intrp = relay.build_module.create_executor('graph', sym, tvm.cpu(0), target)
dtype = 'float32'
func = intrp.evaluate(sym)`

TVMError: Check failed: ObjectTypeChecker: :Check(ptr): Expect relay.Expr but get IRModule

The onnx graph:
`
graph(%input.1 : Float(1, 3, 224, 224),
      %conv1.weight : Float(32, 3, 3, 3),
      %bn1.weight : Float(32),
      %bn1.bias : Float(32),
      %bn1.running_mean : Float(32),
      %bn1.running_var : Float(32),
      %bn1.num_batches_tracked : Long(),
      %layer1.0.conv1.weight : Float(32, 32, 3, 3),
      %layer1.0.bn2.weight : Float(32),
      %layer1.0.bn2.bias : Float(32),
      %layer1.0.bn2.running_mean : Float(32),
      %layer1.0.bn2.running_var : Float(32),
      %layer1.0.bn2.num_batches_tracked : Long(),
      %layer1.0.conv2.weight : Float(32, 32, 3, 3),
      %layer1.0.bn3.weight : Float(32),
      %layer1.0.bn3.bias : Float(32),
      %layer1.0.bn3.running_mean : Float(32),
      %layer1.0.bn3.running_var : Float(32),
      %layer1.0.bn3.num_batches_tracked : Long(),
      %layer1.0.downsample.0.weight : Float(32, 32, 1, 1),
      %layer1.0.downsample.1.weight : Float(32),
      %layer1.0.downsample.1.bias : Float(32),
      %layer1.0.downsample.1.running_mean : Float(32),
      %layer1.0.downsample.1.running_var : Float(32),
      %layer1.0.downsample.1.num_batches_tracked : Long(),
      %layer1.1.conv1.weight : Float(32, 32, 3, 3),
      %layer1.1.bn2.weight : Float(32),
      %layer1.1.bn2.bias : Float(32),
      %layer1.1.bn2.running_mean : Float(32),
      %layer1.1.bn2.running_var : Float(32),
      %layer1.1.bn2.num_batches_tracked : Long(),
      %layer1.1.conv2.weight : Float(32, 32, 3, 3),
      %layer1.1.bn3.weight : Float(32),
      %layer1.1.bn3.bias : Float(32),
      %layer1.1.bn3.running_mean : Float(32),
      %layer1.1.bn3.running_var : Float(32),
      %layer1.1.bn3.num_batches_tracked : Long(),
      %layer2.0.conv1.weight : Float(64, 32, 3, 3),
      %layer2.0.bn2.weight : Float(64),
      %layer2.0.bn2.bias : Float(64),
      %layer2.0.bn2.running_mean : Float(64),
      %layer2.0.bn2.running_var : Float(64),
      %layer2.0.bn2.num_batches_tracked : Long(),
      %layer2.0.conv2.weight : Float(64, 64, 3, 3),
      %layer2.0.bn3.weight : Float(64),
      %layer2.0.bn3.bias : Float(64),
      %layer2.0.bn3.running_mean : Float(64),
      %layer2.0.bn3.running_var : Float(64),
      %layer2.0.bn3.num_batches_tracked : Long(),
      %layer2.0.downsample.0.weight : Float(64, 32, 1, 1),
      %layer2.0.downsample.1.weight : Float(64),
      %layer2.0.downsample.1.bias : Float(64),
      %layer2.0.downsample.1.running_mean : Float(64),
      %layer2.0.downsample.1.running_var : Float(64),
      %layer2.0.downsample.1.num_batches_tracked : Long(),
      %layer2.1.conv1.weight : Float(64, 64, 3, 3),
      %layer2.1.bn2.weight : Float(64),
      %layer2.1.bn2.bias : Float(64),
      %layer2.1.bn2.running_mean : Float(64),
      %layer2.1.bn2.running_var : Float(64),
      %layer2.1.bn2.num_batches_tracked : Long(),
      %layer2.1.conv2.weight : Float(64, 64, 3, 3),
      %layer2.1.bn3.weight : Float(64),
      %layer2.1.bn3.bias : Float(64),
      %layer2.1.bn3.running_mean : Float(64),
      %layer2.1.bn3.running_var : Float(64),
      %layer2.1.bn3.num_batches_tracked : Long(),
      %layer3.0.conv1.weight : Float(128, 64, 3, 3),
      %layer3.0.bn2.weight : Float(128),
      %layer3.0.bn2.bias : Float(128),
      %layer3.0.bn2.running_mean : Float(128),
      %layer3.0.bn2.running_var : Float(128),
      %layer3.0.bn2.num_batches_tracked : Long(),
      %layer3.0.conv2.weight : Float(128, 128, 3, 3),
      %layer3.0.bn3.weight : Float(128),
      %layer3.0.bn3.bias : Float(128),
      %layer3.0.bn3.running_mean : Float(128),
      %layer3.0.bn3.running_var : Float(128),
      %layer3.0.bn3.num_batches_tracked : Long(),
      %layer3.0.downsample.0.weight : Float(128, 64, 1, 1),
      %layer3.0.downsample.1.weight : Float(128),
      %layer3.0.downsample.1.bias : Float(128),
      %layer3.0.downsample.1.running_mean : Float(128),
      %layer3.0.downsample.1.running_var : Float(128),
      %layer3.0.downsample.1.num_batches_tracked : Long(),
      %layer3.1.conv1.weight : Float(128, 128, 3, 3),
      %layer3.1.bn2.weight : Float(128),
      %layer3.1.bn2.bias : Float(128),
      %layer3.1.bn2.running_mean : Float(128),
      %layer3.1.bn2.running_var : Float(128),
      %layer3.1.bn2.num_batches_tracked : Long(),
      %layer3.1.conv2.weight : Float(128, 128, 3, 3),
      %layer3.1.bn3.weight : Float(128),
      %layer3.1.bn3.bias : Float(128),
      %layer3.1.bn3.running_mean : Float(128),
      %layer3.1.bn3.running_var : Float(128),
      %layer3.1.bn3.num_batches_tracked : Long(),
      %layer4.0.conv1.weight : Float(384, 128, 3, 3),
      %layer4.0.bn2.weight : Float(384),
      %layer4.0.bn2.bias : Float(384),
      %layer4.0.bn2.running_mean : Float(384),
      %layer4.0.bn2.running_var : Float(384),
      %layer4.0.bn2.num_batches_tracked : Long(),
      %layer4.0.conv2.weight : Float(384, 384, 3, 3),
      %layer4.0.bn3.weight : Float(384),
      %layer4.0.bn3.bias : Float(384),
      %layer4.0.bn3.running_mean : Float(384),
      %layer4.0.bn3.running_var : Float(384),
      %layer4.0.bn3.num_batches_tracked : Long(),
      %layer4.0.downsample.0.weight : Float(384, 128, 1, 1),
      %layer4.0.downsample.1.weight : Float(384),
      %layer4.0.downsample.1.bias : Float(384),
      %layer4.0.downsample.1.running_mean : Float(384),
      %layer4.0.downsample.1.running_var : Float(384),
      %layer4.0.downsample.1.num_batches_tracked : Long(),
      %layer4.1.conv1.weight : Float(384, 384, 3, 3),
      %layer4.1.bn2.weight : Float(384),
      %layer4.1.bn2.bias : Float(384),
      %layer4.1.bn2.running_mean : Float(384),
      %layer4.1.bn2.running_var : Float(384),
      %layer4.1.bn2.num_batches_tracked : Long(),
      %layer4.1.conv2.weight : Float(384, 384, 3, 3),
      %layer4.1.bn3.weight : Float(384),
      %layer4.1.bn3.bias : Float(384),
      %layer4.1.bn3.running_mean : Float(384),
      %layer4.1.bn3.running_var : Float(384),
      %layer4.1.bn3.num_batches_tracked : Long(),
      %classifier.weight : Float(8, 384),
      %classifier.bias : Float(8)):
  %129 : Float(1, 32, 112, 112) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[2, 2]](%input.1, %conv1.weight), scope: LResNet2/Conv2d[conv1] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py:342:0
  %130 : Float(1, 32, 112, 112) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%129, %bn1.weight, %bn1.bias, %bn1.running_mean, %bn1.running_var), scope: LResNet2/BatchNorm2d[bn1] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1670:0
  %131 : Float(1, 32, 112, 112) = onnx::Relu(%130), scope: LResNet2/ReLU[ReLU1] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:912:0
  %132 : Float(1, 32, 112, 112) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%131, %layer1.0.conv1.weight), scope: LResNet2/Sequential[layer1]/BlockIR2[0]/Conv2d[conv1] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py:342:0
  %133 : Float(1, 32, 112, 112) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%132, %layer1.0.bn2.weight, %layer1.0.bn2.bias, %layer1.0.bn2.running_mean, %layer1.0.bn2.running_var), scope: LResNet2/Sequential[layer1]/BlockIR2[0]/BatchNorm2d[bn2] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1670:0
  %134 : Float(1, 32, 112, 112) = onnx::Relu(%133), scope: LResNet2/Sequential[layer1]/BlockIR2[0]/ReLU[ReLU1] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:912:0
  %135 : Float(1, 32, 56, 56) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[2, 2]](%134, %layer1.0.conv2.weight), scope: LResNet2/Sequential[layer1]/BlockIR2[0]/Conv2d[conv2] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py:342:0
  %136 : Float(1, 32, 56, 56) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%135, %layer1.0.bn3.weight, %layer1.0.bn3.bias, %layer1.0.bn3.running_mean, %layer1.0.bn3.running_var), scope: LResNet2/Sequential[layer1]/BlockIR2[0]/BatchNorm2d[bn3] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1670:0
  %137 : Float(1, 32, 56, 56) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[1, 1], pads=[0, 0, 0, 0], strides=[2, 2]](%131, %layer1.0.downsample.0.weight), scope: LResNet2/Sequential[layer1]/BlockIR2[0]/Sequential[downsample]/Conv2d[0] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py:342:0
  %138 : Float(1, 32, 56, 56) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%137, %layer1.0.downsample.1.weight, %layer1.0.downsample.1.bias, %layer1.0.downsample.1.running_mean, %layer1.0.downsample.1.running_var), scope: LResNet2/Sequential[layer1]/BlockIR2[0]/Sequential[downsample]/BatchNorm2d[1] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1670:0
  %139 : Float(1, 32, 56, 56) = onnx::Add(%136, %138), scope: LResNet2/Sequential[layer1]/BlockIR2[0] # /home/huangry/program/LResNet18E.py:44:0
  %140 : Float(1, 32, 56, 56) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%139, %layer1.1.conv1.weight), scope: LResNet2/Sequential[layer1]/BlockIR2[1]/Conv2d[conv1] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py:342:0
  %141 : Float(1, 32, 56, 56) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%140, %layer1.1.bn2.weight, %layer1.1.bn2.bias, %layer1.1.bn2.running_mean, %layer1.1.bn2.running_var), scope: LResNet2/Sequential[layer1]/BlockIR2[1]/BatchNorm2d[bn2] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1670:0
  %142 : Float(1, 32, 56, 56) = onnx::Relu(%141), scope: LResNet2/Sequential[layer1]/BlockIR2[1]/ReLU[ReLU1] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:912:0
  %143 : Float(1, 32, 56, 56) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%142, %layer1.1.conv2.weight), scope: LResNet2/Sequential[layer1]/BlockIR2[1]/Conv2d[conv2] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py:342:0
  %144 : Float(1, 32, 56, 56) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%143, %layer1.1.bn3.weight, %layer1.1.bn3.bias, %layer1.1.bn3.running_mean, %layer1.1.bn3.running_var), scope: LResNet2/Sequential[layer1]/BlockIR2[1]/BatchNorm2d[bn3] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1670:0
  %145 : Float(1, 32, 56, 56) = onnx::Add(%144, %139), scope: LResNet2/Sequential[layer1]/BlockIR2[1] # /home/huangry/program/LResNet18E.py:44:0
  %146 : Float(1, 64, 56, 56) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%145, %layer2.0.conv1.weight), scope: LResNet2/Sequential[layer2]/BlockIR2[0]/Conv2d[conv1] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py:342:0
  %147 : Float(1, 64, 56, 56) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%146, %layer2.0.bn2.weight, %layer2.0.bn2.bias, %layer2.0.bn2.running_mean, %layer2.0.bn2.running_var), scope: LResNet2/Sequential[layer2]/BlockIR2[0]/BatchNorm2d[bn2] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1670:0
  %148 : Float(1, 64, 56, 56) = onnx::Relu(%147), scope: LResNet2/Sequential[layer2]/BlockIR2[0]/ReLU[ReLU1] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:912:0
  %149 : Float(1, 64, 28, 28) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[2, 2]](%148, %layer2.0.conv2.weight), scope: LResNet2/Sequential[layer2]/BlockIR2[0]/Conv2d[conv2] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py:342:0
  %150 : Float(1, 64, 28, 28) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%149, %layer2.0.bn3.weight, %layer2.0.bn3.bias, %layer2.0.bn3.running_mean, %layer2.0.bn3.running_var), scope: LResNet2/Sequential[layer2]/BlockIR2[0]/BatchNorm2d[bn3] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1670:0
  %151 : Float(1, 64, 28, 28) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[1, 1], pads=[0, 0, 0, 0], strides=[2, 2]](%145, %layer2.0.downsample.0.weight), scope: LResNet2/Sequential[layer2]/BlockIR2[0]/Sequential[downsample]/Conv2d[0] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py:342:0
  %152 : Float(1, 64, 28, 28) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%151, %layer2.0.downsample.1.weight, %layer2.0.downsample.1.bias, %layer2.0.downsample.1.running_mean, %layer2.0.downsample.1.running_var), scope: LResNet2/Sequential[layer2]/BlockIR2[0]/Sequential[downsample]/BatchNorm2d[1] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1670:0
  %153 : Float(1, 64, 28, 28) = onnx::Add(%150, %152), scope: LResNet2/Sequential[layer2]/BlockIR2[0] # /home/huangry/program/LResNet18E.py:44:0
  %154 : Float(1, 64, 28, 28) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%153, %layer2.1.conv1.weight), scope: LResNet2/Sequential[layer2]/BlockIR2[1]/Conv2d[conv1] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py:342:0
  %155 : Float(1, 64, 28, 28) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%154, %layer2.1.bn2.weight, %layer2.1.bn2.bias, %layer2.1.bn2.running_mean, %layer2.1.bn2.running_var), scope: LResNet2/Sequential[layer2]/BlockIR2[1]/BatchNorm2d[bn2] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1670:0
  %156 : Float(1, 64, 28, 28) = onnx::Relu(%155), scope: LResNet2/Sequential[layer2]/BlockIR2[1]/ReLU[ReLU1] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:912:0
  %157 : Float(1, 64, 28, 28) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%156, %layer2.1.conv2.weight), scope: LResNet2/Sequential[layer2]/BlockIR2[1]/Conv2d[conv2] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py:342:0
  %158 : Float(1, 64, 28, 28) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%157, %layer2.1.bn3.weight, %layer2.1.bn3.bias, %layer2.1.bn3.running_mean, %layer2.1.bn3.running_var), scope: LResNet2/Sequential[layer2]/BlockIR2[1]/BatchNorm2d[bn3] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1670:0
  %159 : Float(1, 64, 28, 28) = onnx::Add(%158, %153), scope: LResNet2/Sequential[layer2]/BlockIR2[1] # /home/huangry/program/LResNet18E.py:44:0
  %160 : Float(1, 128, 28, 28) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%159, %layer3.0.conv1.weight), scope: LResNet2/Sequential[layer3]/BlockIR2[0]/Conv2d[conv1] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py:342:0
  %161 : Float(1, 128, 28, 28) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%160, %layer3.0.bn2.weight, %layer3.0.bn2.bias, %layer3.0.bn2.running_mean, %layer3.0.bn2.running_var), scope: LResNet2/Sequential[layer3]/BlockIR2[0]/BatchNorm2d[bn2] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1670:0
  %162 : Float(1, 128, 28, 28) = onnx::Relu(%161), scope: LResNet2/Sequential[layer3]/BlockIR2[0]/ReLU[ReLU1] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:912:0
  %163 : Float(1, 128, 14, 14) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[2, 2]](%162, %layer3.0.conv2.weight), scope: LResNet2/Sequential[layer3]/BlockIR2[0]/Conv2d[conv2] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py:342:0
  %164 : Float(1, 128, 14, 14) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%163, %layer3.0.bn3.weight, %layer3.0.bn3.bias, %layer3.0.bn3.running_mean, %layer3.0.bn3.running_var), scope: LResNet2/Sequential[layer3]/BlockIR2[0]/BatchNorm2d[bn3] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1670:0
  %165 : Float(1, 128, 14, 14) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[1, 1], pads=[0, 0, 0, 0], strides=[2, 2]](%159, %layer3.0.downsample.0.weight), scope: LResNet2/Sequential[layer3]/BlockIR2[0]/Sequential[downsample]/Conv2d[0] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py:342:0
  %166 : Float(1, 128, 14, 14) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%165, %layer3.0.downsample.1.weight, %layer3.0.downsample.1.bias, %layer3.0.downsample.1.running_mean, %layer3.0.downsample.1.running_var), scope: LResNet2/Sequential[layer3]/BlockIR2[0]/Sequential[downsample]/BatchNorm2d[1] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1670:0
  %167 : Float(1, 128, 14, 14) = onnx::Add(%164, %166), scope: LResNet2/Sequential[layer3]/BlockIR2[0] # /home/huangry/program/LResNet18E.py:44:0
  %168 : Float(1, 128, 14, 14) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%167, %layer3.1.conv1.weight), scope: LResNet2/Sequential[layer3]/BlockIR2[1]/Conv2d[conv1] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py:342:0
  %169 : Float(1, 128, 14, 14) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%168, %layer3.1.bn2.weight, %layer3.1.bn2.bias, %layer3.1.bn2.running_mean, %layer3.1.bn2.running_var), scope: LResNet2/Sequential[layer3]/BlockIR2[1]/BatchNorm2d[bn2] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1670:0
  %170 : Float(1, 128, 14, 14) = onnx::Relu(%169), scope: LResNet2/Sequential[layer3]/BlockIR2[1]/ReLU[ReLU1] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:912:0
  %171 : Float(1, 128, 14, 14) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%170, %layer3.1.conv2.weight), scope: LResNet2/Sequential[layer3]/BlockIR2[1]/Conv2d[conv2] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py:342:0
  %172 : Float(1, 128, 14, 14) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%171, %layer3.1.bn3.weight, %layer3.1.bn3.bias, %layer3.1.bn3.running_mean, %layer3.1.bn3.running_var), scope: LResNet2/Sequential[layer3]/BlockIR2[1]/BatchNorm2d[bn3] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1670:0
  %173 : Float(1, 128, 14, 14) = onnx::Add(%172, %167), scope: LResNet2/Sequential[layer3]/BlockIR2[1] # /home/huangry/program/LResNet18E.py:44:0
  %174 : Float(1, 384, 14, 14) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%173, %layer4.0.conv1.weight), scope: LResNet2/Sequential[layer4]/BlockIR2[0]/Conv2d[conv1] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py:342:0
  %175 : Float(1, 384, 14, 14) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%174, %layer4.0.bn2.weight, %layer4.0.bn2.bias, %layer4.0.bn2.running_mean, %layer4.0.bn2.running_var), scope: LResNet2/Sequential[layer4]/BlockIR2[0]/BatchNorm2d[bn2] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1670:0
  %176 : Float(1, 384, 14, 14) = onnx::Relu(%175), scope: LResNet2/Sequential[layer4]/BlockIR2[0]/ReLU[ReLU1] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:912:0
  %177 : Float(1, 384, 7, 7) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[2, 2]](%176, %layer4.0.conv2.weight), scope: LResNet2/Sequential[layer4]/BlockIR2[0]/Conv2d[conv2] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py:342:0
  %178 : Float(1, 384, 7, 7) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%177, %layer4.0.bn3.weight, %layer4.0.bn3.bias, %layer4.0.bn3.running_mean, %layer4.0.bn3.running_var), scope: LResNet2/Sequential[layer4]/BlockIR2[0]/BatchNorm2d[bn3] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1670:0
  %179 : Float(1, 384, 7, 7) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[1, 1], pads=[0, 0, 0, 0], strides=[2, 2]](%173, %layer4.0.downsample.0.weight), scope: LResNet2/Sequential[layer4]/BlockIR2[0]/Sequential[downsample]/Conv2d[0] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py:342:0
  %180 : Float(1, 384, 7, 7) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%179, %layer4.0.downsample.1.weight, %layer4.0.downsample.1.bias, %layer4.0.downsample.1.running_mean, %layer4.0.downsample.1.running_var), scope: LResNet2/Sequential[layer4]/BlockIR2[0]/Sequential[downsample]/BatchNorm2d[1] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1670:0
  %181 : Float(1, 384, 7, 7) = onnx::Add(%178, %180), scope: LResNet2/Sequential[layer4]/BlockIR2[0] # /home/huangry/program/LResNet18E.py:44:0
  %182 : Float(1, 384, 7, 7) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%181, %layer4.1.conv1.weight), scope: LResNet2/Sequential[layer4]/BlockIR2[1]/Conv2d[conv1] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py:342:0
  %183 : Float(1, 384, 7, 7) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%182, %layer4.1.bn2.weight, %layer4.1.bn2.bias, %layer4.1.bn2.running_mean, %layer4.1.bn2.running_var), scope: LResNet2/Sequential[layer4]/BlockIR2[1]/BatchNorm2d[bn2] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1670:0
  %184 : Float(1, 384, 7, 7) = onnx::Relu(%183), scope: LResNet2/Sequential[layer4]/BlockIR2[1]/ReLU[ReLU1] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:912:0
  %185 : Float(1, 384, 7, 7) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%184, %layer4.1.conv2.weight), scope: LResNet2/Sequential[layer4]/BlockIR2[1]/Conv2d[conv2] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py:342:0
  %186 : Float(1, 384, 7, 7) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%185, %layer4.1.bn3.weight, %layer4.1.bn3.bias, %layer4.1.bn3.running_mean, %layer4.1.bn3.running_var), scope: LResNet2/Sequential[layer4]/BlockIR2[1]/BatchNorm2d[bn3] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1670:0
  %187 : Float(1, 384, 7, 7) = onnx::Add(%186, %181), scope: LResNet2/Dropout[drop] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:807:0
  %188 : Tensor = onnx::Pad[mode="constant", pads=[0, 0, 0, 0, 0, 0, 0, 0], value=0](%187), scope: LResNet2/AvgPool2d[avgpool]
  %189 : Float(1, 384, 1, 1) = onnx::AveragePool[kernel_shape=[7, 7], pads=[0, 0, 0, 0], strides=[1, 1]](%188), scope: LResNet2/AvgPool2d[avgpool] # /home/huangry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/pooling.py:554:0
  %190 : Long() = onnx::Constant[value={0}](), scope: LResNet2
  %191 : Tensor = onnx::Shape(%189), scope: LResNet2
  %192 : Long() = onnx::Gather[axis=0](%191, %190), scope: LResNet2 # /home/huangry/program/LResNet18E.py:104:0
  %193 : Long() = onnx::Constant[value={-1}](), scope: LResNet2
  %194 : Tensor = onnx::Unsqueeze[axes=[0]](%192)
  %195 : Tensor = onnx::Unsqueeze[axes=[0]](%193)
  %196 : Tensor = onnx::Concat[axis=0](%194, %195)
  %197 : Float(1, 384) = onnx::Reshape(%189, %196), scope: LResNet2 # /home/huangry/program/LResNet18E.py:104:0
  %198 : Float(1, 8) = onnx::Gemm[alpha=1, beta=1, transB=1](%197, %classifier.weight, %classifier.bias), scope: LResNet2/Linear[classifier] # /home/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1370:0
  return (%198)`

**Comment by tqchen** [comment]
Thanks for reporting the problem, the community uses the discuss forum for such kind of trouble shooting questions, please open a new thread there
