### ISSUE TITLE
gather_nd result seems not correct

### ISSUE THREAD

**Issue by adobay** [apache/incubator-tvm#5229]
with data shape [6, 4, 3] , indices shape [6, 2], gather_nd will throw error.
with data shape [1, 4, 1],  indices shape [3, 2], result shape is [2].

**Comment by tqchen** [comment]
cc @kazum @icemelon9

**Comment by icemelon9** [comment]
`gather_nd` in relay follows the [mxnet semantics](https://mxnet.apache.org/api/python/docs/api/ndarray/op/index.html#mxnet.ndarray.op.gather_nd) where each column indicates the indices in the data.

**Comment by tqchen** [comment]
Close for now then, please feel free to open new thread on https://discuss.tvm.ai/ for followup discussions :)
