### ISSUE TITLE
[FRONTEND] tensorflow GatherNd function error

### ISSUE THREAD

**Issue by adobay** [apache/incubator-tvm#5248]
in relay/frontend/tensorflow.py, GatherNd's converter function is relay's gather_nd, but gather_nd in relay follows the mxnet semantics where each column indicates the indices in the data, which is completely different to tensorflow.

**Comment by tqchen** [comment]
cc @kazum @srkreddy1238 @icemelon9  Would be great if we can look into this. 

Also perhaps we should have a discussion in the discuss forum about existing API conventions for gather nd so that we have a clear picture about what they are and how can we convert from one another

**Comment by icemelon9** [comment]
Yes, let's open a discussion in the forum about this. 
https://discuss.tvm.ai/t/gather-nd-semantics/6243
