### ISSUE TITLE
[onnx]   [llvm ]

### ISSUE THREAD

**Issue by fcqfcq** [apache/incubator-tvm#5256]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

For feature proposals, list clear, small actionable items so we can track the progress of the change.

**Comment by fcqfcq** [comment]
WARNING:root:Failed to download tophub package for llvm: <urlopen error [Errno 110] Connection timed out>
download failed due to URLError(TimeoutError(110, 'Connection timed out'),), retrying, 2 attempts left
download failed due to URLError(TimeoutError(110, 'Connection timed out'),), retrying, 1 attempt left
WARNING:root:Failed to download tophub package for llvm: <urlopen error [Errno 110] Connection timed out>
WARNING:autotvm:Cannot find config for target=llvm, workload=('dense_nopack.x86', ('TENSOR', (8, 512), 'float32'), ('TENSOR', (512, 512), 'float32'), None, 'float32'). A fallback configuration is used, which may bring great performance regression.

**Comment by tqchen** [comment]
Please open a new thread on https://discuss.tvm.ai/
