### ISSUE TITLE
[Relay] Support for GroupNorm

### ISSUE THREAD

**Issue by NarendraPatwardhan** [apache/incubator-tvm#5278]
Many modern models utilize GroupNorm, there is support for LayerNorm and InstanceNorm under tvm/relay/op/nn. It is especially helpful for training with low number of samples and more efficient than instance norm in terms of parameters. It would be valuable addition to add it to core set of operators as libraries like pytorch or mxnet already support it.

**Comment by masahi** [comment]
#5358
