### ISSUE TITLE
[TEST][FLAKY] Sphinx pre-check build error

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-tvm#5285]
We have a couple CI error in the sphinx check https://ci.tvm.ai/blue/rest/organizations/jenkins/pipelines/tvm/branches/master/runs/733/nodes/151/log/?start=0 on an CI node. would be great if we can look into what is going on.

I temporarily bring that node offline.

**Comment by tqchen** [comment]
cc @zhiics

**Comment by zhiics** [comment]
I rebooted the machine. Not sure if this error will remain.

**Comment by zhiics** [comment]
The same error now also happens on other CI nodes as well.

**Comment by tqchen** [comment]
I see, i will look into it

**Comment by tqchen** [comment]
Should be fixed by https://github.com/apache/incubator-tvm/pull/5292 Thanks @zhiics for looking into it

**Comment by tqchen** [comment]
closing for now. btw @zhiics perhaps we need to look into cuda driver of the rebooted machine, which reports cuda not found
