### ISSUE TITLE
[CRT][FLAKY] Flaky failures on 32bit platforms

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-tvm#5298]
We have some flaky tests for the CRT under the 32bit platforms(even after https://github.com/apache/incubator-tvm/pull/5293) , see example log here:

https://ci.tvm.ai/blue/rest/organizations/jenkins/pipelines/tvm/branches/PR-5282/runs/9/nodes/152/log/?start=0

https://github.com/apache/incubator-tvm/pull/5297 temporary disabled the tests. It would be great if we look into the potential cause of the problem. One interesting thing is that it only fails in i386, which suggests that it could be a 32bit 64 bit issue.

cc @liangfu @mehrdadhe @tmoreau89

**Comment by tqchen** [comment]
cc @liangfu @areusch can you comment on the status? given the recent significant refactor of CRT, shall we conclude that the flaky error no longer exist?

**Comment by liangfu** [comment]
https://github.com/apache/incubator-tvm/blob/44ff1f3b5ed0751fee39537a0e6e3870a74c930b/tests/scripts/task_python_integration.sh#L39

This wouldn't be successful unless https://github.com/apache/incubator-tvm/pull/6145 is merged, and let's see whether the PR works on i386.

**Comment by tqchen** [comment]
@liangfu @areusch would be great to get your comment about the status of this issue

**Comment by areusch** [comment]
thoretically I think this should be fixed now. at least, the test is enabled on i386 and CPU regressions, so I think we should close this issue and reopen if we see it again.

**Comment by tqchen** [comment]
Thanks @areusch

**Comment by areusch** [comment]
Possibly another instance spotted in #6395, but can't view the old jenkins logs to check:

https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-6395/26/pipeline/
