### ISSUE TITLE
[Jenkinsfile] Should we include libvta_tsim.so at the top level

### ISSUE THREAD

**Issue by zhiics** [apache/incubator-tvm#5351]
@tqchen @tmoreau89 

Should we include libvta_tsim.so and libvta_fsim.so here?

https://github.com/apache/incubator-tvm/blob/84d1eec39a10c559cb659d3f411cacce08cfdaff/Jenkinsfile#L56-L57

it looks we should set them on in the CPU script, but not in the GPU script (we probably don't need to)
https://github.com/apache/incubator-tvm/blob/84d1eec39a10c559cb659d3f411cacce08cfdaff/tests/scripts/task_config_build_cpu.sh#L39-L40

However, we will use them here when we build GPU
https://github.com/apache/incubator-tvm/blob/84d1eec39a10c559cb659d3f411cacce08cfdaff/Jenkinsfile#L148

CC @trevor-m

**Comment by tqchen** [comment]
we still need them for building vta tutorials, which is in the last docs stage

**Comment by zhiics** [comment]
I see. Thanks. Then should we add `set(USE_VTA_TSIM/FSIM, ON)` in the build_gpu.sh? We see errors when packing the lib

**Comment by tqchen** [comment]
I agree, please send a patch :)

**Comment by zhiics** [comment]
close by #5352
