### ISSUE TITLE
Remove Interference of TensorCore Strategy to OpenCL/Metal

### ISSUE THREAD

**Issue by JishinMaster** [apache/incubator-tvm#5370]
Dear all,

Is it possible to use the OpenCL/Vulkan/RoCM backends without enabling the CUDA one?
I want to use TVM on AMD and Intel GPU platforms (i.e without Nvidia).
It seems that CUDA also enables everything related to GPU (for instance the schedule).
Enabling only opencl with the latest tvm source gives me "TVMError: Check failed: allow_missing: Device API gpu is not enabled" at the following line :

with relay.build_config(opt_level=opt_level):
    graph, lib, params = relay.build(mod, target= "opencl", target_host="llvm", params=params)

I have looked in target.cc and schedule.cc. There are not dedicated schedule for vulkan and opencl, and parts of the rocm one seems to link to cuda. 
With USE_CUDA=1 in the build options on my computer with an Nvidia GPU, the previous code works.

Thank you in advance for your help!

**Comment by tqchen** [comment]
cc @icemelon9 @jwfromm @Shawn-Inspur @Hzfengsy

**Comment by tqchen** [comment]
This is related to the strategy introduced by the tensorcore PR

**Comment by jwfromm** [comment]
It looks like this is probably happening because we forgot to check that the current target is `cuda` before calling `nvcc.have_tensorcore` in the `dense` strategy function. PR #5376 should fix this. Can you give the change a try and see if it solves your problem?
