### ISSUE TITLE
[REFACTOR][TIR] Migrate HoistIfThenElse to the unified pass manager

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-tvm#5373]
See background https://github.com/apache/incubator-tvm/pull/5364

cc @kevinthesun can you work on this item?

**Comment by kevinthesun** [comment]
@tqchen Sorry I'm quite busy these days. Will work on it when I get time.

**Comment by tqchen** [comment]
Thanks @kevinthesun , it should take about a few hours

**Comment by tqchen** [comment]
ping @kevinthesun

**Comment by tqchen** [comment]
ping @kevinthesun
