### ISSUE TITLE
[RUNTIME][VULKAN] vkBuffer released before memory copy command send to GPU

### ISSUE THREAD

**Issue by samwyi** [apache/incubator-tvm#5388]
**Problem**: When the Vulkan runtime uses deferred kernels to do a GPU -> GPU copy, the source vkBuffer is released before the copy command is put into command buffer. That can cause seg fault in vulkan driver.

**Details**: 
The problem happens in:
`args = [ [nd.array(x, ctx=ctx) for x in args] (measure_methods.py: 482).`
This line of code rpc calls CopyDataFromTo() (vulkan.cc: 200) to do a GPU -> GPU copy on the remote device. CopyDataFromTo() uses deferred mode to schedule the copy commands. So the copy commands are not really put into vulkan cmd buffer by the end of the rpc call.  

Then the source ndarray is destructed because 'args' now points to the dest ndarray. The destructor rpc calls FreeDataSpace() to destroy the source vkBuffer. This caused the vkDestroyBuffer command being scheduled before the vkCmdCopyBuffer command. 

In the next line in measure_methods.py,  ctx.sync() rpc calls Synchronize(), when the copy commands are actually put into the cmd buffer. But by now, the source buffer is already an invalid. This caused the driver to seg fault while performing the copy.

**Reproduce**:
Run attached debug_tune.py, or any auto-tuning script using Vulkan and rpc.

**Possible Solution**:
Add a counter in VulkanBuffer struct. +1 upon a copy request, and -1 after the copy command actually put into cmd buffer. Destroy the buffer only when the counter is 0.

[debug_tune.zip](https://github.com/apache/incubator-tvm/files/4507069/debug_tune.zip)

**Comment by tqchen** [comment]
Thanks @samwyi for reporting the problem. Perhaps an easier fix now would be call into Synchronize directly in when FreeDataSpace is called. This is also the default behavior in CUDA. Given that most of the space won't be freed during computation, this might be a fine fix.

@samwyi do you mind to send a PR?

**Comment by tqchen** [comment]
cc @ajtulloch @antinucleon

**Comment by samwyi** [comment]
> Thanks @samwyi for reporting the problem. Perhaps an easier fix now would be call into Synchronize directly in when FreeDataSpace is called. This is also the default behavior in CUDA. Given that most of the space won't be freed during computation, this might be a fine fix.
> 
> @samwyi do you mind to send a PR?

I'd be glad to provide a fix, but seems CUDA didn't call Synchronize in FreeDataSpace. Seems CUDA doesn't use deferred kernels, so it should be fine.

**Comment by tqchen** [comment]
CUDA's cudaFree implicitly syncs the default stream

**Comment by tqchen** [comment]
ping @samwyi  :)

**Comment by samwyi** [comment]
> ping @samwyi :)

I'll send out a PR soon.

**Comment by samwyi** [comment]
> > ping @samwyi :)
> 
> I'll send out a PR soon.

Do we

**Comment by samwyi** [comment]
> ping @samwyi :)

I'll send out a PR soon. Just to confirm the procedure: (1) create own fork, (2) change in the main branch of my own fork, (3) push to remote and request pull, correct?

**Comment by tqchen** [comment]
yes, that is the correct procedure

**Comment by samwyi** [comment]
PR: https://github.com/apache/incubator-tvm/pull/5418

**Comment by tqchen** [comment]
closed thanks to @samwyi !
