### ISSUE TITLE
lib.export_library('path/to/deploy_lib.dll') on windows

### ISSUE THREAD

**Issue by hudmgy** [apache/incubator-tvm#5402]
when I ran  "lib.export_library('path/to/deploy_lib.dll')" on windows, I failed 

cl: Command line warning D9024 :unrecognized source file type“C:\Users\afx-\AppData\Local\Temp\tmprr0gougm\lib0.o”，object file assumed
cl: Command line warning D9027 :source file“C:\Users\afx-\AppData\Local\Temp\tmprr0gougm\lib0.o”ignored
dllmain.cc
C:\Users\afx-\AppData\Local\Temp\tmpfj_x3sy6\dllmain.cc(1): warning C4067: Unexpected token after preprocessor instruction - newline expected
C:\Users\afx-\AppData\Local\Temp\tmpfj_x3sy6\dllmain.cc(1): fatal error C1034: windows.h:

**Comment by tqchen** [comment]
Please open a new troubleshooting thread on https://discuss.tvm.ai/
