### ISSUE TITLE
Tflite testsuite issue with tflite 2.1.0 (test_elemwise(partial(add, "RELU6"))) 

### ISSUE THREAD

**Issue by u99127** [apache/incubator-tvm#5406]
As documented in #5392 using the packages for tflite and tensorflow 2.1.0 the test as in the subject line segfaults. It has now been skipped in the testsuite but this needs to be fixed.

**Comment by u99127** [comment]
This is the failure in the build and test run. 

`
>         raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
E         tensorflow.lite.python.convert.ConverterError: See console for info.
E         2020-04-22 14:25:04.973317: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object 
file: No such file or directory; LD_LIBRARY_PATH:
E         2020-04-22 14:25:04.973380: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open 
shared object file: No such file or directory; LD_LIBRARY_PATH:
E         2020-04-22 14:25:04.973388: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
E         2020-04-22 14:25:05.600205: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 2 operators, 4 arrays (0 quantized)
E         2020-04-22 14:25:05.600303: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 2 operators, 4 arrays (0 quantized)
E         Fatal Python error: Segmentation fault
E         
E         Current thread 0x00007f4ad17cc700 (most recent call first):
`

E           File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 56 in execute
E           File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250 in _run_main
E           File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299 in run
E           File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40 in run
E           File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 93 in main
E           File "/usr/local/bin/toco_from_protos", line 8 in <module>
E         Segmentation fault (core dumped)

**Comment by tqchen** [comment]
@u99127 @anijain2305 can you comment on the state of the issue?

**Comment by tqchen** [comment]
ping, will consider this issue closed due to inactive status
