### ISSUE TITLE
import vta: Cannot find config in /3rdparty/vta-hw/config/vta_config.json

### ISSUE THREAD

**Issue by dreamqin68** [apache/incubator-tvm#5440]
I installed VTA according to the VTA Simulator Installation guide. Then I set the environment. But when I imported vta, there was a bug.

```
Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/home/dream/tvm/vta/python/vta/__init__.py", line 27, in <module>
    from .bitstream import get_bitstream_path, download_bitstream

  File "/home/dream/tvm/vta/python/vta/bitstream.py", line 24, in <module>
    from .environment import get_env

  File "/home/dream/tvm/vta/python/vta/environment.py", line 325, in <module>
    Environment.current = _init_env()

  File "/home/dream/tvm/vta/python/vta/environment.py", line 321, in _init_env
    raise RuntimeError("Cannot find config in %s" % str(config_path))

RuntimeError: Cannot find config in /3rdparty/vta-hw/config/vta_config.json
```

In fact, I found `vta_config.json` in `/3rdparty/vta-hw/config/`. 

I don't know how to fix it.

**Comment by lixiaoquan** [comment]
vta-hw is a submodule, you may need 'git submodule init' and 'git submodule update'

**Comment by tqchen** [comment]
Please try the suggested step, pleas also feel free to followup on the https://discuss.tvm.ai/

**Comment by dreamqin68** [comment]
> vta-hw is a submodule, you may need 'git submodule init' and 'git submodule update'

Thank you for your help. 

Do you mean that Windows users who use Github tools need to 'git submodule init' and 'git submodule update'? In fact, I have already used `--recursive` in Linux environment.  I followed the installation guide. But there was still wrong.

**Comment by tqchen** [comment]
do a `git submodule update --init`

**Comment by dreamqin68** [comment]
> do a `git submodule update --init`

Thank you for your help.

I did `git submodule update --init`, then I rebuilt, `cmake ..`:
```
-- VTA build with VTA_HW_PATH=/3rdparty/vta-hw
/usr/bin/python: can't open file '/3rdparty/vta-hw/config/vta_config.py': [Errno 2] No such file or directory
-- Build VTA runtime with target:
/usr/bin/python: can't open file '/3rdparty/vta-hw/config/vta_config.py': [Errno 2] No such file or directory
```
```
CMake Error at cmake/modules/VTA.cmake:58 (add_library):
  Cannot find source file:

    /3rdparty/vta-hw/src/sim/sim_driver.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  CMakeLists.txt:283 (include)


CMake Error: CMake can not determine linker language for target: vta_fsim
CMake Error: Cannot determine link language for target "vta_fsim".
```
I don't know what happened.

**Comment by dreamqin68** [comment]
> do a `git submodule update --init`

Thank you very much! It works.
