### ISSUE TITLE
How to implement a demo of TVM C++ object-detection?

### ISSUE THREAD

**Issue by HK017** [apache/incubator-tvm#5443]
hi all developer， how to transform tvm::run_time::NDArray data to c++ data so that I can process the data better，for example，
For yolov3 (Darknet version) TVM C + + code, how to handle the output of get_output?

If you see the problem, please help me to solve it, I will be very grateful！！！
Thanks again

**Comment by FrozenGene** [comment]
Suggest asking this question on the discuss forum: https://discuss.tvm.ai/

**Comment by HK017** [comment]
> Suggest asking this question on the discuss forum: https://discuss.tvm.ai/

Because no one replied to me, I came here for help on the discuss forum: https://discuss.tvm.ai/
