### ISSUE TITLE
Windows OSError: "exception: access violation reading 0x0000000000000000"

### ISSUE THREAD

**Issue by schliffen** [apache/incubator-tvm#5449]
We are trying to convert a mxnet model into tvm (v7) in windows using the following part of code:
loading model (works fine):
 `      mx_sym, args, auxs = mx.model.load_checkpoint(root + ap.mdlrt, 0)`
       ` mod, params = relay.frontend.from_mxnet(mx_sym, shape_dict, dtype, arg_params=args, aux_params=auxs)
`
build tvm model (fails):

`    with relay.build_config(opt_level=3):`
        `graph, mod, params = relay.build(mod, target, params=params)
`
in this relay.build we faced with the following error (full log):
`[08:31:15] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:209: Loading symbol saved by previous version v1.2.0. Attempting to upgrade...`
`[08:31:15] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:217: Symbol successfully upgraded!`
`Traceback (most recent call last):
  File "E:/TVM/faceTransfer/mxnet2Tvm.py", line 96, in save_tvm_model`
`    graph, mod, params = relay.build(mod, target, params=params)`
`  File "C:\Python\Python37\site-packages\tvm-0.7.dev1-py3.7-win-amd64.egg\tvm\relay\build_module.py", line 251, in build`
`    graph_json, mod, params = bld_mod.build(mod, target, target_host, params)`
`  File "C:\Python\Python37\site-packages\tvm-0.7.dev1-py3.7-win-amd64.egg\tvm\relay\build_module.py", line 120, in build`
`    self._build(mod, target, target_host)`
`  File "C:\Python\Python37\site-packages\tvm-0.7.dev1-py3.7-win-amd64.egg\tvm\_ffi\_ctypes\packed_func.py", line 215, in __call__`
`    ctypes.byref(ret_val), ctypes.byref(ret_tcode)) != 0:`
`OSError: exception: access violation reading 0x0000000000000000`

system details: Windows 10, Visual Studio-2015, c++14, cuda 10.1, llvm 6.0.1, tvm v7

**Comment by tqchen** [comment]
Please open a new trouble shooting thread on https://discuss.tvm.ai/
