### ISSUE TITLE
centernet_dlav0 pytorch to tvm is wrong,who can help me?

### ISSUE THREAD

**Issue by zoufangyu1987** [apache/incubator-tvm#5462]
File "/data_1/TVM/TVM/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 219, in __call__
    raise get_last_ffi_error()

tvm._ffi.base.TVMError: Traceback (most recent call last):
  [bt] (8) /data_1/TVM/TVM/tvm/build/libtvm.so(TVMFuncCall+0x65) [0x7f95b6864615]
  [bt] (7) /data_1/TVM/TVM/tvm/build/libtvm.so(+0xa0dfb4) [0x7f95b5f25fb4]
  [bt] (6) /data_1/TVM/TVM/tvm/build/libtvm.so(tvm::IRModule::FromExpr(tvm::RelayExpr const&, tvm::Map<tvm::GlobalVar, tvm::BaseFunc, void, void> const&, tvm::Map<tvm::GlobalTypeVar, tvm::TypeData, void, void> const&)+0x26e) [0x7f95b5f21d9e]
  [bt] (5) /data_1/TVM/TVM/tvm/build/libtvm.so(tvm::IRModuleNode::Add(tvm::GlobalVar const&, tvm::BaseFunc const&, bool)+0x3cf) [0x7f95b5f2191f]
  [bt] (4) /data_1/TVM/TVM/tvm/build/libtvm.so(tvm::RunTypeCheck(tvm::IRModule const&, tvm::GlobalVar const&, tvm::relay::Function)+0x25e) [0x7f95b5f1de5e]
  [bt] (3) /data_1/TVM/TVM/tvm/build/libtvm.so(tvm::relay::InferType(tvm::relay::Function const&, tvm::IRModule const&, tvm::GlobalVar const&)+0x1dd) [0x7f95b661c4fd]
  [bt] (2) /data_1/TVM/TVM/tvm/build/libtvm.so(tvm::relay::TypeInferencer::Infer(tvm::RelayExpr)+0x71) [0x7f95b661bd31]
  [bt] (1) /data_1/TVM/TVM/tvm/build/libtvm.so(tvm::ErrorReporter::RenderErrors(tvm::IRModule const&, bool)+0x2292) [0x7f95b5f5ea22]
  [bt] (0) /data_1/TVM/TVM/tvm/build/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x7c) [0x7f95b5ed859c]
  File "/data_1/TVM/TVM/tvm/src/ir/error.cc", line 133
TVMError: 
Error(s) have occurred. The program has been annotated with them:

In `main`: 
v0.0.4

%181 = nn.conv2d_transpose(%180, %v1479, channels=1, kernel_size=[4, 4], strides=[2, 2], padding=[1, 1, 1, 1], groups=256) in particular dimension 1 conflicts 0 does not match 1; unable to unify: `Tensor[(256, 0, 4, 4), float32]` and `Tensor[(256, 1, 4, 4), float32]`; ;
  %182 = (%175, %181);
  %183 = concatenate(%182, axis=1);
  nn.conv2d(%183, %v1505, padding=[1, 1, 1, 1], channels=256, kernel_size=[3, 3]) in particular dimension 1 conflicts 257 does not match 512; unable to unify: `Tensor[(256, 257, 3, 3), float32]` and `Tensor[(256, 512, 3, 3), float32]`; 
}

**Comment by tqchen** [comment]
Please open a new troubleshooting thread on https://discuss.tvm.ai/

**Comment by austinmw** [comment]
Ran into same issue
