### ISSUE TITLE
[REFACTOR] std::string -> String Migration in IR nodes

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-tvm#5490]
This is an issue to track the progress of std::string -> String migration in IR Nodes.

- [x] Merge initial example https://github.com/apache/incubator-tvm/pull/5438
- [x] Convert relay nodes
- [x] Convert base types
- [x] Convert tir nodes.

**Comment by tqchen** [comment]
cc @icemelon9 @jroesch @zhiics please chime in if you would like to take a stab

**Comment by tqchen** [comment]
NOTE, as in the intiial example, we will need to update the converter(via _update_from_std_str) to keep backward compatibility of the nodes

**Comment by ANSHUMAN87** [comment]
I like to contribute for this movement. May be we can share the workload, if @zhiics  already working on it. Please let me know.Thanks!

**Comment by zhiics** [comment]
@ANSHUMAN87 Welcome to contribute. I've busy with other things recently. Thanks.
