### ISSUE TITLE
Can not find stride and padding information in graph after relay.build function

### ISSUE THREAD

**Issue by wangzhao123456** [apache/incubator-tvm#5543]
Hello, I am a beginner of TVM and I run the tutorials on official website to learn TVM. 
I noticed that before  relay.build function there has stride and padding informations stored in the model. After relay.build function, conducting some kinds of  graph-level optimizations, there has no stride and padding information in the optimized graph. I wonder where could I find the stride and padding informations after relay.build function? 
Thanks a lot.

**Comment by tqchen** [comment]
Please open a new thread on https://discuss.tvm.ai/
