### ISSUE TITLE
[DOCKER] Update vulkan installation to later versions of driver

### ISSUE THREAD

**Issue by tristan-arm** [apache/incubator-tvm#5560]
Broken external link (https://sdk.lunarg.com/sdk/download/1.0.65.0/linux/vulkansdk-linux-x86_64-1.0.65.0.run) results in https://github.com/apache/incubator-tvm/blob/master/docker/install/ubuntu_install_vulkan.sh failing to execute successfully.

Note: the 'run' script downloads successfully, however the result is a file containing the text 'Not Found'

**Comment by tqchen** [comment]
We should update the script to points to new version of vulkan drivers then

**Comment by tqchen** [comment]
https://github.com/apache/incubator-tvm/pull/5566
