### ISSUE TITLE
why the data and the weight for the nn.dense are not correct

### ISSUE THREAD

**Issue by angusHeZZ** [apache/incubator-tvm#5564]
Use implementation for op not is_dyn:  nn.dense
inputs size:  2
data input shape:  [1, 512]
weight input shape:  [1000, 512]
local_pyfunc:  <function dense_strategy at 0x7f80e8fc7598>
WARNING:strategy:dense is not optimized for this platform.
local_pyfunc:  <function wrap_compute_dense.<locals>._compute_dense at 0x7f80ba7d0048>

**Comment by angusHeZZ** [comment]
data input is NHWC,  How is the weight input setted to NHWC?

**Comment by tqchen** [comment]
Please open a new thread on https://discuss.tvm.ai/

**Comment by angusHeZZ** [comment]
T can not open a new thread on https://discuss.tvm.ai/

**Comment by angusHeZZ** [comment]
Your new topics appear here.

By default, topics are considered new and will show a new indicator if they were created in the last 2 days.

Visit your preferences to change this.
You have no new topics. Browse all categories or view latest topics
