### ISSUE TITLE
Failed to compile Rust examples on SGX

### ISSUE THREAD

**Issue by kaimast** [apache/incubator-tvm#5608]
When trying to compile the `test_nn` crate I get the following error.

```
  = note: rust-lld: error: undefined symbol: __tvm_module_startup
          >>> referenced by syslib.rs:54 (runtime/src/module/syslib.rs:54)
          >>>               tvm_runtime-f01990fd12d68664.1r4d5m44mb9eexid.rcgu.o:(_$LT$tvm_runtime..module..syslib..SystemLibModule$u20$as$u20$core..default..Default$GT$::default::hcb6bc8b13c957c71) in archive /home/kai/dev/tvm/rust/target/x86_64-fortanix-unknown-sgx/debug/deps/libtvm_runtime-f01990fd12d68664.rlib
```

The crate runs and compiles fine without SGX. i am not entirely sure where the tvm_moule_startup symbol is defined. Is there some other library I have to link to?

Thanks,
Kai

PS: Also the `apps/sgx` example seems to be broken.

**Comment by tqchen** [comment]
cc @nhynes

**Comment by nhynes** [comment]
https://github.com/apache/incubator-tvm/blob/master/apps/sgx/build.rs#L68-L73

**Comment by kaimast** [comment]
> https://github.com/apache/incubator-tvm/blob/master/apps/sgx/build.rs#L68-L73

Thanks. Not sure why but that fixes it!
