### ISSUE TITLE
time cost gap between autotvm and running.

### ISSUE THREAD

**Issue by Observer007** [apache/incubator-tvm#5610]
I tune a 1x1 conv with shape 28*128*56*56 and got a time cost gap between autotvm tuning log and actual running. The gap is about 0.01-0.05 ms and total execute time is 0.7-0.8 ms.
I used autoTVM tuning and got up to 3800 gflops, but during running with best parameters, I just got 3600 gflops.
The target and other parameters are same during tuning and running. My machine is intel clx-8280.
I used time_evaluation api and read its source code. I find that the call of RPC and other target are different. AutoTVM uses rpc and my running uses llvm. So is this the case?

**Comment by tqchen** [comment]
Please open a new thread on https://discuss.tvm.ai/
