### ISSUE TITLE
[Question] mxnet resnest, after using tvm is too slow

### ISSUE THREAD

**Issue by lichun-wang** [apache/incubator-tvm#5629]
Hi,
I downloaded resnest from gluon and converted it to mxnet model(json + params). Then I used tvm auto tune to make the model faster on 1080ti. But after tuning , the model became too slow . mxnet model take 15ms to process a image, but after tuning, it will take 380ms, I don't find the reason.

**Comment by kevinthesun** [comment]
Use debugger runtime to see which layer is the bottleneck?

**Comment by tqchen** [comment]
Please open a new thread on https://discuss.tvm.ai/

**Comment by lichun-wang** [comment]
> Use debugger runtime to see which layer is the bottleneck?

i print the time of the resnest, I found the cost of first layer( just conv + bn + relu ) was bigger than resnet, resnet just cost 0.75ms,  resnest cost 37ms, the only difference of is channel resnest is 64,resnet is 32 .  I open a issus on disscuss.tvm.ai :https://discuss.tvm.ai/t/question-after-auto-tune-the-speed-of-resnest101-and-resnet101-have-big-difference/6748
