### ISSUE TITLE
[PatternLang] pattern.partition doesn't include the last optional op.

### ISSUE THREAD

**Issue by comaniac** [apache/incubator-tvm#5647]
In the unit test of pattern language, the pattern `conv2d -> optional(bias_add) -> relu` can match `conv2d -> bias_add -> relu`, and the partitioned function does include 3 ops.

On the other hand, I tried to modify the pattern to `conv2d -> bias_add -> optional(relu)` and found the following issue:

1. Graph: `conv2d->bias_add`.

    * Match: True
    * Partition: Correct.

2. Graph: `conv2d->bias_add->relu`:

    * Match: True
    * Partition: The function only includes 2 ops (`conv2d` and `bias_add`) without `relu`.

Accordingly, I guess the last `optional` might be ignored during the matching process. After all, the last optional is useless for `match` operation, but we need to include it for partition.

```python
import tvm
from tvm import relay
from tvm.relay.dataflow_pattern import *

def test_match_option():
    x = relay.var('x')
    w = relay.var('w')
    b = relay.var('b')

    conv2d = is_op('nn.conv2d')(wildcard(), wildcard())
    bias = conv2d.optional(lambda x: is_op('nn.bias_add')(x, wildcard()))
    pattern1 = is_op('nn.relu')(bias)

    conv2d = is_op('nn.conv2d')(wildcard(), wildcard())
    bias = is_op('nn.bias_add')(conv2d, wildcard())
    pattern2 = bias.optional(lambda x: is_op('nn.relu')(x))

    conv2d = relay.op.nn.conv2d(x, w)
    bias_add = relay.op.nn.bias_add(conv2d, b)
    relu = relay.op.nn.relu(bias_add)

    assert pattern1.match(relu)
    print(pattern1.partition(relu))

    assert pattern2.match(relu)
    print(pattern2.partition(relu))

test_match_option()
```
cc @mbrookhart

**Comment by mbrookhart** [comment]
Ooh, fascinating, where did I screw up? :) Will debug, thanks!

**Comment by mbrookhart** [comment]
Okay, I see the problem. I'm doing a post order traversal of the expression to find subgraphs to partition. That means it comes to the bias-add first, that matches the pattern, so it marks that subgraph as part of a fusion. Then it gets to the relu, ALSO matches it to the pattern, but can't fuse the nodes  because they're already in another subgraph.

I either need to allow growing fusion groups, which seems a little sketchy, or do a preorder traversal. I think pre-order traversal will be cleaner.

**Comment by comaniac** [comment]
I encountered the similar issue before when we were implementing `PartitionGraph` pass in BYOC. We then had a group merging mechanism as you mentioned.

I think I didn't quite get the point of using preorder to solve this problem. Is this because the first/input nodes of a pattern are impossible to be optional?

**Comment by mbrookhart** [comment]
It's because the matching is pre-order: you start with the final node of the pattern, check to see if that matches the expresssion. If it does, you compare the pattern's inputs to the expr's inputs recursively.

**Comment by comaniac** [comment]
Ah I see. Yeah then I totally agree that using pre-order traversal would be cleaner.

**Comment by comaniac** [comment]
Thanks @mbrookhart for the quick fix :)
