### ISSUE TITLE
[REFACTOR] PassContext.fallback_device -> PassConfig.config

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-tvm#5650]
https://github.com/apache/incubator-tvm/pull/5631 Introduces a generic config mechanism to store the pass configuration options. Given that fallback_device is a pas related config, We should probably also migrate PassContext->fallback_device to a special config. e.g.` relay.fallback_device_type` with IntImmNode as its node type

**Comment by tqchen** [comment]
cc @zhiics

**Comment by zhiics** [comment]
@tqchen Thanks for reminding. I will take a stab next week.

**Comment by zhiics** [comment]
I realize we may also want to remove `relay.build_config` and directly use PassContext to keep it consistent to tir, but it may invoke a lot of changes. @tqchen thoughts?

**Comment by tqchen** [comment]
I agree we should do that as well

**Comment by zhiics** [comment]
One potential problem is that it may break downstream deployment.

**Comment by tqchen** [comment]
We could mark build_config as deprecation, and remove that API in the next release cycle. In the meanwhile, we should replace all of the current usages.

**Comment by zhiics** [comment]
Sounds like a good plan.
