### ISSUE TITLE
mxnet group conv not support very well by tvm

### ISSUE THREAD

**Issue by lichun-wang** [apache/incubator-tvm#5673]
hi，
I have a problem,  I use tvm to speed up resnet101(mxnet) on 1080ti， I try to use group conv, but after I set group =2, the speed became slower too much.  Then I try to speed up resnext101(mxnet). ResNext also became more slower .  So , do  tvm not support  group conv (mxnet ) ?

**Comment by lichun-wang** [comment]
if I set group=32, the speed is faster then group = 2.  if group = 1 ,  after tvm  , process one image cost  6ms, if group = 2 , cost about 200ms,  group = 3 cost 17ms.  When group =2 , the speed is the  slowest.

**Comment by lichun-wang** [comment]
sorry,  group=32,  cost17ms,  not group=3

**Comment by tqchen** [comment]
Thanks for reporting the problem, let us move to the discuss thread https://discuss.tvm.ai/t/mxnet-group-conv-not-support-very-well-by-tvm/6811/3
