### ISSUE TITLE
Publish TVM4J artifact

### ISSUE THREAD

**Issue by breandan** [apache/incubator-tvm#5707]
It would be great if there were a single multi-platform JAR for TVM4J, including Mac OS X, Windows and *nix x64 builds, available on a publicly accessible package repository to avoid [manual compilation](https://github.com/apache/incubator-tvm/tree/master/jvm#installation).

The [Z3-TurnKey](https://github.com/tudo-aqua/z3-turnkey#how) project is a pretty good example of how this works. If you inspect [the JAR](https://search.maven.org/remotecontent?filepath=io/github/tudo-aqua/z3-turnkey/4.8.7.1/z3-turnkey-4.8.7.1.jar), it contains prebuilt native binaries for OS X/Linux/Windows, [dispatching](https://github.com/tudo-aqua/z3-turnkey/blob/eb2ae31ad0390c1175e9a876b977d688e673ea2d/src/main/java/com/microsoft/z3/Z3Loader.java#L55) to the correct native library at runtime.

**Comment by tqchen** [comment]
Please open a new discuss thread on https://discuss.tvm.ai/ for the related topic. Due to the ASF policy, we only release source release officially. 

But we could faciliate community members and to publish binary releases as individuals and thirdparties.

**Comment by breandan** [comment]
Tried to resubmit this issue on the forums, but received the following message:

![image](https://user-images.githubusercontent.com/175716/83429283-d1ccbd80-a401-11ea-9916-aa26f0ca7cba.png)

**Comment by tqchen** [comment]
seems to be a false alarm of the discours, just approved, Thanks @breandan

**Comment by breandan** [comment]
Thanks @tqchen, continuing the discussion [here](https://discuss.tvm.ai/t/publish-tvm4j-artifact/6861).
