### ISSUE TITLE
Mismatched new / delete [ ] in Relay VM

### ISSUE THREAD

**Issue by akosik-anyvision** [apache/incubator-tvm#5728]
There seem to be mismatched new / delete[] statements in the following lines:

https://github.com/apache/incubator-tvm/blob/a64208910b22b60da5eb312d3a63cffb6e11f747/src/runtime/vm/vm.cc#L264
https://github.com/apache/incubator-tvm/blob/a64208910b22b60da5eb312d3a63cffb6e11f747/src/runtime/vm/vm.cc#L267
https://github.com/apache/incubator-tvm/blob/a64208910b22b60da5eb312d3a63cffb6e11f747/src/runtime/vm/vm.cc#L270
https://github.com/apache/incubator-tvm/blob/a64208910b22b60da5eb312d3a63cffb6e11f747/src/runtime/vm/vm.cc#L273
https://github.com/apache/incubator-tvm/blob/a64208910b22b60da5eb312d3a63cffb6e11f747/src/runtime/vm/vm.cc#L276
https://github.com/apache/incubator-tvm/blob/a64208910b22b60da5eb312d3a63cffb6e11f747/src/runtime/vm/vm.cc#L279

**Comment by tqchen** [comment]
cc @jroesch @zhiics

**Comment by zhiics** [comment]
They are allocated when the instruction is constructed and deleted when it is deconstructed

https://github.com/apache/incubator-tvm/blob/34c95a89eae13043aa3a269ad7d27d28837ffb56/src/runtime/vm/vm.cc#L100-L103

https://github.com/apache/incubator-tvm/blob/34c95a89eae13043aa3a269ad7d27d28837ffb56/src/runtime/vm/vm.cc#L66-L71

I don't think there is a mismatch.

**Comment by akosik-anyvision** [comment]
Sorry, the title is backwards. The issue is that `new[]` is used to allocate objects that are deleted with `delete`.

**Comment by zhiics** [comment]
ah, I see. We should have used `delete[]`. You are welcome to send a PR. Thanks.

**Comment by akosik-anyvision** [comment]
> ah, I see. We should have used delete[]. You are welcome to send a PR. Thanks.
Thanks for confirming. I would've done that directly, but I was waiting on approval from my company.
