### ISSUE TITLE
[Test][CPPTEST] File is not tested `./tests/cpp/relay_transform_sequential.cc`

### ISSUE THREAD

**Issue by junrushao1994** [apache/incubator-tvm#5744]
Occasionally I found that this file is not tested in our master's CI pipeline, and the primary reason is that the test launcher `./tests/scripts/task_cpp_unittest.sh` only finds executables ending with "_test"...I manually ran the file but it fails, because some global packed functions are renamed...

CC: @zhiics if you are interested in reviving this unit test :-)

**Comment by zhiics** [comment]
ahh, sorry about that. It worked locally before. Recently we changed schedule registration. That's probably why it fails.

**Comment by zhiics** [comment]
#5745

**Comment by junrushao1994** [comment]
Closed via #5745
