### ISSUE TITLE
Confusing error message when mod.export_library() with non-standard library suffix

### ISSUE THREAD

**Issue by wrongtest** [apache/incubator-tvm#5747]
When dump compiled library with ```lib.export_library(filename)```,  if the filename does not end with ".so" or ".dylib", there will lead to compiler error like
```
Traceback (most recent call last):
  File "export_tvm.py", line 14, in <module>
    lib.export_library("tvm_output/mylib")
  File "/incubator-tvm/python/tvm/runtime/module.py", line 340, in export_library
    fcompile(file_name, files, **kwargs)
  File "/incubator-tvm/python/tvm/contrib/cc.py", line 48, in create_shared
    _linux_compile(output, objects, options, cc)
  File "/incubator-tvm/python/tvm/contrib/cc.py", line 189, in _linux_compile
    raise RuntimeError(msg)
RuntimeError: Compilation error:
/lib/../lib64/crt1.o：在函数‘_start’中：
(.text+0x20)：对‘main’未定义的引用
collect2: error: ld returned 1 exit status
```
Since we almost always expect to export shared library (except tar), can this restrict be removed or more friendly noted? The current error is somewhat confusing.

**Comment by tqchen** [comment]
Good suggestion, let us enhance linux compile to detect the sufix of the file. Let us followup on https://discuss.tvm.ai/ given that it is more around development discussion
