### ISSUE TITLE
[RUNTIME][IR] String operator+

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-tvm#5792]
We have a few places in the code base that uses operator+ of String. Right now:

-  we either convert to std string https://github.com/apache/incubator-tvm/blob/master/src/tir/ir/expr.cc#L86
- Or added some overload that converts to std::string https://github.com/apache/incubator-tvm/blob/master/include/tvm/runtime/container.h#L1391

Given that operator+ is quite common, and we can have a better solution in these cases(by allocating the right result length then copy), perhaps we should have a good overload for most cases.

**Comment by tqchen** [comment]
cc @zhiics @wweic @junrushao1994

**Comment by junrushao1994** [comment]
I agree, not sure about the performance impact though

**Comment by tqchen** [comment]
k, it is mainly about the usability, than the perf aspect

**Comment by zhiics** [comment]
Besides this, I think we should make the comparison operators free functions instead of member functions because they are not communicative.

**Comment by tqchen** [comment]
@zhiics would you be interested in taking a stab?

**Comment by zhiics** [comment]
#5770 5806

**Comment by tqchen** [comment]
Closing thanks to @zhiics !
