### ISSUE TITLE
Darknet library support out of date/inconsistent with master?

### ISSUE THREAD

**Issue by alexwong** [apache/incubator-tvm#5835]
I recently tried to run the darknet tutorial using a shared library built from the master branch (https://github.com/pjreddie/darknet) rather than the one hosted here https://github.com/dmlc/web-data/tree/master/darknet/lib which seems to be https://github.com/siju-samuel/darknet/tree/tvm. I am hitting an error in the darknet->relay converter.

```
Traceback (most recent call last):

  File "tutorials/frontend/from_darknet.py", line 92, in <module>
    mod, params = relay.frontend.from_darknet(net, dtype=dtype, shape=data.shape)

  File "/tvm/python/tvm/relay/frontend/darknet.py", line 851, in from_darknet
    return GraphProto(net, shape, dtype).from_darknet()

  File "/tvm/python/tvm/relay/frontend/darknet.py", line 815, in from_darknet
    params = self._get_darknet_params(self._net.layers[i], prefix)

  File "/tvm/python/tvm/relay/frontend/darknet.py", line 664, in _get_darknet_params
    params = self._get_convolution_weights(layer, opname)

  File "/tvm/python/tvm/relay/frontend/darknet.py", line 470, in _get_convolution_weights
    biases = self._read_memory_buffer((layer.n, ), layer.biases)

  File "/tvm/python/tvm/relay/frontend/darknet.py", line 455, in _read_memory_buffer
    data_np[i] = data[i]

RuntimeError: cannot dereference null pointer from cdata 'float *'
```

Using either the .so hosted by TVM or building https://github.com/siju-samuel/darknet/tree/tvm works fine. I am wondering if this is a version problem between the master darknet branch and the one TVM is testing against (although, it seems the one TVM is using isn't that stale). If so, I am also wondering if/when the converter and library used by TVM for testing will be updated to the master version? @siju-samuel

**Comment by siju-samuel** [comment]
@alexwong This error is because the `network` and `layer` datastructure is not same. So the parsing have issues.
Im currently updating the whole code based on 'https://github.com/AlexeyAB/darknet' to support yolov4 and this can support previous versions as well.
Since we have to rely on their library (`.so`  we have to  build locally ) to parse darknet cfg and weight, maintenance is high for this framework.

**Comment by alexwong** [comment]
That makes sense. Do you have a rough idea of when you think you'll finish the update? Thanks!

**Comment by siju-samuel** [comment]
@alexwong You can use my private branch https://github.com/siju-samuel/tvm/tree/darknet_yolo
This can parse the latest darknet networks(including yolov4) with tvm. Since this branch cannot support some of exisitng networks, im not raising pr to tvm. If you find any issues please let me know.

**Comment by tqchen** [comment]
close for now as the original question was resolved, please open new followup threads on https://discuss.tvm.ai/
