### ISSUE TITLE
When I use Julia to call tvm at arm server, find the error : CommandLine Error: Option 'aarch64-enable-ccmp' registered more than once! LLVM ERROR: inconsistency in registered CommandLine options

### ISSUE THREAD

**Issue by agdkyang** [apache/incubator-tvm#5841]
When I use Julia to call tvm at arm server, find the error:
: CommandLine Error: Option 'aarch64-enable-ccmp' registered more than once! LLVM ERROR: inconsistency in registered CommandLine options

**Comment by tqchen** [comment]
Please open a new trouble shooting thread on https://discuss.tvm.ai/
