### ISSUE TITLE
[Micro] Some problems about riscv_spike micro device

### ISSUE THREAD

**Issue by BelfortXP** [apache/incubator-tvm#5908]
Anybody knows how to use of the riscv-spike?  The strange thing is that the spike shows "get unsupported command" when execute the test_alloc() in tvm\tests\python\unittest\test_runtime_micro.py.

The definition of config is like this:
![image](https://user-images.githubusercontent.com/39782968/85480629-f0823680-b5f2-11ea-80a5-6aafa7f2cb7a.png)
if the image cannot be loaded, you can see this: DEV_RISCV = micro.device.riscv_spike.generate_config(0x10000000, 0x20000, "127.0.0.1", 9824)

This is the information shows in spike:
![image](https://user-images.githubusercontent.com/39782968/85481149-ddbc3180-b5f3-11ea-81c4-8f40e4e27146.png)

Finally, thank you to everyone who will answer this question for me

**Comment by BelfortXP** [comment]
![image](https://user-images.githubusercontent.com/39782968/85481184-ed3b7a80-b5f3-11ea-9489-c08ec2a2279e.png)

**Comment by BelfortXP** [comment]
These are the information in spike, you can see this if the image cannot be loaded.

 spike --rbb-port=9824 -m0x10000000:0x20000 rot13-64
Listening for remote bitbang connection on port 9824.
warning: tohost and fromhost symbols not in ELF; can't communicate with target
remote_bitbang got unsupported command 'e'
remote_bitbang got unsupported command 's'
remote_bitbang got unsupported command 'e'
remote_bitbang got unsupported command 't'
remote_bitbang got unsupported command ' '
remote_bitbang got unsupported command 'u'
remote_bitbang got unsupported command 'n'
remote_bitbang got unsupported command ''

**Comment by tqchen** [comment]
Thanks @BelfortXP  Please open a new trouble shooting thread on https://discuss.tvm.ai/
