### ISSUE TITLE
TVM on conda-forge

### ISSUE THREAD

**Issue by marcelotrevisani** [apache/incubator-tvm#5981]
Just to let you know that I added TVM to the ``conda-forge``
So you will be able to install the tvm libs using conda such as:
``conda install -c conda-forge libtvm``
and the python interface using
``conda install -c conda-forge tvm-py``

https://github.com/conda-forge/tvm-py-feedstock
https://github.com/conda-forge/libtvm-feedstock

**Comment by marcelotrevisani** [comment]
Even ``nnvm``
https://github.com/conda-forge/nnvm-feedstock

If any of the maintainers want to maintain those recipes please let me know and I can add

**Comment by tqchen** [comment]
Thanks @marcelotrevisani  closing this issue for  now as there is nothing to be acted on. Feel free to post followups on https://discuss.tvm.ai/
