### ISSUE TITLE
How to call DNNL under TVM version 0.7

### ISSUE THREAD

**Issue by yangjing69** [apache/incubator-tvm#5996]
I'm using tvm version 0.7 and need to call the DNNL library, but tried the following statements and found that none of them are supported .
mod = relay.build_extern(mod, "dnnl") 
mod = relay.build_extern_compiler(mod, " dnnl")
mod = relay.transform.AnnotateExternalCompiler("xx")(mod)
How should I replace it?
Looking forward to everyone's help.Thank you!

**Comment by tqchen** [comment]
Thanks for asking the question. Please open a new discussion thread on https://discuss.tvm.ai/
