### ISSUE TITLE
Two issues when running Compile ONNX Models tutorial

### ISSUE THREAD

**Issue by austinmw** [apache/incubator-tvm#5998]
I've pulled the docker image `tvmai/demo-gpu` and am trying the tutorial [Compile ONNX Models](https://tvm.apache.org/docs/tutorials/frontend/from_onnx.html?highlight=onnx) using the python3 install inside the container.

The first issue I run into is that the line `from tvm import te` fails to import. The version of tvm inside this container is `'0.6.dev'`, so maybe the tutorial is a bit out of date?

The second issue I run into is in the section "Compile the model with relay":

```python
with tvm.transform.PassContext(opt_level=1):
    intrp = relay.build_module.create_executor('graph', mod, tvm.cpu(0), target)
```

> Traceback (most recent call last):
> 
>   File "<stdin>", line 1, in <module>
> 
> AttributeError: module 'tvm' has no attribute 'transform'

Any recommendations for how I should move past this would be greatly appreciated.

**Edit:** Looks like this change worked for the second issue:

```python
with tvm.relay.PassContext(opt_level=1):
    intrp = relay.build_module.create_executor('graph', mod, tvm.gpu(0), target)
```

**Comment by tqchen** [comment]
closing for now as the topic moved to https://discuss.tvm.ai/
