### ISSUE TITLE
[TEST][FLAKY] test_arith_solve_linear_inequality.py::test_multi_equal

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-tvm#6009]
https://ci.tvm.ai/blue/organizations/jenkins/tvm/detail/master/1247/pipeline

Seems was due to indeterminsm(possible iteration over a Map etc), perhaps we need to rewrite the assertion by subtraction and then simplify

**Comment by tqchen** [comment]
cc @yzhliu

**Comment by yzhliu** [comment]
ack

**Comment by fernchen** [comment]
I meet the same problem: https://ci.tvm.ai/blue/organizations/jenkins/tvm/detail/PR-6000/4/pipeline/38
Then I test this case many times, and find that this error does not always happen, it happens reandomly.

**Comment by junrushao1994** [comment]
should be good to close @tqchen

**Comment by zhiics** [comment]
close by #6014
