### ISSUE TITLE
Adding an operator support for frontend TFLite: 'NON_MAX_SUPPRESSION_V5'

### ISSUE THREAD

**Issue by cam145** [apache/incubator-tvm#6025]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

For feature proposals, list clear, small actionable items so we can track the progress of the change.

@FrozenGene @u99127 @yongwww @kevinthesun @maheshambule

I wonder if it is possible to add another operator 'NON_MAX_SUPPRESSION_V5' (https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/non-max-suppression-v5) for tflite frontend.

I am aware that you have implemented the operartor 'TFLite_Detection_PostProcess' in the tflite frontend.

Cheers.

**Comment by zhiics** [comment]
Could you please open a thread in the discussion forum (https://discuss.tvm.ai) for this issue? Thanks.

**Comment by fPecc** [comment]
Hi.

Can we reopen this issue? I am also trying to use a tflite model and am encountering the same error.
