### ISSUE TITLE
Adding an operator for frontend ONNX: NonMaxSuppression?

### ISSUE THREAD

**Issue by cam145** [apache/incubator-tvm#6026]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

For feature proposals, list clear, small actionable items so we can track the progress of the change.

I am aware that tensorflow frontend has an implementation of 'NonMaxSuppression'.

I wonder if it is possible to implement 'NonMaxSuppression' for onnx frontend.

Cheers

**Comment by zhiics** [comment]
Could you please open a thread in the discussion forum (https://discuss.tvm.ai) to start the discussion? Thanks.

**Comment by cam145** [comment]
Thanks for your message.  
I have posted on forum and came across an implementation on NMS from your AWS team. I wonder if your team intend to implement NMS on other frontend as well, e.g., onnx or tflite. I know mxnet is your main tool. Cheers
