### ISSUE TITLE
very slow runtime for keras compiler on CPU

### ISSUE THREAD

**Issue by taeheej** [apache/incubator-tvm#6028]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

For feature proposals, list clear, small actionable items so we can track the progress of the change.

**Comment by taeheej** [comment]
I am following 'Compile Keras Models' (https://tvm.apache.org/docs/tutorials/frontend/from_keras.html).
Instead of gpu, I set up target as 'llvm' and ctx as cpu. 
Then, I executed the following code. It takes about 12,000 millseconds. 
The warning message is 'Cannot find config for 'dense_nopack.x86' and 'conv2d_NCHWc.x86'.
Is there any solution to make better performance? 

-------------------------------------------------
target = 'llvm'
ctx = tvm.cpu(0)
with tvm.transform.PassContext(opt_level=3):
    executor = relay.build_module.create_executor('graph', mod, ctx, target)
dtype = 'float32'
tvm_out = executor.evaluate()(tvm.nd.array(data.astype(dtype)), **params)

**Comment by zhiics** [comment]
Could you please open a thread in the discussion forum https://discuss.tvm.ai? We generally use the forum to such discussions. Thanks.
