### ISSUE TITLE
Dispatcher warning for target-keys=tracing,cpu

### ISSUE THREAD

**Issue by eqy** [apache/incubator-tvm#6034]
https://github.com/apache/incubator-tvm/blob/64766c2cb1cd3ce41ee91a54909882036fffd412/python/tvm/autotvm/task/dispatcher.py#L419

Currently it seems that the warning will always print, even after tuning (e.g., for x86 CPU) when the key is "tracing,cpu". Is this the desired behavior or can the warning be suppressed here?

**Comment by tqchen** [comment]
Ideally we would like to supress the warning and only show once per error kind
