### ISSUE TITLE
 The version of tvm of v0.6.1 is incorrect.

### ISSUE THREAD

**Issue by LEA0317** [apache/incubator-tvm#6061]
There is a problem that the internal version of tag 0.6.1 has not been rewritten.
It remains at 0.6.0.

I fixed this problem in my repository and confirmed the version.
Check this one.
https://github.com/LEA0317/incubator-tvm/releases/tag/v0.6.1

**Comment by tqchen** [comment]
Thanks for reporting, cc @yzhliu

**Comment by yzhliu** [comment]
Thanks. I'll add one section to check&update version in the step-by-step release document.

**Comment by tqchen** [comment]
closing for now as the release docs PR update has been merged and we won't act on it further for now. Thanks @LEA0317
