### ISSUE TITLE
[IR] Missing check for dependency passes in SequentialNode::operator()

### ISSUE THREAD

**Issue by poyenc** [apache/incubator-tvm#6074]
## Problem
In [`SequentialNode::operator()`](https://github.com/apache/incubator-tvm/blob/8578096853eec5711bfcc9a3a68145fd12a135cb/src/ir/transform.cc#L364), before executing each passes, we do not check if their own dependency passes are all enabled:

```c++
IRModule SequentialNode::operator()(IRModule mod, const PassContext& pass_ctx) const {
  for (const Pass& pass : passes) {
    CHECK(pass.defined()) << "Found undefined pass for optimization.";
    const PassInfo& pass_info = pass->Info();
    if (!PassEnabled(pass_info)) continue; // THE PROBLEM: only check pass itself
    // resolve dependencies
    for (const auto& it : pass_info->required) {
      mod = GetPass(it)(std::move(mod), pass_ctx);
    }
    mod = pass(std::move(mod), pass_ctx);
  }
  return mod;
}
```

## Suggestion
In the loop shown above, add [`PassEnabled()`](https://github.com/apache/incubator-tvm/blob/8578096853eec5711bfcc9a3a68145fd12a135cb/src/ir/transform.cc#L334) call for all dependency passes.

**Comment by tqchen** [comment]
In this particular case, I think the behavior is expected. Because the dependency itself might be required in order to run the pass
