### ISSUE TITLE
error building docker image

### ISSUE THREAD

**Issue by HakanKumdakci** [apache/incubator-tvm#6087]
I run below command to clone repository.
`git clone --recursive https://github.com/apache/incubator-tvm tvm`
I run below command in tvm directory.
`docker build -t tvm.demo_android -f docker/Dockerfile.demo_android ./docker`
And got this error

![s1](https://user-images.githubusercontent.com/43298396/87777752-b7746500-c832-11ea-99a3-aaaa9c692c9a.png)

I couln't fix it. Its seems like sdkmanager can't find repo for extras;android;gapid;1 in repositories.cfg. So it can't download it and can't find it in device. I downloaded gapid and installed it. But it still doesn't work. Waiting for help..

**Comment by tqchen** [comment]
Could you please open a thread in the discussion forum https://discuss.tvm.ai? We generally use the forum to such discussions. Thanks.
