### ISSUE TITLE
tflite frontend reshape operator AssertionError assert op.BuiltinOptionsType() == BuiltinOptions.ReshapeOptions

### ISSUE THREAD

**Issue by cam145** [apache/incubator-tvm#6088]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

Based on the latest master branch, I used the following script https://www.dropbox.com/s/eooupdzsnxm5i8u/test_tflite_frontend.py?dl=0

and model file:

https://www.dropbox.com/s/qxiyfaiaefv57m8/simple_model_test_reshape.tflite?dl=0

Then got the following information:

    assert op.BuiltinOptionsType() == BuiltinOptions.ReshapeOptions
AssertionError

==========================================
Print out get the following information:

op.BuiltinOptionsType() = 0
BuiltinOptions.ReshapeOptions = 17

It seems that the two 'reshape' operators are incompatible or something else.

Thanks

For feature proposals, list clear, small actionable items so we can track the progress of the change.

**Comment by tqchen** [comment]
Could you please open a thread in the discussion forum https://discuss.tvm.ai? We generally use the forum to such discussions. Thanks.
