### ISSUE TITLE
[BUG] PartitionGraph and ccompiler too simplistic, too limited

### ISSUE THREAD

**Issue by mikeseven** [apache/incubator-tvm#6090]
Using the test_pass_partition_graph.py and whitelisting nn.conv2d to be built with ccompiler crashes in codegen.cc because it seems to support only the simple operations in this test!

Seems like ccompiler codegen is just a test itself??? 

Bummer, it would have been great to test separate compilation of real NN operators as a fallback mechanism on CPU if external compiler like DNNL are not available or not supporting an operation.

Thanks.

**Comment by comaniac** [comment]
Could you provide more details for the crashing you encountered? DNNL codegen is mainly for BYOC demonstration purpose and it's not in production for now.

On the other hand, BYOC does have the mechanism to offload supported ops to the external codegen.

**Comment by tmoreau89** [comment]
Having a small script to reproduce the bug would be helpful, thanks!

**Comment by mikeseven** [comment]
The script is simply test_pass_partition_graph.py is TVM tests. 
Replacing `mod=WhiteListAnnotator(["add","substract","multiply"], "ccompiler")(mod)`
with `mod=WhiteListAnnotator(["nn.conv2d"], "ccompiler")(mod)`

Then simply calling `relay.build(mod, target, params)`

Crash happens because it only knows about add, substract, multiply and nothing else. 
```
File "../src/relay/backend/contrib/codegen_c/codegen.cc", line 124
TVMError: Unrecognized op
```

I was under the assumption that using ccompiler would reuse TVM for x86 on the subgraph, similar to what on_device() does.

**Comment by comaniac** [comment]
The message you posted is expected. `ccompiler` is only used for demonstration purpose, and we don't expect to suppose more ops for it. The fallback mechanism on CPU is to use the LLVM backend instead directly.

**Comment by mikeseven** [comment]
ah ok, make sense now.
