### ISSUE TITLE
Question about how to compile tvm environment

### ISSUE THREAD

**Issue by 652994331** [apache/incubator-tvm#6101]
Hi, what i am doing is to build a tvm environment to test bert model inference. According to https://gist.github.com/icemelon9/860d3d2c9566d6f69fa8112840dd95c1. we need to build tvm c++ environment  with command like below:
![image](https://user-images.githubusercontent.com/51428350/87995724-dd478580-cb22-11ea-90de-26812b8cd458.png)

from the command above, i built llvm=6.60 and intel-mkl.

The problem is how to modify the CMakeList.txt and config.make

for now, i modify CMakeList.txt from the project and modify the config.cmake file under ./build like this:
![image](https://user-images.githubusercontent.com/51428350/87997919-08cd6e80-cb29-11ea-9bb8-ed3980b83dac.png)

but after i used cmake command , something wrong with my BLAS_LIBRARY, 
![image](https://user-images.githubusercontent.com/51428350/87998100-85604d00-cb29-11ea-8850-7d523f646ad4.png)

I think the problem might be the use_blas. could you please show me how to fix it, thanks

**Comment by 652994331** [comment]
the error screen shot is this one, mb.
![image](https://user-images.githubusercontent.com/51428350/87998141-ade84700-cb29-11ea-84c9-d482aa35bde2.png)

**Comment by tqchen** [comment]
Thanks for asking the question, Please open a new trouble shooting thread on https://discuss.tvm.ai/
