### ISSUE TITLE
[Runtime] should VM/graph runtime support multiple entry?

### ISSUE THREAD

**Issue by MarisaKirisame** [apache/incubator-tvm#6136]
I noticed that tvm only assume a single "main" entry in the code. I dont think this is a good design for training - when training a network, you will switch between training, validation, and maybe even pruning and quantization. 

If we do not allow multiple entry in tvm module, one will have to manage multiple module himself, which will result in code duplication and code complexity (one module to manage vs many module) then necessary.

Can we support multi-entry? If so how much work is it?
@tqchen @jroesch

**Comment by tqchen** [comment]
We support multiple entry by default by allowing the user to pick the name of the function. For example

```python
mod["xyz"]
```
refers to the function xyz, then we could followup to call the function xyz. In the case of the graph runtime, we can have ```gmod["set_input"]`, ```gmod["run"] ```, each of them can be viewed as an entry function

**Comment by tqchen** [comment]
For followup dicsussions like this, let us open new threads on the discuss forum https://discuss.tvm.ai/
