### ISSUE TITLE
[DOCS][REFACTOR] Update Pass Infra Docs to Reflect the latest State

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-tvm#6144]
The current doc https://tvm.apache.org/docs/dev/relay_pass_infra.html

- [x] Move to the tvm/ir section
- [x] Update terminologies
- [x] Split out the how-to usecases (how to construct pass, how to print out IR after each stage) into seperate guide and put them under the developer how-to guide section.

**Comment by tqchen** [comment]
cc @zhiics @jroesch

**Comment by zhiics** [comment]
Thanks, will do when I get cycles recently.
