### ISSUE TITLE
AttributeError: module 'tvm.runtime' has no attribute 'load'

### ISSUE THREAD

**Issue by 12101111** [apache/incubator-tvm#6158]
I'm testing the rust front-end example, and got this error when running `tvm/rust/tvm/examples/resnet/src/build_resnet.py`:
```
2020-07-28 15:36:02,208 - __main__ - INFO - build was successful
2020-07-28 15:36:02,209 - __main__ - INFO - test the build artifacts
Traceback (most recent call last):
  File "./src/build_resnet.py", line 130, in <module>
    test_build(build_dir)
  File "./src/build_resnet.py", line 115, in test_build
    lib = tvm.runtime.load(osp.join(build_dir, "deploy_lib.so"))
AttributeError: module 'tvm.runtime' has no attribute 'load'
```
In https://github.com/apache/incubator-tvm/pull/4837, It seems `tvm.module.load` is renamed to `tvm.runtime.load_module` in 250eb03b3aa60febf67389af2cf899ce2ddd3a88. But in the later commit f48486ca8ac436aaf89437d1f64744bc77bc3026, `tvm.module.load` is changed to `tvm.module.load`.

**Comment by tqchen** [comment]
THanks @12101111 good catch!

**Comment by tqchen** [comment]
https://github.com/apache/incubator-tvm/pull/6161
