### ISSUE TITLE
[DOC] xgboost require new cmake version

### ISSUE THREAD

**Issue by windclarion** [apache/incubator-tvm#6163]
2020-02-20 xgboost 1.0 need cmake 3.12,  2020-05-17  xgboost 1.1 need 3.13,  both version > 3.10.2 which is ubuntu 18.04 default cmake verison.   And it is  > 3.2 which TVM required, too.

our doc https://tvm.apache.org/docs/install/from_source.html#python-package-installation

say  "pip3 install --user tornado psutil xgboost"

Should we need to specify  these pip package version in the doc or

just leave individual programmer  to decide whether install xgboost==0.9.0 or update cmake to 3.13 by himself/herself?

**Comment by tqchen** [comment]
GIven that most of the platforms comes with xgboost binary wheel, so it shouldn't be a problem. Given that it is a dependency package problem, we won't put it as a requirement of TVM. But it might be helpful to put a note. @windclarion do you mind to send a PR?

**Comment by windclarion** [comment]
Yes, you are right!  I make a mistake, I misunderstand the cmake requirement which it belong to xgboost building procedure, each platform has its binary wheel, so it's not a problem!         Thanks tianqi!!
