### ISSUE TITLE
TVM output shape doesn't match DarkNet YOLO output

### ISSUE THREAD

**Issue by melty-chocolate** [apache/incubator-tvm#6185]
Lately I tried to benchmark tvm compiled darknet models, I followed the instruction from the darknet frontend tutorial. I found output shape mismatch between tvm compiled models and original darknet models.

For darknet imagenet classifier models, the output shape of tvm compiled model is `(1000, 1)` while original darknet model output shape is `(1, 1000, 1, 1)`.

For darknet yolov2 and yolov3 models, I noticed that there is an additional post-processing step after `m.run()`, is it possible to make this post-processing part of the `m.run()`? Is the out of `m.run()` same as [float *out = net->output](https://github.com/pjreddie/darknet/blob/f6d861736038da22c9eb0739dca84003c5a5e275/src/network.c#L505) ?  As [float *out = net->output](https://github.com/pjreddie/darknet/blob/f6d861736038da22c9eb0739dca84003c5a5e275/src/network.c#L505) is a C pointer, is there a good way to convert C pointer to ndarray?

Any help would be appreciated! @siju-samuel

**Comment by siju-samuel** [comment]
>> For darknet imagenet classifier models, the output shape of tvm compiled model is (1000, 1) while original darknet model output shape is (1, 1000, 1, 1).

I think this is a bug, an extra flatten is happening during softmax.

>> For darknet yolov2 and yolov3 models, I noticed that there is an additional post-processing step after m.run(), is it possible to make this post-processing part of the m.run()? Is the out of m.run() same as float *out = net->output ? As float *out = net->output is a C pointer, is there a good way to convert C pointer to ndarray?

the postprocessing after `m.run` is for marking of bounding boxes. 
the `net->output` and `m.run` output is same.

>> is there a good way to convert C pointer to ndarray?

 [This link](https://github.com/apache/incubator-tvm/blob/1823a7b7007d7d7dfef3cdaf5cb60198fd853517/tests/python/frontend/darknet/test_forward.py#L44) may help.

**Comment by tqchen** [comment]
Good discussions . please follow up on https://discuss.tvm.ai. We generally use the forum to such discussions. Thanks.
