### ISSUE TITLE
GoogleNet aux is None in pytorch test

### ISSUE THREAD

**Issue by wjliu1998** [apache/incubator-tvm#6201]
When running
`TVM_FFI=ctypes python -m pytest -v /home/liuwenjian/incubator-tvm/tests/python/frontend/pytorch/test_forward.py -k "test_googlenet"
`

error will occur at 
https://github.com/apache/incubator-tvm/blob/90bde33e60a3ae0d18a767eba9a2092eab204788/tests/python/frontend/pytorch/test_forward.py#L179

the error message is 
"
         assert(isinstance(orig, torch.nn.Module))
E       AssertionError
anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py:2195: AssertionError
"

This is because when getting googlenet pretrained model, the aux module is always None. Therefore the assert will fail

torch.__version__='1.6.0+cu101'
tvm.__version__='0.7.dev1'

**Comment by masahi** [comment]
PyTorch 1.6 is not supported yet, a PR welcome.

**Comment by wjliu1998** [comment]
I'll try this one, thanks!
