### ISSUE TITLE
Reshape does not check that shape change is valid

### ISSUE THREAD

**Issue by tkonolige** [apache/incubator-tvm#6210]
This following code snippet causes zero errors. Running this module with the graph runtime also does not error.
```python
from tvm import relay
x = relay.var("x", shape=[2,3])
y = relay.reshape(x, [7])
f = relay.Function([x], y)
mod = relay.build(f, target="llvm")
```
@tqchen

**Comment by tkonolige** [comment]
@mbrookhart

**Comment by mbrookhart** [comment]
I see that the Shape relation function indeed fails to check for a valid reshape. I'm kind of surprised that running it doesn't crash. What value does the 7th element of the output have?

**Comment by mbrookhart** [comment]
Doesn't look like the recent dynamic work removed a check, I'll spend some time tomorrow to see if we can add one to the shape relation function.

**Comment by tkonolige** [comment]
@mbrookhart I figured out how to add a shape check to reshape. I will submit the PR tomorrow.
