### ISSUE TITLE
Why is the inference time obtained with module.time_evaluator method less, but the inference time obtained with the method defined by myself is slower?

### ISSUE THREAD

**Issue by SmallHedgehog** [apache/incubator-tvm#6266]
# using module.time_evaluator
`
print("Evaluate inference time cost...")
ftimer = module.module.time_evaluator("run", ctx, number=1, repeat=600)
prof_res = np.array(ftimer().results) * 1000  # convert to millisecond
print("Mean inference time (std dev): %.2f ms (%.2f ms)" %(np.mean(prof_res), np.std(prof_res)))

`
# 27.6ms

# using myself method
`with tvm.target.cuda():
         with autotvm.apply_history_best(log_file):
             print("Compile...")
             with relay.build_config(opt_level=3):
                 graph, lib, params = relay.build(mod, 'cuda', 'llvm', params=params)
             tvm_model = graph_runtime.create(graph, lib, ctx)
             tvm_model.set_input(**params)
             tvm_model.set_input(input_name, tvm.nd.array(image))
             
             times = 0.0
             for i in range(600):
                 s = time.time()
                 tvm_model.run()
                 pred = tvm_model.get_output(0).asnumpy()
                 tvm_out = pred[0]
                 times += time.time() - s
             print(times / 600)
`
# about 72ms

**Comment by tqchen** [comment]
Thanks for reporting the problem, the community uses https://discuss.tvm.ai/ for quick trouble shooting and discussions, please open a new thread there

**Comment by glc12125** [comment]
I think your code includes the time to copy data from GPU to CPU, whereas the time_evaluator(...) does not. Please see [this](https://discuss.tvm.apache.org/t/what-time-does-time-evaluator-include/1293) as an reference.
