### ISSUE TITLE
[TEST][FLAKY] test_normal fails intermittently

### ISSUE THREAD

**Issue by electriclilies** [apache/incubator-tvm#6309]
`test_normal` in `tests/python/contrib/test_random.py` has been failing intermittently on GPU for two of my recent PRs. My PRs implement dynamic shapes, which currently only run on CPU, not GPU, so it is pretty clear that the failure was not caused as a result of my changes. 

See the output from Jenkins for more info:
https://ci.tvm.ai/blue/organizations/jenkins/tvm/detail/PR-6298/6/pipeline/
https://ci.tvm.ai/blue/organizations/jenkins/tvm/detail/PR-6273/13/pipeline/

**Comment by tqchen** [comment]
Thanks @electriclilies , seems to be a flaky problem that we need to fix.

**Comment by tqchen** [comment]
cc @FrozenGene @merrymercy can you help to look into it?

**Comment by electriclilies** [comment]
Thanks @FrozenGene @tqchen!
