### ISSUE TITLE
[Auto-TVM] How to Auto tune the model on iOS device

### ISSUE THREAD

**Issue by dileep223** [apache/incubator-tvm#6320]
Hi  Experts,

I need to Auto-tune the ONNX model on iOS device. i went through the some of the tutorials from https://tvm.apache.org/docs/tutorials/index.html#auto-tuning . i’m able to tune the model on the cuda (NVIDIA-GPU)target, but some how my bad i’m not able auto-tune the model on iOS device ( there is no tutorial on iOS device).
1. can we able to Auto-tune the model on iOS device ? 

if yes can you please help me to how to tune the model on iOS device.

Thank you.

**Comment by tqchen** [comment]
move to https://discuss.tvm.ai/t/auto-tvm-how-to-auto-tune-the-model-on-ios-device/7681/3
