### ISSUE TITLE
How to use tvm in colab? tvm-0.7.dev1-cp36-cp36m-linux_x86_64.whl:Access Denied

### ISSUE THREAD

**Issue by StevenJokes** [apache/incubator-tvm#6325]
I'm learning d2l-tvm
I'm using win10.
So I want to use tvm in colab
But I'm having problem with installation.
Please look : https://github.com/d2l-ai/d2l-tvm/issues/46
Anyone can help me?

---

![image](https://user-images.githubusercontent.com/25657787/90979821-28bddb00-e58a-11ea-9c83-e0d39ff8302d.png)

**Comment by tqchen** [comment]
Thanks for the discussion, the community uses the discuss forum for related topics, let us move the discussion there https://discuss.tvm.ai/t/getting-started-installation/4706/2

Note that however, right now the community does not yet provide a binary wheel, and it is recommended to install from source. Some community members are actively working towards a solution that might help later.
