### ISSUE TITLE
NotImplementedError: The following operators are not implemented: ['aten::leaky_relu_', 'aten::pixel_shuffle']

### ISSUE THREAD

**Issue by wjliu1998** [apache/incubator-tvm#6328]
It seems that the leaky_relu has been implemented in tvm, aten::leaky_relu_ is just an alias which is not included in convert_map.

However, aten::pixel_shuffle seems not implemented

**Comment by kosuke55** [comment]
@wjliu1998 
Thak you for the issue. I also found the same error.
The problem of leaky_relu_ Is it solved only by just adding
```
        "aten::leaky_relu_"                     : _leaky_relu(),
```
to the [convert_map](https://github.com/apache/incubator-tvm/blob/9aa69e2e14a75962faaf352b639c9daf53fc2222/python/tvm/relay/frontend/pytorch.py#L2042)?

**Comment by kosuke55** [comment]
I was missing the latest version. `leaky_relu_` was added in this commit. https://github.com/apache/incubator-tvm/commit/f56bb71df9c93ba8830c5ab632352b3b2569bec9
