### ISSUE TITLE
Android shared lib (so) can not run on Android 4.4.2 

### ISSUE THREAD

**Issue by snsun** [apache/incubator-tvm#6329]
Hi all, Recently, I am using TVM to deploy my pytorch model to android devices. When I use an Android phone with android 6.0, everything goes well. However, when I use another andorid pad with version android 4.4.2, the so goes wrong. I used logcat to capture the log and I got :

rnnt_decoder.so (fused_cast_take_divide_add_round_cast_clip_cast_expand_dims_cast_subtract_layout_9068456268455801501_)

I/DEBUG ( 2213): 8a785fa8 7d46c208

I/DEBUG ( 2213): 8a785fac 7d467c40

I/DEBUG ( 2213): #00 8a785fb0 7d461080

I/DEBUG ( 2213): … …

I/DEBUG ( 2213): #01 8a785fb0 7d461080

I/DEBUG ( 2213): … …

I/DEBUG ( 2213): #02 8a785fb0 7d461080

For the android api, i use android-19. Anyone has met the same problem?

**Comment by tqchen** [comment]
Thanks for reporting the problem, please open a trouble shooting thread on https://discuss.tvm.ai/ Perhaps you should use the same ndk that comes with the corresponding android version?
