### ISSUE TITLE
Faster RCNN: Unable to compile for CPU because topk fails

### ISSUE THREAD

**Issue by ashutoshparkhi** [apache/incubator-tvm#6340]
Hello,

This the variant that fails with topk error.
http://download.tensorflow.org/models/object_detection/faster_rcnn_inception_v2_coco_2018_01_28.tar.gz

Error:
        **%10934 = topk(%10930, %10933, k=None, dtype="int32")^[[31m the function is provided too many arguments expected 1, found 2; ^[[39m;**

Is anyone already working to fix this issue?

Please let me know if I need to serve more details.

Tagging @yongwww as he has recently done some fixes for SSD.
Is there any plan to support this variant of Faster RCNN?
Can I try any variant that already compiles and runs with Relay VM?

Thanks,
Ashutosh

**Comment by ashutoshparkhi** [comment]
While trying to compile it with commit a64feed, compilation goes through.

**Comment by electriclilies** [comment]
To clarify, does #5996 compile it correctly (i.e., is #5595 the most recent commit that works)? I suspect this may be an issue with the tensorflow importer.

**Comment by electriclilies** [comment]
Also, if you have a version that is already compiled, you should be able to run it with the relay VM. This is most likely an issue with the tensorflow importer.

**Comment by yongwww** [comment]
@ashutoshparkhi fasterrcnn should be supported, could you try with latest tvm again? very likely the topk issue you faced is from frontend, topk got one more unexpected argument

**Comment by ashutoshparkhi** [comment]
Thanks @yongwww and @electriclilies. TOT has the fix for it.
