### ISSUE TITLE
Perf tools to further improve the performance of given schedule.

### ISSUE THREAD

**Issue by xutianming** [apache/incubator-tvm#6356]
Dear developers,

I was optimizing a TextCNN model with TVM on intel x86.
I wrote my own Conv1D NCWc schedule based on Conv2D

![image](https://user-images.githubusercontent.com/4970790/91565965-8fba0600-e975-11ea-85a4-83d66b2cbdf3.png)

TVM stack only has operator-level performance tools. 
**How could I further locate the hot-spot of the operator**  ?

I tried gdb, and the ZMM registers were utilized.
![image](https://user-images.githubusercontent.com/4970790/91566257-f808e780-e975-11ea-9c36-abc16099fb04.png)

I also tried linux-perf, but didn't get much clue.

I asked the same question on [TVM discuss](https://discuss.tvm.ai/t/how-to-further-improve-the-performance-of-given-schedule/7711), but got no reply.

Sincerely hope for your reply.

**Comment by tqchen** [comment]
Thanks @xutianming , let us followup in https://discuss.tvm.ai/t/how-to-further-improve-the-performance-of-given-schedule/7711/2
