### ISSUE TITLE
Tutorial page is not available

### ISSUE THREAD

**Issue by xu78guo6** [apache/incubator-tvm#6371]
I'm new to TVM want to know how to start from compiling. it seems that the tutorial page https://tvm.apache.org/docs/tutorials/ cannot be visited. I've tried serveral entrances looks like a tutorial and all  shown 404 not found.

**Comment by yongwww** [comment]
@tqchen @zhiics

**Comment by Wheest** [comment]
@xu78guo6 can confirm I've got the same issue.  In the meantime, this [archive.org](https://web.archive.org/web/20200106185813/https://docs.tvm.ai/install/from_source.html) snapshot should have most of the tutorials, and the Juypter notebooks are also in the repo under [tutorials](https://github.com/apache/incubator-tvm/tree/master/tutorials).

**Comment by zhiics** [comment]
The tvm website, including the docs and tutorials, is migrated to: http://tvm.apache.org/

**Comment by Wheest** [comment]
Great, thanks.  Though I don't think it's got its SSL cert set up yet, at least on the couple of browsers I checked on.
