### ISSUE TITLE
`import tvm` now requires pytest

### ISSUE THREAD

**Issue by leandron** [apache/incubator-tvm#6398]
With the merge of #6331, `import tvm` now requires pytest. I created this issue just to check whether this is something intentional or something that we want to fix.

The chain from `import tvm` to `import pytest` happens due to the `from .import testing` on `python/tvm/__init__.py`. There is nothing actually done with that import.

https://github.com/apache/incubator-tvm/blob/a4ebb16ed76bfea4ce4eed7be7ea73d4a01027e2/python/tvm/__init__.py#L53-L56

Within `python/tvm/testing.py` then there is the `import pytest`. I was thinking that we might want to remove these lines from `__init__.py`, so that we don't load `tvm.testing` and will only import it when required. I'm happy to submit a PR removing those lines, in case there is an understanding that it makes sense.

cc @tqchen

**Comment by tqchen** [comment]
I agree. thanks @leandron !

**Comment by tkonolige** [comment]
Good catch.

When I was adding the pytest-related functions, I originally put them in `tests/python/__init__.py` so they would be local to the tests. Unfortunately, doing this meant that you could no longer run files directly. Instead you'd have to specify the module path. For example, `python tests/python/unittest/test_ir_type.py` would become `python -m tests.python.unittest.test_ir_type`.
