### ISSUE TITLE
Compiling error: library not found for -llibxml2.tbd

### ISSUE THREAD

**Issue by xu78guo6** [apache/incubator-tvm#6406]
Today I tried to rebuild tvm dylib on mac, meet this error:
[100%] Linking CXX shared library libtvm.dylib
ld: library not found for -llibxml2.tbd
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have built tvm successfully several days ago following installation on website and git pull some new code then. It seems that the new code causes this problem.

**Comment by xu78guo6** [comment]
I have found /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libxml2.tbd  and added this path to LD_LIBRARY_PATH, dont know why it happen.

**Comment by tqchen** [comment]
Please open a new troubleshooting thread on https://discuss.tvm.apache.org/. The current CI has a mac build, so it might due to soe problems in your local setup
