### ISSUE TITLE
Can the code of bitserial_dense(including compute and schedule) run on GPU? 

### ISSUE THREAD

**Issue by linbinskn** [apache/incubator-tvm#6409]
Can the code of bitserial_dense(including compute and schedule) run on GPU? 

I am using the code of bitserial_dense to test the mixed bitwidth matrix multiplication. I have found the version of x86 and arm_cpu, but I haven't found the version of cuda. Does the implementation of bitserial_dense supports the GPU?

**Comment by tqchen** [comment]
Thanks for asking the question, please open a new thread on https://discuss.tvm.apache.org/
