### ISSUE TITLE
arm64 : undefined symbol: __extendhftf2 at runtime

### ISSUE THREAD

**Issue by tom-gall** [apache/incubator-tvm#6415]
After building TVM on debian with the distro compiler (gcc 8), when you first load libtvm.so, the undefined symbol error will spring up crashing your python app.

Within in src/relay/transforms/pattern_util.h the addition of
    reinterpret_cast<__fp16*>(array->data)[i];

If you try and build the same with llvm, it'll just straight out ICE the compiler. 

While the LLVM issue is now fixed in mainline, for those on native arm64 using debian I wonder if we shouldn't defensively address the issue.

**Comment by tqchen** [comment]
https://github.com/apache/incubator-tvm/pull/6431
