### ISSUE TITLE
[RFC] v0.7 Release Planning

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-tvm#6421]
Thanks to everyone who works hard in the past cycle. This RFC to plan for v0.7 release.  The community has always been focusing on high quality releases.

One of the major highlights in the past cycle is that we have gone through major refactors to make sure we have a fresh new foundation for new things we want to develop, and there are also exciting new features such as auto scheduler and uTVM coming in.

Considering the nature of the new foundational change, we propose to focus of this release on landing key foundational changes we have made -- for example the new TIR/target and pass infra, since they affect the API itself. 

Because we are landing new features at a fast pace, we might include experimental features(that does not affect API itself) that may still need stabilization and work to cut another release after these features stabilize. We would include auto_scheduler(ansor) and intitial uTVM would be part of this release as experimental features and we will continue to polish the features in the incoming cycle.

Please share your thoughts. 

In the next few days we will be populating the release note in this thread.  Most release note content will be derived from our monthly report.

**Comment by tqchen** [comment]
@ZihengJiang and @zhiics have kindly agreed to serve as release managers for this release

**Comment by junrushao1994** [comment]
Do we have a target date for the release?

**Comment by tqchen** [comment]
Of course the the date would depends on the status of the release, because we should always aim for quality. Based on our past experience, it might takes a few weeks.

**Comment by comaniac** [comment]
1. Is the error reporting feature included in this release as an experimental feature or it would be in the next release?

2. For the experimental features, auto_scheduler and uTVM, would that be better to decorate their entry points with something like `@experiment` so that it pops a warning to tell users this feature is experimental (and maybe the actions we expect users to take when they encounter issues)?

**Comment by jroesch** [comment]
@comaniac if we land the final error reporting PR it removes the existing error reporting from type checker completely, I think we should either choose to ship it this release or delay until next release. One worry is that there will probably be a period of stability where we iterate/polish on new errors.

**Comment by comaniac** [comment]
> @comaniac if we land the final error reporting PR it removes the existing error reporting from type checker completely, I think we should either choose to ship it this release or delay until next release. One worry is that there will probably be a period of stability where we iterate/polish on new errors.

Make sense to me (including the worry as well). Different from auto_scheduler and uTVM, error reporting is not just a standalone module that users can completely ignore, so we should be more careful.

**Comment by tqchen** [comment]
I agree that we should mark certain features as initial support/experimental in the release note. We could also come up with documentation tags to mark the feature as experimental. I am less certain sure about shooting a warning for each function call, as they harm the overall user experience, perhaps we can start with the release note and docs?

**Comment by zhiics** [comment]
Yeah, I also prefer to document it instead of throwing many warnings. In addition, we have some checker in the codebase claiming that some APIs will be deprecated in the next release. We probably want to take some actions on them as well.

**Comment by u99127** [comment]
I'd like to see the tvmc work to be functional before we cut the release please. I'd also like to see the Ethos-N PRs land as well.

**Comment by ZihengJiang** [comment]
@apache/tvm-committers  @jroesch @u99127 @comaniac 

We have a release note candidate here: https://github.com/apache/incubator-tvm/issues/6486

Please comment it if you have anything want to be added into this release or other opinion.

**Comment by tqchen** [comment]
Also jump in here. Let us plan to cut a release next week. At this point we should "freeze the features", but please suggest a list of PRs(fixes) that need to be merged.

**Comment by comaniac** [comment]
A brief summary of the related PRs missed in the current release note candidates. Not sure if all of them have to be listed so just for reference. Except for the note followed by the PR indicating its status, all PRs listed here are merged.

Automatic Scheduling (Experimental)
  * [AutoTVM][Ansor] Enable random fill and CPU cache flush for AutoTVM and Ansor (#6391)
  * [Minor] Fix typos in Ansor (#6425)
  * [TUTORIAL][ANSOR] Using the template-free auto-scheduler on CPU (#6488)
  * [ANSOR] Auto-scheduler tutorial for GPU and necessary refactor/fix (#6512)
  * [Ansor] Parallel the InitPopulation (#6512)
  * [Ansor][FLAKY] Bug fix for compute at mutation error (#6557)

BYOC
  * [BYOC][CONTRIB] Vitis-AI codegen integration (#6343) -- expected to merge in 2 weeks.
  * [BYOC][ETHOSN] Introduce further operator support (#6355)
  * [BYOC][JSON] Support input nodes with multiple entries (#6368)
  * [BYOC][TensorRT] TensorRT BYOC integration (#6368) -- expected to merge in 2 weeks.
  * [BYOC][ACL] Add maximum support for float32 (#6506)
  * [BYOC][ACL] Support add operation (#6532) -- expected to merge in 1 week.
  * [BYOC][ETHOSN] Fix tests for new module API (#6560) -- expected to merge in 1 week.

TVMC(Experimental)
  * [tvmc] Introduce 'tune' subcommand (part 3/4) (#6537) -- expected to merge in 1 week.
  * TVMC part 4/4: Tutorial -- not filed yet but I suppose it's required if we list TVMC as an experimental feature in 0.7 (cc @leandron, @u99127).

**Comment by tqchen** [comment]
At this point, we should focus on stablization, so we don't have to rush in features like Vitis-AI and TensorRT and we do them in v0.8 cycle(for better stablization).  We should instead list PRs that contains necessary fixes that need to be inlcuded.

**Comment by comaniac** [comment]
> At this point, we should focus on stablization, so we don't have to rush in features like Vitis-AI and TensorRT and can do them in the v0.8 cycle(for better stablization). We should instead list PRs that contains necessary fixes that need to be inlcuded.

Make sense. Removed them from the list.

**Comment by ZihengJiang** [comment]
@comaniac Thanks for checking! I have added missing ones except those are not merged yet.

**Comment by leandron** [comment]
> TVMC(Experimental)
>     * [tvmc] Introduce 'tune' subcommand (part 3/4) (#6537) -- expected to merge in 1 week.
>     * TVMC part 4/4: Tutorial -- not filed yet but I suppose it's required if we list TVMC as an experimental feature in 0.7 (cc @leandron, @u99127).

@comaniac, yes, it would be great to merge #6537 before, lets try to solve all the issues early next week; Also, "part 4/4", related to `tvmc run` is coming very soon, Monday max, and it would be great to have it as well, so that we have the first package complete

**Comment by tqchen** [comment]
Let us aim for Oct 1st as the tentative date for the release cutting. would be great to merge #6537  before then

**Comment by leandron** [comment]
> Let us aim for Oct 1st as the tentative date for the release cutting. would be great to merge #6537 before then

So, #6537 and #6578 would be the final two PRs to complete the first version of `tvmc`.

**Comment by comaniac** [comment]
> So, #6537 and #6578 would be the final two PRs to complete the first version of `tvmc`.

Per offline discussion with @leandron, the final PR for TVMC would be a simple tutorial planned to be sent by tomorrow. We will do our best to review and merge them before Oct 1st.

**Comment by leandron** [comment]
> > So, #6537 and #6578 would be the final two PRs to complete the first version of `tvmc`.
> 
> Per offline discussion with @leandron, the final PR for TVMC would be a simple tutorial planned to be sent by tomorrow. We will do our best to review and merge them before Oct 1st.

The mentioned tutorial PR is https://github.com/apache/incubator-tvm/pull/6597

**Comment by ZihengJiang** [comment]
@leandron @comaniac @tqchen 
We are still waiting CI for #6597 and #6578 . I have added them into the release note and let's merge them tomorrow morning.

**Comment by comaniac** [comment]
> @leandron @comaniac @tqchen
> We are still waiting CI for #6597 and #6578 . I have added them into the release note and let's merge them tomorrow morning.

Thanks. I am actually waiting to merge them today but still waiting for their CIs.

**Comment by comaniac** [comment]
@ZihengJiang both were merged.

**Comment by zhiics** [comment]
@comaniac cool, thanks. We plan to make a cut tomorrow.

**Comment by tqchen** [comment]
https://github.com/apache/incubator-tvm/tree/v0.7
