### ISSUE TITLE
[BUG] Lots Python Tests or Tutorials Failed by The Changes of PR #6399

### ISSUE THREAD

**Issue by Johnson9009** [apache/incubator-tvm#6453]
$ python3 tutorials/optimize/opt_gemm.py
Numpy running time: 0.006542
Traceback (most recent call last):
  File "tutorials/optimize/opt_gemm.py", line 113, in <module>
    tvm.testing.assert_allclose(c.asnumpy(), answer, rtol=1e-5)
AttributeError: module 'tvm' has no attribute 'testing'

The issue #6398  and PR #6399 remove the `from . import testing` from file `python/tvm/__init__.py`, but lots of test cases and tutorials still using `tvm.testing.xxx` when only with `import tvm`, so now they will fail with the error message like the above one.

**Comment by tqchen** [comment]
https://github.com/apache/incubator-tvm/pull/6454
