### ISSUE TITLE
Cannot build for RK3399 Mali GPU

### ISSUE THREAD

**Issue by anoop54** [apache/incubator-tvm#6471]
First I install the libmali-rk-midgard-t86x-r14p0_1.6-3ayufan5_arm64.deb so that I have the library installed, and then when I try to build TVM I will have issues. My error is as follows:

-- Build with RPC support...
-- Build with Graph runtime support...
-- VTA build with VTA_HW_PATH=/home/rock/Desktop/tvm/3rdparty/vta-hw
-- Build VTA runtime with target: sim
-- Build with standalone CRT
CMake Error at /usr/local/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find OpenCL (missing: OpenCL_LIBRARY) (found version "2.2")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.16/Modules/FindOpenCL.cmake:150 (find_package_handle_standard_args)
  cmake/modules/OpenCL.cmake:53 (find_package)
  CMakeLists.txt:324 (include)

-- Configuring incomplete, errors occurred!
See also "/home/rock/Desktop/tvm/build/CMakeFiles/CMakeOutput.log".
Makefile:46: recipe for target 'runtime' failed
make: *** [runtime] Error 1

Do I need to revert to an older version? I don't think there is a newer driver out.

**Comment by tqchen** [comment]
Please open a new thread on https://discuss.tvm.apache.org/. It would be great if you can dig into FindOpenCL to see what happens. You can try to manually set up the opencl path and library path in this case
