### ISSUE TITLE
[TOPI] Missing import in python source?

### ISSUE THREAD

**Issue by roastduck** [apache/incubator-tvm#6473]
Please have a look at this file:

https://github.com/apache/incubator-tvm/blob/dd37ed50c4fda2e402c52a5cb44d15597f9d7cc4/python/tvm/topi/bifrost/gemm.py

I think a `from tvm import te` is missing, since `te` is directly used around this file.

I don't know how this file passes the tests, but Python reports an error to me.

**Comment by masahi** [comment]
I saw a similar issue, in my case `tvm.testing` was not imported but CI doesn't complain. if I run the test directly it fails with due to missing import. I guess it relates to how pytest resolves imports.

**Comment by tqchen** [comment]
good catch, please send a PR to fix the problem. It is due to how pytest running everything together and file being imported elsewere
