### ISSUE TITLE
[RELAY] Inaccurate doc for nn.dense

### ISSUE THREAD

**Issue by roastduck** [apache/incubator-tvm#6490]
https://github.com/apache/incubator-tvm/blob/b8d385c2ab741cb254aa700b48546799273276ee/python/tvm/relay/op/nn/nn.py#L1388

Doc of `nn.dense` says it compute `Y = X * W`, but it should actually be `Y = X * W^T` as the shape checking below.

https://github.com/apache/incubator-tvm/blob/b8d385c2ab741cb254aa700b48546799273276ee/src/relay/op/nn/nn.h#L66

I think we'd better doc this transposition (or memory layout).

**Comment by tqchen** [comment]
Rgabjs @roastduck , a PR is more than welcomed

**Comment by roastduck** [comment]
Fixed in #6508
