### ISSUE TITLE
[TOPI] Typo in operator key

### ISSUE THREAD

**Issue by roastduck** [apache/incubator-tvm#6492]
https://github.com/apache/incubator-tvm/blob/bdfefbb03f5aab96ee677ee28a166dd6ab5dbf3f/python/tvm/topi/bifrost/dense.py#L26

"biforst" should be "bifrost". This bug makes the op totally unavailable in Relay.

I can fix this bug if expected, but I don't know how to add a proper test.

**Comment by zhiics** [comment]
cc @mbaret @icemelon9 

I think we I have test in test_topi: https://github.com/apache/incubator-tvm/blob/master/tests/python/topi/python/test_topi_dense.py#L40, but the target is probably not enabled in the CI

**Comment by mbaret** [comment]
Ah yes... It's very difficult to keep these maintained due to the lack of a Mali GPU in CI. I don't have immediate access to one either but that change looks obviously correct to me.

**Comment by tqchen** [comment]
Thanks @roastduck please send a PR
