### ISSUE TITLE
Question:Errors when ran the tutorials of raspberry pi

### ISSUE THREAD

**Issue by ljs19981117** [apache/incubator-tvm#6520]
When I ran the raspberry pi tutorial(https://tvm.apache.org/docs/tutorials/frontend/deploy_model_on_rasp.html).I got the errors below.I am new to AI,and I really don't know how to fix it.Please help me.

RPCError: Traceback (most recent call last):
  [bt] (8) /home/ljs/tvm/build/libtvm.so(std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::runtime::RPCModuleNode::WrapRemoteFunc(void*)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&)+0x33) [0x7fd651d0e2f3]
  [bt] (7) /home/ljs/tvm/build/libtvm.so(tvm::runtime::RPCWrappedFunc::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const+0x3c5) [0x7fd651d0dd55]
  [bt] (6) /home/ljs/tvm/build/libtvm.so(tvm::runtime::RPCClientSession::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)> const&)+0x57) [0x7fd651cfe9b7]
  [bt] (5) /home/ljs/tvm/build/libtvm.so(tvm::runtime::RPCEndpoint::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)>)+0x215) [0x7fd651cf6415]
  [bt] (4) /home/ljs/tvm/build/libtvm.so(tvm::runtime::RPCEndpoint::HandleUntilReturnEvent(bool, std::function<void (tvm::runtime::TVMArgs)>)+0x1ab) [0x7fd651cf518b]
  [bt] (3) /home/ljs/tvm/build/libtvm.so(tvm::runtime::RPCEndpoint::EventHandler::HandleNextEvent(bool, bool, std::function<void (tvm::runtime::TVMArgs)>)+0xd7) [0x7fd651cfe6a7]
  [bt] (2) /home/ljs/tvm/build/libtvm.so(tvm::runtime::RPCEndpoint::EventHandler::HandleProcessPacket(std::function<void (tvm::runtime::TVMArgs)>)+0x126) [0x7fd651cfe486]
  [bt] (1) /home/ljs/tvm/build/libtvm.so(tvm::runtime::RPCEndpoint::EventHandler::HandleReturn(tvm::runtime::RPCCode, std::function<void (tvm::runtime::TVMArgs)>)+0x13f) [0x7fd651cfd95f]
  [bt] (0) /home/ljs/tvm/build/libtvm.so(+0x18ef442) [0x7fd651cf3442]
  [bt] (8) /home/ubuntu/tvm/build/libtvm.so(+0x103b100) [0xffff91e9d100]
  [bt] (7) /home/ubuntu/tvm/build/libtvm.so(tvm::runtime::RPCServerLoop(int)+0xac) [0xffff91e9c7b4]
  [bt] (6) /home/ubuntu/tvm/build/libtvm.so(tvm::runtime::RPCEndpoint::ServerLoop()+0xe8) [0xffff91e800c8]
  [bt] (5) /home/ubuntu/tvm/build/libtvm.so(tvm::runtime::RPCEndpoint::HandleUntilReturnEvent(bool, std::function<void (tvm::runtime::TVMArgs)>)+0x258) [0xffff91e7fb40]
  [bt] (4) /home/ubuntu/tvm/build/libtvm.so(tvm::runtime::RPCEndpoint::EventHandler::HandleNextEvent(bool, bool, std::function<void (tvm::runtime::TVMArgs)>)+0x1e4) [0xffff91e88184]
  [bt] (3) /home/ubuntu/tvm/build/libtvm.so(tvm::runtime::RPCEndpoint::EventHandler::HandleProcessPacket(std::function<void (tvm::runtime::TVMArgs)>)+0x168) [0xffff91e87ea0]
  [bt] (2) /home/ubuntu/tvm/build/libtvm.so(tvm::runtime::RPCSession::AsyncCallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::RPCCode, tvm::runtime::TVMArgs)>)+0x58) [0xffff91e9b368]
  [bt] (1) /home/ubuntu/tvm/build/libtvm.so(tvm::runtime::LocalSession::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)> const&)+0x74) [0xffff91e8e9c4]
  [bt] (0) /home/ubuntu/tvm/build/libtvm.so(+0xfbf140) [0xffff91e21140]
  File "/home/ubuntu/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 81, in cfun
    rv = local_pyfunc(*pyargs)
  File "/home/ubuntu/tvm/python/tvm/rpc/server.py", line 69, in load_module
    m = _load_module(path)
  File "/home/ubuntu/tvm/python/tvm/runtime/module.py", line 411, in load_module
    _cc.create_shared(path + ".so", files)
  File "/home/ubuntu/tvm/python/tvm/contrib/cc.py", line 43, in create_shared
    _linux_compile(output, objects, options, cc, compile_shared=True)
  File "/home/ubuntu/tvm/python/tvm/contrib/cc.py", line 205, in _linux_compile
    raise RuntimeError(msg)
  File "/home/ljs/tvm/src/runtime/rpc/rpc_endpoint.cc", line 370
RPCError: Error caught from RPC call:
RuntimeError: Compilation error:
/tmp/tmp8ci2y3co/net/lib0.o: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status

Command line: g++ -shared -fPIC -o /tmp/tmp8ci2y3co/net.tar.so /tmp/tmp8ci2y3co/net/lib0.o /tmp/tmp8ci2y3co/net/devc.o

**Comment by FrozenGene** [comment]
Please consider opening new thread in https://discuss.tvm.apache.org/, we use this forum to solve this kind of question. Your question should be related with the target and compiler (g++) doesn't match. For example, target is x86 but compiler (g++) is arm.

**Comment by ljs19981117** [comment]
> Please consider opening new thread in https://discuss.tvm.apache.org/, we use this forum to solve this kind of question. Your question should be related with the target and compiler (g++) doesn't match. For example, target is x86 but compiler (g++) is arm.
Thanks for your reminding.I will ask in the disscuss.tvm.
I make the target to rasp3b,but got this:
```
> "-target" is deprecated, use "-mtriple" instead.
> Cannot find config for target=llvm -keys=arm_cpu,cpu -device=arm_cpu -mattr=+neon -model=bcm2837 -mtriple=armv7l-linux-gnueabihf, workload=('dense_nopack.x86', ('TENSOR', (1, 512), 'float32'), ('TENSOR', (1000, 512), 'float32'), None, 'float32'). A fallback configuration is used, which may bring great performance regression.
```
Is the API update ?
