### ISSUE TITLE
rust examples are not working.

### ISSUE THREAD

**Issue by intheworld** [apache/incubator-tvm#6526]
rust/tvm/examples/resnet/src/build_resnet.py 
"cargo build" went wrong, when add "--pretrained" args.

--- stderr
thread 'main' panicked at 'Could not prepare demo: AttributeError: <class 'tvm.ir.module.IRModule'> has no attribute params', tvm/examples/resnet/build.rs:31:5

**Comment by qixiuai** [comment]
I did not encounter the error when add "--pretrained" args using the master branch 044885860842e6c9936b45ab4edbd23f0e3c727b.

**Comment by intheworld** [comment]
I find a similar script as follow.
https://github.com/apache/incubator-tvm/blob/master/tutorials/frontend/from_mxnet.py
And I change the build_resnet.py accordingly.

**Comment by tqchen** [comment]
Closed by #6527
