### ISSUE TITLE
multi-thread

### ISSUE THREAD

**Issue by stormchasingg** [apache/incubator-tvm#6543]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

For feature proposals, list clear, small actionable items so we can track the progress of the change.

**Comment by stormchasingg** [comment]
I'm developing a program using TVM. A C++ multi-thread code is registered as a Python code through PackedFunc of TVM. I test the running time of C++ code. The result shows that multi-thread speeds the code. But when I test the running time in Python side, multi-thread doesn't work. Does TVM support multi-thread ?

**Comment by tqchen** [comment]
Please open a new thread on https://discuss.tvm.apache.org/ where the community collectively discusses related questions
