### ISSUE TITLE
[TEST][FLAKY] ParallelFor issue in test_sketch_search_policy_basic

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-tvm#6548]
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-6547/1/pipeline

**Comment by tqchen** [comment]
cc @merrymercy @jcf94 please look into it and send a fix

**Comment by merrymercy** [comment]
I guess it is introduced by #6529.
You can revert #6529 if this is urgent.
This can be assigned to @jcf94

**Comment by jcf94** [comment]
Thanks. I will check this carefully and fix it as soon as possible.

**Comment by tqchen** [comment]
Another related https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-6554/2/pipeline

**Comment by comaniac** [comment]
Looks like the same problem as #6557 fixed. Should be fine now.
