### ISSUE TITLE
[New Op request] _sample_normal and _sample_gamma from mxnet 1.7.0

### ISSUE THREAD

**Issue by rubick1896** [apache/incubator-tvm#6556]
I got the following message when trying to compile DeepAR model from Gluonts
`
---------------------------------------------------------------------------
OpNotImplemented                          Traceback (most recent call last)
<ipython-input-3-9838f83506d7> in <module>
----> 1 mod, params = relay.frontend.from_mxnet(predictor.prediction_net, shape_dict)

~/.local/lib/python3.7/site-packages/tvm-0.7.dev1-py3.7-linux-x86_64.egg/tvm/relay/frontend/mxnet.py in from_mxnet(symbol, shape, dtype, arg_params, aux_params)
   2596             sym = mx.sym.Group(sym)
   2597         shape, dtype = _update_shape_dtype(shape, dtype, params)
-> 2598         func = _from_mxnet_impl(sym, shape, dtype, params, mod)
   2599     elif isinstance(symbol, mx.gluon.Block):
   2600         raise NotImplementedError("Only Hybrid Blocks are supported now.")

~/.local/lib/python3.7/site-packages/tvm-0.7.dev1-py3.7-linux-x86_64.egg/tvm/relay/frontend/mxnet.py in _from_mxnet_impl(symbol, shape_dict, dtype_info, params, mod)
   2472         msg = '\n'.join(['{}: {}'.format(op_name, cnt) for op_name, cnt in unsupported.items()])
   2473         raise tvm.error.OpNotImplemented(
-> 2474             'One or more operators are not supported in frontend MXNet:\n{}'.format(msg))
   2475 
   2476     for nid, node in enumerate(jnodes):

OpNotImplemented: One or more operators are not supported in frontend MXNet:
_sample_gamma: 10
_sample_normal: 10
`
DeepAR: https://gluon-ts.mxnet.io/api/gluonts/gluonts.model.deepar.html
TVM version:  0.7.dev1

Is it possible to support these operations in the near future?

**Comment by tqchen** [comment]
Consolidate to https://github.com/apache/incubator-tvm/issues/6813
