### ISSUE TITLE
auto scheduler/Ansor auto_scheduler.auto_schedule do not auto exit 

### ISSUE THREAD

**Issue by luchangli03** [apache/incubator-tvm#6570]
when I use auto scheduler to tune GPU batch_matmul or CONV2D program, the python did not quit even if the tune auto_scheduler.auto_schedule call is finished. I must use ctrl +c to manually stop the search thread.

![image](https://user-images.githubusercontent.com/34341633/94363268-a4fc8e80-00f3-11eb-8c9b-48994cdc5017.png)
the program is just like this:
![image](https://user-images.githubusercontent.com/34341633/94363439-b003ee80-00f4-11eb-8d0d-7a790627a52e.png)

**Comment by luchangli03** [comment]
found a solution: call os._exit(os.EX_OK)  after auto_scheduler.auto_schedule()

**Comment by comaniac** [comment]
Did you `del measure_ctx` at the end, as suggested by the tutorial?

**Comment by merrymercy** [comment]
We should call `del measure_ctx` explicitly.
We do this in the last section of the tutorial. But it is not emphasized in the tutorial.
@luchangli03 Would you mind sending a PR to improve the tutorial?

**Comment by merrymercy** [comment]
#6660
