### ISSUE TITLE
Unable to build NMS in tensorflow

### ISSUE THREAD

**Issue by fernchen** [apache/incubator-tvm#6571]
When I execute the test case in tests/python/frontend/tensorflow/test_forward.py, I try to change the mode to “” in _test_forward_nms_v3(…) function, then it will raise some error, like this:

>   File "test_forward.py", line 165, in run_tvm_graph
    graph, lib, params = relay.build(mod, target, target_host, params)
  File "/root/projects/tvm_open/python/tvm/relay/build_module.py", line 259, in build
    graph_json, mod, params = bld_mod.build(mod, target, target_host, params)
  File "/root/projects/tvm_open/python/tvm/relay/build_module.py", line 126, in build
    self._build(mod, target, target_host)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 321, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 256, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 245, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 160, in tvm._ffi._cy3.core.CALL
tvm._ffi.base.TVMError: Traceback (most recent call last):
  [bt] (8) /root/projects/tvm_open/build/libtvm.so(tvm::relay::ExprFunctor<void (tvm::RelayExpr const&)>::VisitExpr(tvm::RelayExpr const&)+0x10c) [0x7fbc61b04f1e]
  [bt] (7) /root/projects/tvm_open/build/libtvm.so(tvm::NodeFunctor<void (tvm::runtime::ObjectRef const&, tvm::relay::ExprFunctor<void (tvm::RelayExpr const&)>*)>::operator()(tvm::runtime::ObjectRef const&, tvm::relay::ExprFunctor<void (tvm::RelayExpr const&)>*) const+0x11e) [0x7fbc61b05d8c]
  [bt] (6) /root/projects/tvm_open/build/libtvm.so(tvm::relay::ExprFunctor<void (tvm::RelayExpr const&)>::InitVTable()::{lambda(tvm::runtime::ObjectRef const&, tvm::relay::ExprFunctor<void (tvm::RelayExpr const&)>*)#6}::_FUN(tvm::runtime::ObjectRef const&, tvm::relay::ExprFunctor<void (tvm::RelayExpr const&)>*)+0x25) [0x7fbc61b05582]
  [bt] (5) /root/projects/tvm_open/build/libtvm.so(tvm::relay::ExprFunctor<void (tvm::RelayExpr const&)>::InitVTable()::{lambda(tvm::runtime::ObjectRef const&, tvm::relay::ExprFunctor<void (tvm::RelayExpr const&)>*)#6}::operator()(tvm::runtime::ObjectRef const&, tvm::relay::ExprFunctor<void (tvm::RelayExpr const&)>*) const+0x3e) [0x7fbc61b05556]
  [bt] (4) /root/projects/tvm_open/build/libtvm.so(tvm::relay::StorageAllocator::VisitExpr_(tvm::relay::CallNode const*)+0x167) [0x7fbc61d2ef4b]
  [bt] (3) /root/projects/tvm_open/build/libtvm.so(tvm::relay::StorageAllocator::CreateToken(tvm::RelayExprNode const*, bool)+0x1b7) [0x7fbc61d2ecbb]
  [bt] (2) /root/projects/tvm_open/build/libtvm.so(tvm::relay::StorageAllocator::Request(tvm::relay::StorageToken*)+0x33) [0x7fbc61d2f457]
  [bt] (1) /root/projects/tvm_open/build/libtvm.so(tvm::relay::StorageAllocator::GetMemorySize(tvm::relay::StorageToken*)+0x16d) [0x7fbc61d2f255]
  [bt] (0) /root/projects/tvm_open/build/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x4e) [0x7fbc60f619be]
  File "/root/projects/tvm_open/src/relay/backend/graph_plan_memory.cc", line 293
TVMError: Check failed: pval != nullptr: Cannot allocate memory symbolic tensor shape [?]

you can reproduce this problom by change the `mode` to "" in _test_forward_nms_v3 function of  tests/python/frontend/tensorflow/test_forward.py scripts and then execute the script.

**Comment by tqchen** [comment]
Thanks for asking the question, it would be great to use https://discuss.tvm.apache.org/ for general trouble shooting. In this particular case, it might due to the fact that the model imported contains dynamic shape and we do not support graph runtime for that(need to use vm)
