### ISSUE TITLE
how to evaluate inference's accuracy

### ISSUE THREAD

**Issue by zotanika** [apache/incubator-tvm#6576]
Dear TVM team,

I'm struggling to figure out the reason why the models hosted at [https://www.tensorflow.org/lite/guide/hosted_models](url) experience huge accuracy drop after converting with relay.frontend.from_tflite(). For instance, mobilenet_v1_1.0_224 claimed to hit top1 72%, top5 91% accuracy becomes top1 61%, top5 87%.

First, I would like to reproduce the result accuracy given at [https://tvm.apache.org/docs/dev/benchmark.html](url) for resnet18 and reuse these benchmark infrastructures to debug the problem efficiently, but I cannot find the source codes matching to schema v0.1 log format described in the page.

Do I miss something, or is there any other reference to do this job?

**Comment by tqchen** [comment]
Thanks for asking the question, it would be great to use https://discuss.tvm.apache.org/ for general trouble shooting. In this particular case, it might due to relates to things like pre-processing and other issues. It would be great if you can dig deeper into the problem
