### ISSUE TITLE
[Docs] relay.nn.bias_add with axis=-1?

### ISSUE THREAD

**Issue by gussmith23** [apache/incubator-tvm#6592]
The documentation for `bias_add` does not seem to indicate what `axis=-1` means, though it appears in Relay's version of ResNet.

**Comment by gussmith23** [comment]
cc @hogepodge

**Comment by tqchen** [comment]
I believe it is like most numpy conventions. Negative axis means starting from the highest dimension.

Let us also use https://discuss.tvm.apache.org/ for this kind of general topics so we can also get more attentions there :)

**Comment by gussmith23** [comment]
It is somewhat implicit what negative `axis` values mean; they're used in other places in Relay. I bet a lot of people know what it means right off the bat.

**Comment by tqchen** [comment]
I agree it might be helpful to update the document, Thanks @gussmith23 for bringing this up
