### ISSUE TITLE
CHECK(data != nullptr) causes type checking to fail

### ISSUE THREAD

**Issue by electriclilies** [apache/incubator-tvm#6608]
Many type relations check that types are not equal to nullptr. This results in early failure of the type checker. As an example, when trying to import efficientnet-b0 (tflite-int8-model), this error occurs: 

`%0 = qnn.requantize(%images, 0.012566f, 131, 0.012566f, 3, out_dtype="int8") an internal invariant was violated while typechecking your program [17:21:40] /home/vega/github/incubator-tvm/src/relay/qnn/op/requantize.cc:261: Check failed: data != nullptr`

Instead of applying a check, the type relation should return false if data is equal to nullptr. This way, the type checker can continue to try to figure out what the type of data is. If the type checker really cannot find the type, the type checker itself should throw an error. 

cc @jwfromm @areusch @vegaluisjose 

I should be able to get a fix up soon.

**Comment by areusch** [comment]
I think this was reproduced by trying to import the ONNX model generated by

```
python3 -m pip install geffnet
wget "https://github.com/rwightman/gen-efficientnet-pytorch/blob/master/onnx_export.py"
python3 onnx_export.py ./onnx_export/b4.onnx --model="tf_efficientnet_b4_ns" --img-size=380
```

from https://discuss.tvm.apache.org/t/unable-to-build-relay-function-twice/7987

**Comment by vegaluisjose** [comment]
@areusch that was actually the workaround. In other words, using the "onnx" version from this conversion does not seems to trigger the issue. However, I haven't tested the "correctness" of this onnx model, compared to the version provided in tensorflow hub.

The issue originally was found by using the TF-lite (8-bit) model directly. Specifically, this one:

https://tfhub.dev/tensorflow/lite-model/efficientnet/lite0/int8/2

**Comment by areusch** [comment]
thanks for clarifying @vegaluisjose !

**Comment by electriclilies** [comment]
These are the type relations I've found that have this issue, but I could be missing some. 
- [ ]  ArgWhereRel
- [ ]  WhereRel
- [ ]  StridedSliceRel
- [ ]  SparseToDenseRel
- [ ]  NdarraySizeRel
- [ ]  MultiBoxTransformLocRel
- [ ]  DequantizeRel
- [ ]  QuantizeRel
- [ ]  RequantizeRel
- [ ]  SimulatedQuantizeRel
