### ISSUE TITLE
[VOTE] Release Apache TVM (incubating) v0.7.0.rc0

### ISSUE THREAD

**Issue by ZihengJiang** [apache/incubator-tvm#6622]
Dear TVM community,

This is a call for vote to release Apache TVM (incubating) version 0.7.0.  This is a major release with many new features and improvement. All users of Apache TVM (incubating) 0.6 are advised to upgrade. The release is co-managed by Zhi Chen (@zhiics).

Link to release notes: 
https://github.com/apache/incubator-tvm/releases/tag/v0.7.0.rc0 

Link to release candidate: 
https://dist.apache.org/repos/dist/dev/incubator/tvm/tvm-v0.7.0-rc0

The vote will be open for at least 72 hours. Everyone is welcomed to vote. Please vote by replying to this thread explicitly.

+1 = approve
+0 = no opinion
-1 = disapprove (provide reason)

NOTE: this thread is being mirrored in dev@

**Comment by yzhliu** [comment]
+1, I have checked

Incubating in name
Verified signature and checksum
LICENSE checked
NOTICE checked
DISCLAIMER checked

**Comment by tqchen** [comment]
+1 (binding), I checked

Signatures and hashes good
DISCLAIMER, LICENSE, NOTICE
Signatures and hashes
No unexpected binary files
Code compiles

TQ

**Comment by bgchun** [comment]
+1 (binding)

- I checked the signature and hash. 
- DISCLAIMER, LICENSE, and NOTICE look good
- No unexpected binary files
- The code compiles and runs

Thanks.
-Gon

**Comment by FrozenGene** [comment]
+1, I checked

- signature and hash
- LICENSE, DISCLAIMER and NOTICE
- Version
- Code compiles

**Comment by zhiics** [comment]
+1 (binding)

- Checked the signature and hash
- The code compiles
- Checked LICESE and NOTICE

**Comment by tmoreau89** [comment]
+1 (binding):

**Comment by jroesch** [comment]
+1 (binding)
* Checked the code compiles
* Checked License and Notice
* Version

**Comment by comaniac** [comment]
+1

* Checked the code compiles
* Checked LICENSE and NOTICE
* Checked version.

**Comment by tvm-archiver** [comment]
+1 (binding)

I checked:
* Checksum
* Code compiles

**Comment by ZihengJiang** [comment]
Thanks everyone for voting. The voting result has been sent out.
