### ISSUE TITLE
[RFC] Move to use main as default branch

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-tvm#6623]
Dear TVM Community:

In light of recent proposed change of [github's default branch from master to main](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/). It would be great for the community to consider such a change. Given the minimum impact to set it up. We believe is a net positive to the community and also keeps us up to the latest github convention.

This thread seeks formal lazy consensus :) Everyone is also more than welcomed to share their thoughts.

TQ

**Comment by tqchen** [comment]
To be fully transparent about what it would take:

- create main branch from master
- setup branch protection 
- New PRs and other activities will continue to work as normal
- For stale PRs that still need updates, re-raise against the new default -- given we merge PRs actively and stale PR usually requires CI retrigger anyway, there wont be a big overhead.

**Comment by junrushao1994** [comment]
It makes a lot of sense. Let’s follow the new default setting in github carefully to make sure the transition is smooth. Thanks a lot!

**Comment by szha** [comment]
> For stale PRs that still need updates, re-raise against the new default

It's also feasible to just change the base of each of the open PR to target the new branch. Since the branches are identical initially, this switch shouldn't cause any issue. It can be carried out alongside the change in default branch setting.

**Comment by hogepodge** [comment]
This change would be in accordance with the [Apache Code of Conduct](https://www.apache.org/foundation/policies/conduct.html) across several dimensions.

1. It creates a more open community.
2. It shows empathy for the diverse open source community.
3. It encourages collaboration.
4. It is being careful with the words we choose.
5. It aligns with the diversity statement.

**Comment by tqchen** [comment]
Thanks everyone, the lazy consensus has passed.

**Comment by tqchen** [comment]
As of now, the default branch has been changed to main. I have also spend some time to update base branch of the existing PRs, but it would be great to double check for a bit when we merge PR this week. 

@apache/tvm-committers  please check the information when merging a PR ([XXX] want to merge into apache:main from [YYY]). If the base branch have not been changed, click Edit and change the base branch to apache:main

**Comment by tqchen** [comment]
All the open PR's base has been updated to main
