### ISSUE TITLE
[Anosr][Bug] ValueError: arch(sm_xy) is not passed, and we cannot detect it from env

### ISSUE THREAD

**Issue by Hecmay** [apache/incubator-tvm#6634]
## Environment 
* Ubuntu 18.04.5 LTS
* CUDA Version: 11.0. 
* GPU: RTX 2080 Ti. Compute Compatibility : 7.5

## Description

I created a simple MatMul tensor expression in C++, and want to use Anosr to search the optimal schedule for it. Here is the skeleton of the program that I am using. The `args` is an array of tensor inputs and output of the MatMul op.  
```c++
  // Create DAG and search task
  const auto& dag = tvm::auto_scheduler::ComputeDAG(args);
  auto task = SearchTask(dag, "test", Target("cuda"), Target("llvm"), Optional<HardwareParams>());

  // Create tuning options and search policy 
  auto options = TuningOptions(num_measure_trials, early_stopping, 
                               num_measures_per_round, verbose, builder, runner,
                               Optional<Array<MeasureCallback>>());
  auto policy = SketchPolicy(task, cost_model, params, seed, verbose, callbacks);

  // Launch Ansor 
  std::pair<te::Schedule, Array<te::Tensor>> res = AutoSchedule(policy, options);
```

When running the program, `measure.py` complains that the GPU architecture cannot be found. The error message is as followed. I tried some solutions in this link: https://discuss.tvm.apache.org/t/solved-compile-error-related-to-autotvm/804/11. But none of them worked in my case. 

```shell
------------------------------------------------------------
-------------------------  [ Search ]
------------------------------------------------------------
Generate Sketches               #s: 1
Sample Initial Population       #s: 744 fail_ct: 3352   Time elapsed: 0.39
GA Iter: 0      Max score: 0.0000       Min score: 0.0000       #Pop: 744       #M+: 0  #M-: 0
GA Iter: 5      Max score: 0.0000       Min score: 0.0000       #Pop: 2048      #M+: 1446       #M-: 89
GA Iter: 10     Max score: 0.0000       Min score: 0.0000       #Pop: 2048      #M+: 1573       #M-: 94
EvolutionarySearch              #s: 128 Time elapsed: 3.50
------------------------------------------------------------
-------------------------  [ Measure ]
------------------------------------------------------------
Get 10 programs for measure. (This may take a while)
.E.E.E.E.E.E.E.E.E.E
==================================================
No: 1   GFLOPS: 0.00 / 0.00     results: MeasureResult(error_type:CompileHostError, error_msg:Traceback (most recent call last):
  File "/home/sx/dlcb/build/tvm/python/tvm/auto_scheduler/measure.py", line 516, in timed_func
    sch, args, target=task.target, target_host=task.target_host
  File "/home/sx/dlcb/build/tvm/python/tvm/driver/bu
...
et_arch)
  File "/home/sx/dlcb/build/tvm/python/tvm/contrib/nvcc.py", line 71, in compile_cuda
    raise ValueError("arch(sm_xy) is not passed, and we cannot detect it from env")
ValueError: arch(sm_xy) is not passed, and we cannot detect it from env
, all_cost:0.02, Tstamp:1601955085.48)
==================================================
```

I guess my env settings should be correct, since I was able to run the Ansor tutorial. I also tried to specify the architecture string manually (i.e. to be `sm_75` in my case). But Ansor will throw the following error when I do so:
```shell
==================================================
No: 4   GFLOPS: 0.00 / 0.00     results: MeasureResult(error_type:RuntimeDeviceError, error_msg:Traceback (most recent call last):
  File "/home/sx/dlcb/build/tvm/python/tvm/auto_scheduler/measure.py", line 672, in timed_func
    ndarray.empty(get_const_tuple(x.shape), x.dtype, ctx) for x in build_res.args
  File "/home/sx/dlcb/build/tvm/py
...
] (0) /home/sx/dlcb/build/tvm/build/libtvm.so(+0x1791844) [0x7fd1ecfb3844]
  File "/home/sx/dlcb/build/tvm/src/runtime/cuda/cuda_device_api.cc", line 115
CUDA: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading: initialization error
, all_cost:0.46, Tstamp:1601956508.32)
==================================================
```

**Comment by zhiics** [comment]
cc @merrymercy @jcf94 @comaniac

**Comment by comaniac** [comment]
It seems to me that your solution by providing the `sm_75` to the first error was correct. For the runtime initialization error, it is case by case, because not all schedule candidates are valid on your GPU. As long as Ansor can still find valid schedules you should be fine. This happens quite often especially on small GPUs such as T4. Could you provide the number of explored trials and the final throughput achieved by Ansor?

**Comment by Hecmay** [comment]
Hi @comaniac Cody, thanks for your reply.

I just used the default parameters of 10 trails. All of 10 trails returned the same error when running the evaluation. The finally returned schedule (from `Autoschedule(policy, options)`) is the unoptimized schedule (with no thread or block binding).
```shell
] (0) /home/sx/dlcb/build/tvm/build/libtvm.so(+0x1791844) [0x7f6429edf844]
  File "/home/sx/dlcb/build/tvm/src/runtime/cuda/cuda_device_api.cc", line 115
CUDA: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading: initialization error
, all_cost:0.55, Tstamp:1602008338.18)
```
I tried to look into the problematic function (AllocateDataSpace:108) in `cuda_device_api.cc`. It seems that `cudaSetDevice()` does not able to find the device, and program builder just aborted from there. 

```c++
    if (ctx.device_type == kDLCPUPinned) {
      CUDA_CALL(cudaMallocHost(&ret, nbytes));
    } else {
      CUDA_CALL(cudaSetDevice(ctx.device_id));
      CUDA_CALL(cudaMalloc(&ret, nbytes));
    }
```

This is quite wired. Everything can run smoothly using the python API. But when using C++ APIs, the runtime cannot detect the device or context, and thus cannot find usable schedules.

**Comment by comaniac** [comment]
I see, so the same setting and tuning task work with the Python APIs but not the C++ APIs. Then it might be something that has been handled in the Python API before passing to the C++.

Could you try to create an RPC runner by referring to https://github.com/apache/incubator-tvm/blob/master/python/tvm/auto_scheduler/measure.py#L399-L414 to see if that works or not?

**Comment by Hecmay** [comment]
Okay. Thanks! Will try that. I was using the local runner and that might be the issue.

**Comment by comaniac** [comment]
It's recommended to use RPC runner for GPUs so that we can isolate the CUDA context and other environments. Some issues have been reported that a CUDA context cannot be shared between parent and child threads due to the memory mapping.

**Comment by Hecmay** [comment]
RPC runner works. Thanks Cody!
