### ISSUE TITLE
Incorrect data type in relay causes abort() rather than exception

### ISSUE THREAD

**Issue by areusch** [apache/incubator-tvm#6653]
We should not abort() the whole Python instance just because someone passed the incorrect data type (or, as seems more likely in this case, the parser is misconfigured to produce `kTVMObjectHandle` from `data_layout` attributes instead of `kTVMStr`).

To reproduce at `2cfbd093be048ca04cbedd36e9c63f76e2e59bce`, create `repro_bug.py`:
```
import tvm

RELAY_MODEL = """
#[version = "0.0.5"]
def @main(%data : Tensor[(1, 64, 64, 3), uint8], %conv0_weight : Tensor[(5, 5, 8, 3), int8]) {
    %1 = nn.conv2d(
         %data,
         %conv0_weight,
         padding=[2, 2],
         channels=32,
         kernel_size=[5, 5],
         data_layout="NHWC",
         kernel_layout="HWOI",
         out_dtype="int32");
  %1
}
"""

model = tvm.parser.fromtext(RELAY_MODEL)
```

Output:
```
$ poetry run python3 repro_bug.py
libc++abi.dylib: terminating with uncaught exception of type tvm::AttrError: AttributeError:relay.attrs.Conv2DAttrs: Cannot find required field 'data_layout' during initialization.If the key is defined check that its type matches the declared type.
Abort trap: 6
```

Expected output:
```
Expect str
```
(I.e. the LOG(FATAL) [here](https://github.com/apache/incubator-tvm/blob/8348a44b9a915fe2fb2ead44c8bf3d1be126ff8d/include/tvm/ir/attrs.h#L418))

Really, we expect a proper error raised, but it would have the same effect on this bug.

cc @jroesch @tqchen

**Comment by areusch** [comment]
Offending `throw`: https://github.com/apache/incubator-tvm/blob/8348a44b9a915fe2fb2ead44c8bf3d1be126ff8d/include/tvm/ir/attrs.h#L358

**Comment by tqchen** [comment]
In this case the problem is not in the throw, but the exception being raised in a destructor. The particular destructor is already being marked as enable throw and is fine, so it we need to look up the stacktrace to see what destructor causes the problem

**Comment by areusch** [comment]
My POV is that throwing in a destructor is bad because it will necessarily obscure any LOG(FATAL) raised during the lifetime of the object. This could happen from LOG(FATAL) in any invoked function as well. I think we should by convention not allow marking destructors as `DMLC_THROW_EXCEPTION` because of this behavior. It's implicit and hard to catch in a code review, and it means error reports take longer to root cause.

The specific problem is that we are trying to set a string attribute value using a TVMObjectHandle. But, you can't see that because the destructor throws and we don't support chained exceptions. 

I see the benefits of writing the overall attrs mechanism this way, but it seems like the main use cases for using exceptions in the destructor are in invoking other visitors and in the AttrInitEntry object. In the AttrInitEntry object, we could just move the destructor logic to a Validate() function. In the AttrNonDefaultVisitor case, we could just build up a list of visitable fields in the AttrNonDefaultEntry destructor, and visit them a function defined on AttrNonDefaultVisitor. I don't believe visitors are recursive here, correct me if I am wrong.

**Comment by tqchen** [comment]
I agree that destructor throw should be rare(we only have very few of them), but in this particular case it is intended behavior(in the AttrInit). And we need to use this way to support the particular syntax to declare fields in an Attrs.

We should, however, find out what destructor causes the abort(it is certainly not the AttrInit because it can throw) and fix that destructor.

**Comment by areusch** [comment]
it's probably aborting because an exception was raised while unwinding the stack because of a different exception?

I don't think you need to actually raise the exception in the destructor here to get what you want. I think you can work around it and raise the exception in the Visitor instead of the Entry, unless there are other Visitor usages outside of `attr.h` i'm not seeing. it won't be automatic (I.e. the visitor will have to explicitly check that there were no problems in the visit), but i think explicitly specifying where a CHECK fail may occur is better than letting it occur randomly (i.e. whenever the c++ compiler decides to free the Entry) based on user input. see my previous post.

**Comment by areusch** [comment]
it looks like a patch was merged shortly after I reported this that fixed string parsing. I reverted that patch and couldn't trigger this error anymore, so something else changed. i'll close this issue since it seems to be resolved.

separately, we should probably work to remove all throws in destructors, but that's not this bug.
