### ISSUE TITLE
[CI] Build doc environment isolation

### ISSUE THREAD

**Issue by comaniac** [apache/incubator-tvm#6727]
In the past 2 days all CI are failed at the auto-scheduler tutorials, we found that the reason is the auto-scheduler tutorial generates a tuning log with a fixed name (e.g., `conv2d.json`). Apparently, the docs building stage in CI is executed in the same path for all PRs. As a result, `conv2d.json` keeps increasing and now has more than one thousand lines (one run should only generate 10 lines), and this is dangerous. For this case, #6671 changes the log format and its CI wrote the changed log to `conv2d.json`. Since this line is incompatible, all of CI runs failed to read this line as they are based on the main branch.

While we are working on solving this issue in the auto-scheduler tutorial by using a temporary file as the log file (temporary disable tutorial in #6723 ), we should prevent this problem from happening again. There are some options:

1. Make sure every CI runs are isolated and clean.

2. Make sure all files generated from tutorial scripts are unique and deleted afterward.

3. Make sure all files generated from tutorial scripts have `.log` extension so that the clean script can remove it before starting another run (not sure if this is true. need confirm.)

cc @tqchen @merrymercy @junrushao1994 @jroesch

**Comment by junrushao1994** [comment]
CC: @areusch @electriclilies

**Comment by tqchen** [comment]
Let us save the files into a temp folder, and clean cleanup these states before run, see also https://github.com/apache/incubator-tvm/blob/main/tests/scripts/task_python_docs.sh#L39 for some previous examples.
