### ISSUE TITLE
run example for tvm complie tensorflow model， It's very slow

### ISSUE THREAD

**Issue by jiesonshan** [apache/incubator-tvm#6737]
WARNING:strategy:For x86 target, NCHW layout is recommended for conv2d.
WARNING:strategy:For x86 target, NCHW layout is recommended for conv2d.
WARNING:strategy:For x86 target, NCHW layout is recommended for conv2d.
WARNING:strategy:For x86 target, NCHW layout is recommended for conv2d.
WARNING:strategy:For x86 target, NCHW layout is recommended for conv2d.
WARNING:strategy:For x86 target, NCHW layout is recommended for conv2d.
tvm:  2.159142017364502
tvm:  2.1827878952026367
tvm:  2.186274528503418
tvm:  1.9802303314208984
tvm:  2.016192674636841
tvm:  2.0197951793670654
tvm:  1.995375156402588
tvm:  2.2087066173553467
tvm:  2.593811511993408
tvm:  2.403001070022583
African elephant, Loxodonta africana (score = 0.58335)
tusker (score = 0.33901)
Indian elephant, Elephas maximus (score = 0.02391)

**Comment by tqchen** [comment]
Please use https://discuss.tvm.apache.org/ for related topics
