### ISSUE TITLE
Failed to load .so file using C++ api

### ISSUE THREAD

**Issue by aiblackmaner** [apache/incubator-tvm#6742]
Hi， when I used C + + in Ubuntu 16 to load my resnet-18 model of auto tuning on the python side, I used
**TVM:: Runtime:: module Mod_ lib = tvm::runtime::Module::LoadFromFile("…/params/deploy_ lib.so ")**
; an exception was thrown: undefined reference to TVM:: Runtime:: module:: loadfromfile (STD::__ cxx11::basic_ string<char, std::char_ traits<char>, std::allocator<char> > const&, std::__ cxx11::basic_ string<char, std::char_ traits<char>, std::allocator<char> > const&)' When I add: add_definitions(-D_ GLIBCXX_ USE_ CXX11_ ABI = 0) to my cmake file, another exception is thrown: undefined reference to TVM:: Runtime:: module:: loadfromfile (STD:: String const & and STD:: String const &) ’ Is there anyone who has any suggestions for my mistake? It’s a little difficult to learn TVM for the first time. I use the environment: ubuntu16.04, gcc5.4, thanks a lot!

**Comment by zhiics** [comment]
Please send it to the discuss (https://discuss.tvm.apache.org/) forum for help.
