### ISSUE TITLE
micro_tflite.ipynb import tvm issue in Colab

### ISSUE THREAD

**Issue by danilopau** [apache/incubator-tvm#6743]
Hello, I downloaded the notebook from here https://tvm.apache.org/docs/tutorials/micro/micro_tflite.html#sphx-glr-tutorials-micro-micro-tflite-py, and run in Colab

I got ModuleNotFoundError: No module named 'tvm'

Then I added 
!pip install tflite==2.1.0 --user
!pip install tvm
!set PYTHONPATH to .:/usr/local/lib/python3.6/

error is still there. Wuuld you please help becuase it doesn't work as provided out of the box

Thanks and kind regards
Danilo

**Comment by zhiics** [comment]
Please create a thread at https://discuss.tvm.apache.org/ for help. You probably need to point your PYTHONPATH to where TVM is installed as well.
