### ISSUE TITLE
opencl build error when run onnx model at windows.

### ISSUE THREAD

**Issue by wyx-1978** [apache/incubator-tvm#6770]
I had download TVM code at the lastest commit on master branch.
Then convert my model file (*.pb) to dll file in windows, dll can run by python system successfully.
but when i use c++ to load dll and run the model, TVM throw error as bellow.

 "TVMError: OpenCL build error for device=000002431E0BE180ptxas error   : Entry function 'fused_nn_conv2d_18_kernel0' uses too much shared data (0xc9c4 bytes, 0xc000 max)
Stack trace:
  File "f:\imgblur_new_tvm\imgblur\src\lib\tvm\opencl\opencl_module.cc", line 314
"
I had check the code again and again, from input data ,out put data, tvm_runtime_pack and so on, i had even modify cpp_deploy demo to run my model. It always throw the same error.
Does anyone know how to solve the issue? 
Thanks!

**Comment by tqchen** [comment]
move to https://discuss.tvm.apache.org/t/opencl-build-error-when-run-onnx-model-at-windows/8301
