### ISSUE TITLE
[TEST][FLAKY] auto_scheduler layout rewrite tests

### ISSUE THREAD

**Issue by comaniac** [apache/incubator-tvm#6843]
Two tests introduced by #6750 have been disabled by #6841 due to flaky. It'd be better to resolve the root cause and re-open them.

Reference failures:
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/124/pipeline

cc @jcf94 @merrymercy

**Comment by masahi** [comment]
it's being worked on at https://github.com/apache/incubator-tvm/pull/6830

**Comment by comaniac** [comment]
Ah thanks for the connection. Then we can close this issue once #6830 is merged.
