### ISSUE TITLE
Not able to compile TVM with Arm Compute library

### ISSUE THREAD

**Issue by joyalbin** [apache/incubator-tvm#6857]
Hi,

Followed the below tutorial to build TVM with ARM Compute library. 
https://github.com/apache/incubator-tvm/blob/e561007f0c330e3d14c2bc8a3ef40fb741db9004/docs/deploy/arm_compute_lib.rst 

Steps followed:
1. Enabled USE_ARM_COMPUTE_LIB and USE_ARM_COMPUTE_LIB_GRAPH_RUNTIME in config.cmake
2. setup the prebuild library at $TVM_HOME/acl
3. Trying to build TVM with acl

This cause the issue, failed to resolve the arm compiler header file dependency in the acl source files while building TVM with cmake.
When I enable USE_ARM_COMPUTE_LIB_GRAPH_RUNTIME=ON and build TVM, it expect to include arm compiler headers (arm_neon.h) and by default its not happening. Any thing extra I have do?

`"These flags can be used in different scenarios depending on your setup. For example, if you want to compile an ACL module on an x86 machine and then run the module on a remote Arm device via RPC, you will need to use USE_ARM_COMPUTE_LIB=ON on the x86 machine and USE_ARM_COMPUTE_LIB_GRAPH_RUNTIME=ON on the remote AArch64 device."`

Someone please help to understand what exactly meant by `"USE_ARM_COMPUTE_LIB_GRAPH_RUNTIME=ON on the remote AArch64 device."`? In which case this flag as to be enabled? we don't need to build TVM after enabling this flag?

**Comment by joyalbin** [comment]
@lhutton1 Could you please help me on this?

**Comment by joyalbin** [comment]
Hi All,
While building TVM with flags USE_ARM_COMPUTE_LIB_GRAPH_RUNTIME and USE_ARM_COMPUTE_LIB set to ON, am getting below error:

![image](https://user-images.githubusercontent.com/1856674/98319564-02470200-2007-11eb-9ad5-0babc9385cbc.png)

Please help me to understand how to use this feature

**Comment by giuseros** [comment]
Hi @joyalbin ,
So Arm Compute Library is a runtime library, and it is meant to run on Arm machines. The usual setup is the following:
- A: is the machine where you are actually compiling your network. Which is usually a x86 machine. 
- B: is the machine where you run the network (e.g., through RPC). This should be an Arm machine. 

About the flags:
- On machine A, you need build TVM with USE_ARM_COMPUTE_LIB  to ON. In that way you tell the (Relay) compiler  to annotate the Arm Compute LIbrary supported operators. 

- On machine B , you need to only build the runtime with  USE_ARM_COMPUTE_LIB_GRAPH_RUNTIME to ON. This is telling the runtime that whenever it sees an annotated operator, it should run it through the Arm Compute Library. Just to be clear, on machine B, you usually build only the runtime part of TVM (i.e., `make -j4 runtime`)

Some more info about all this: 
- https://tvm.apache.org/2020/07/15/how-to-bring-your-own-codegen-to-tvm
- https://tvm.apache.org/docs/deploy/arm_compute_lib.html?highlight=acl
- https://discuss.tvm.apache.org/t/rfc-byoc-arm-compute-library-integration/7082

Hope this helps

**Comment by tqchen** [comment]
Good discussion, seems this topic is more suitable for https://discuss.tvm.apache.org/, let us move the discussion thread
