### ISSUE TITLE
gcc8.2 compile error

### ISSUE THREAD

**Issue by zhxfl** [apache/incubator-tvm#6891]
/home/disk2/zhengzaoxin/code/tvm_v07_gcc82/include/tvm/runtime/packed_func.h: In instantiation of ‘TObjectRef tvm::runtime::TVMPODValue_::AsObjectRef() const [with TObjectRef = tvm::runtime::DataType]’:
/home/disk2/zhengzaoxin/code/tvm_v07_gcc82/include/tvm/runtime/packed_func.h:880:87:   required from ‘static TObjectRef tvm::runtime::PackedFuncValueConverter<TObjectRef>::From(const tvm::runtime::TVMArgValue&) [with TObjectRef = tvm::runtime::DataType]’
/home/disk2/zhengzaoxin/code/tvm_v07_gcc82/include/tvm/runtime/packed_func.h:1453:43:   required from ‘tvm::runtime::TVMArgValue::operator T() const [with T = tvm::runtime::DataType; <template-parameter-1-2> = void]’
/home/disk2/zhengzaoxin/code/tvm_v07_gcc82/include/tvm/ir/attrs.h:403:8:   required from ‘void tvm::detail::SetValue(T*, const tvm::runtime::TVMArgValue&) [with T = tvm::runtime::DataType]’
/home/disk2/zhengzaoxin/code/tvm_v07_gcc82/include/tvm/ir/attrs.h:476:15:   required from ‘tvm::detail::AttrInitEntry<T> tvm::detail::AttrInitVisitor<FFind>::operator()(const char*, T*) [with T = tvm::runtime::DataType; FFind = tvm::AttrsNode<DerivedType>::InitByPackedArgs(const tvm::runtime::TVMArgs&, bool) [with DerivedType = tvm::relay::ArgsortAttrs]::<lambda(const char*, tvm::runtime::TVMArgValue*)>]’
/home/disk2/zhengzaoxin/code/tvm_v07_gcc82/include/tvm/relay/attrs/algorithm.h:49:5:   required from ‘void tvm::relay::ArgsortAttrs::__VisitAttrs__(FVisit&) [with FVisit = tvm::detail::AttrInitVisitor<tvm::AttrsNode<DerivedType>::InitByPackedArgs(const tvm::runtime::TVMArgs&, bool) [with DerivedType = tvm::relay::ArgsortAttrs]::<lambda(const char*, tvm::runtime::TVMArgValue*)> >]’
/home/disk2/zhengzaoxin/code/tvm_v07_gcc82/include/tvm/ir/attrs.h:684:7:   required from ‘void tvm::AttrsNode<DerivedType>::InitByPackedArgs(const tvm::runtime::TVMArgs&, bool) [with DerivedType = tvm::relay::ArgsortAttrs]’
/home/disk2/zhengzaoxin/code/tvm_v07_gcc82/include/tvm/ir/attrs.h:666:8:   required from here
/home/disk2/zhengzaoxin/code/tvm_v07_gcc82/include/tvm/runtime/packed_func.h:1373:17: 错误：static assertion failed: Conversion only works for ObjectRef
   static_assert(std::is_base_of<ObjectRef, TObjectRef>::value,
                 ^~~
/home/disk2/zhengzaoxin/code/tvm_v07_gcc82/include/tvm/runtime/packed_func.h:1375:59: 错误：no type named ‘ContainerType’ in ‘class tvm::runtime::DataType’
   using ContainerType = typename TObjectRef::ContainerType

**Comment by zhxfl** [comment]
DataType is not a Derived classof ObjectRef.
static_assert(std::is_base_of<ObjectRef, DataType>) fail; 
gcc53 can compile sussess

**Comment by FrozenGene** [comment]
https://github.com/apache/incubator-tvm/pull/6893 should solve the this issue @zhxfl

**Comment by zhxfl** [comment]
fix now & tks
