### ISSUE TITLE
run the tutourials file failed cuda is not enable 

### ISSUE THREAD

**Issue by piaodangdang** [apache/incubator-tvm#6895]
I build in Ubuntu 1804  cuda 10.1 cuddnn 7.6  I've set use_cuda on  but I run the relay_quick_start.ipynb it still tell me cuda is not enable when build, How can I fix it ?

**Comment by piaodangdang** [comment]
when i build on window 10 , set use llvm path to llvm, build in visual studio 2019 ,the mentioned is 
1>------ 已跳过生成: 项目: cpptest, 配置: Release x64 ------
1>没有为此解决方案配置选中要生成的项目 
2>------ 已启动生成: 项目: tvm, 配置: Release x64 ------
3>------ 已跳过生成: 项目: runtime, 配置: Release x64 ------
3>没有为此解决方案配置选中要生成的项目 
2>LINK : fatal error LNK1181: 无法打开输入文件“z.lib”
2>已完成生成项目“tvm.vcxproj”的操作 - 失败。
4>------ 已跳过生成: 项目: INSTALL, 配置: Release x64 ------
4>没有为此解决方案配置选中要生成的项目 
========== 生成: 成功 0 个，失败 1 个，最新 4 个，跳过 3 个 ==========

**Comment by tqchen** [comment]
please open a new thread on https://discuss.tvm.apache.org/

**Comment by laolihaile** [comment]
I have the same problem, how can I solve it?There is no corresponding solution on the https://discuss.tvm.apache.org/
