### ISSUE TITLE
relay.build not support size_var?

### ISSUE THREAD

**Issue by zhxfl** [apache/incubator-tvm#6942]
here is the test code 
** 80 def test_dropout():
 81     for dtype in ["float16", "float32"]:
 82         #n, t, d = 1024, 1024, 1024
 83         n, t, d = te.size_var("n"), 1024, 1024
 84         input_ty = relay.TensorType((n, t, d), dtype)
 85         x = relay.var("x", input_ty)
 86         y = relay.nn.dropout(x, rate=0.75)
 87         mod = tvm.IRModule.from_expr(relay.Function([x], y))
 88         compiled_lib = relay.build(mod, tvm.target.create("cuda"))
 89         assert "rate=" in y.astext()
 90         yy = run_infer_type(y)
 91         assert yy.checked_type == input_ty
**
the graph_plan_memory.cc:GetMemorySize check(dim) fail

**Comment by zhiics** [comment]
Yes, you have to use Realy VM for dynamic input.

**Comment by zhxfl** [comment]
"Realy VM for dynamic input" can export a lib for "C++" runtime just as "relay.build" ?
